### ISSUE TITLE
missing MSFragger parameter in pipeline

### ISSUE THREAD

**Issue by kevinkovalchik** [Nesvilab/philosopher#100]
Hello,

I am trying to set up a pipeline in philosopher using MSFragger. When running it I am getting an error which leads me to think the pipeline is trying to pass a parameter to MSFragger that is undefined:

```
> philosopher pipeline --config ./msfragger_pipe.yml  ./
INFO[19:05:17] Executing Pipeline  v2.1.1                   
INFO[19:05:17] Initiating the workspace on ./               
INFO[19:05:18] Creating workspace                           
WARN[19:05:18] A meta data folder was found and will not be overwritten.  
INFO[19:05:18] Processing database                          
INFO[19:05:20] Running the Database Search on all data      
MSFragger version MSFragger-2.1
Batmass-IO version 1.16.1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 1.8.0_162, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 18204 MB memory

remove_precursor_range has an empty value.
INFO[19:05:22] Running the validation and inference on ./   
INFO[19:05:22] Executing PeptideProphet on ./               
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/ext/peptideprophet.interactParser(0xc0003be840, 0x38, 0xc0003be880, 0x37, 0xc0003be8c0, 0x3e, 0xc0003be900, 0x3c, 0xc0003be940, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:218 +0x2244
philosopher/lib/ext/peptideprophet.PeptideProphet.Execute(0xc0003be840, 0x38, 0xc0003be880, 0x37, 0xc0003be8c0, 0x3e, 0xc0003be900, 0x3c, 0xc0003be940, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:125 +0x1bd
philosopher/lib/ext/peptideprophet.Run(0xc0000aa330, 0x24, 0xc0003be7c0, 0x38, 0xc0000aa390, 0x29, 0xc002265180, 0x47, 0xc0003be800, 0x3e, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:70 +0x4dc
philosopher/lib/pip.Prophets(0xc0000aa0c0, 0x24, 0xc0003be100, 0x38, 0xc0000aa0f0, 0x29, 0xc0022640a0, 0x47, 0xc0003be140, 0x3e, ...)
	/workspace/philosopher/lib/pip/pip.go:229 +0xaf7
philosopher/cmd.glob..func13(0x86f99e0, 0xc000129da0, 0x1, 0x3)
	/workspace/philosopher/cmd/pipeline.go:76 +0x512
github.com/spf13/cobra.(*Command).execute(0x86f99e0, 0xc000129d40, 0x3, 0x3, 0x86f99e0, 0xc000129d40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x86fa3e0, 0x0, 0x0, 0x0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:34 +0x2d
main.main()
	/workspace/philosopher/main.go:22 +0x6e
```

When MSFragger starts, it quits right away with the statement `remove_precursor_range has an empty value.` Then the rest of the pipeline crashes of course because there are no .pepXML files.

Here are my pipeline.yml file and msfragger params:

[msfragger_pipe.yml.txt](https://github.com/Nesvilab/philosopher/files/4167315/msfragger_pipe.yml.txt)
[nonspecific_fragger.params.txt](https://github.com/Nesvilab/philosopher/files/4167317/nonspecific_fragger.params.txt)

You can see that `remove_precursor_range` is set in the msfragger parameters. Also, that same parameter does not exist in the default pipeline config file. It seems that the pipeline passes this parameter to msfragger, but there is no way to set a value. I tried adding it to the pipeline config file, but that did not solve the issue.

I'm a little confused as to what is going on with msfragger in the pipeline, because I am able to point it to an msfragger parameter file, but it seems to be overriding those parameters with command line parameters. For example, if I specify an enzyme in the msfragger params, and leave that space empty in the pipeline config, msfragger reports that `search_enzyme_name has an empty value.`

I tested a comet pipeline as well and it ran fine.

Thanks for any help you can provide!
Kevin

**Comment by prvst** [comment]
I think you are using the pipeline parameter file from the previous version, I don't see the option in your file. Open a terminal and type `philosopher pipeline --print` to get the most recent version, that should work for you.

**Comment by anesvi** [comment]
Also, you should get MSFragger 2.3. The latest version of philosopher will work with MSFragger 2.3, but could have issues with earlier versions.

**Comment by kevinkovalchik** [comment]
Ah yes, thanks. I did make the parameter file a few days ago, and since then built the latest philosopher container. I'll try that and see how it goes.

**Comment by kevinkovalchik** [comment]
The pipeline is running using the proper config file. However, I am still not sure how the parameters from msfragger.params and pipeline.yml are handled. Is the msfragger.params file supposed to be the default parameters? I have defined `decoy_prefix` in my msfragger.params to be "rev_", but when I run the pipeline it shows this message: `There is no decoy_prefix parameter. Changing calibrate_mass from 2 to 1`.

**Comment by prvst** [comment]
You can run MSFragger independently our within the pipeline via Philosopher. If done independently you will need to pass a msfragger.params file to the program. If done via pipeline, then you won't need that parameter file, just fill up the parameters inside the yml file.

**Comment by kevinkovalchik** [comment]
Okay, but it seems like not all the parameters are in the yml file. I specified a decoy_tag in the database section, but this does not get passed on the msfragger and there is no corresponding parameter under the msfragger section of the yml file.

For example, when I use this yml file:

[msfragger_pipe.yml.txt](https://github.com/Nesvilab/philosopher/files/4171535/msfragger_pipe.yml.txt)

This is the output:
```
MSFragger version MSFragger-2.3
Batmass-IO version 1.17.2
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 1.8.0_162, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 17 GB memory

There is no decoy_prefix parameter. Changing calibrate_mass from 2 to 1 (i.e., Calibrate the mass but don't find the optimal parameters.).
Checking /home/caron/Projects/Analysis/SearchComparison/msfragger/160331_DK_BD-ZH03_Thyroid_postSCX_W_8%_DDA_#1_400-650mz_msms25.mzML...
...
```
Is the `decoy_prefix` parameter from the database section supposed to propagate to msfragger?

**Comment by prvst** [comment]
the decoy parameter is only necessary when fragger is doing parameter optimizations, it's not a required for doing database searches.

**Comment by anesvi** [comment]
Felipe, since parameter optimization is done for MSFragger, it is needed when the user specifies parameter optimization.  Philosopher needs to pass that info.

**Comment by prvst** [comment]
I'll add the decoy name to fragger parameter list internally, then it will always be passed on to the search

**Comment by anesvi** [comment]
It would be good if you generate fragger.params file when running yaml file. That way, one can see what was actually sued for MSFragger search. And one can repeat the search.
