### ISSUE TITLE
Running pipeline without ProteinProphet

### ISSUE THREAD

**Issue by kevinkovalchik** [Nesvilab/philosopher#101]
Hello,

I am having trouble running a pipeline without ProteinProphet in Philosopher. The problem seems to be that I have turned off ProteinProphet in the config file, but when it gets to the filtering step it tries to open the expected output file from ProteinProphet:
```
FATA[12:34:47] Cannot read file. open interact.prot.xml: no such file or directory
```
Can I change the Filter parameters in the config file to prevent this? There isn't an obvious switch that I can see.

Thanks

**Comment by prvst** [comment]
Yes, you are right , the pipeline is expecting to have a protxml file inside the workspace, I'll change that and add the fix to the next minor release.

**Comment by javanOkendo** [comment]
I am also having this type of error @prvst 
file 1: /scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.pepXML
Unknown file type. No file loaded./scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.mzBIN_calibrated
WARNING: cannot open data file /scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
/scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.mzML(1) : parseOffset() 4: Syntax error parsing XML.
time="21:22:34" level=fatal msg="Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files"
time="21:22:35" level=info msg="Executing Workspace  v2.1.1"
time="21:22:36" level=info msg="Removing workspace"
time="21:22:36" level=info msg=Done

**Comment by prvst** [comment]
Fixed. Added to v3.2.2
