### ISSUE TITLE
Error when running the peptideprophet on some of my raw files

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/philosopher#102]
Operating on slice 6 of 7:
        001. 180712_C0_CH_T042BCG.mzBIN_calibrated 4.8 s [progress: 47410/47410 (100.00%) - 94254.47 spectra/s] - completed 0.5 s
        002. 180712_C0_CH_T042BCG.mzBIN_calibrated 4.9 s [progress: 47410/47410 (100.00%) - 94820.00 spectra/s] - completed 0.5 s
        003. 180712_C0_CH_T061BCG.mzBIN_calibrated 4.5 s [progress: 44591/44591 (100.00%) - 89182.00 spectra/s] - completed 0.5 s
        004. 180712_C0_CH_T061BCG.mzBIN_calibrated 4.4 s [progress: 44591/44591 (100.00%) - 89003.99 spectra/s] - completed 0.5 s
        005. 180712_C0_CH_T062P.mzBIN_calibrated 3.7 s [progress: 37702/37702 (100.00%) - 94019.95 spectra/s] - completed 0.4 s
        006. 180712_C0_CH_T062P.mzBIN_calibrated 3.5 s [progress: 37702/37702 (100.00%) - 86870.97 spectra/s] - completed 0.4 s
        007. 180712_C0_CH_T080BCG.mzBIN_calibrated 3.7 s [progress: 38652/38652 (100.00%) - 95201.97 spectra/s] - completed 0.4 s
        008. 180712_C0_CH_T080BCG.mzBIN_calibrated 3.7 s [progress: 38652/38652 (100.00%) - 96389.03 spectra/s] - completed 0.4 s
        009. 180712_C0_CH_T083BCG.mzBIN_calibrated 4.8 s [progress: 47542/47542 (100.00%) - 94894.21 spectra/s] - completed 0.5 s
        010. 180712_C0_CH_T083BCG.mzBIN_calibrated 4.9 s [progress: 47542/47542 (100.00%) - 79104.83 spectra/s] - completed 0.6 s
Operating on slice 7 of 7:
        001. 180712_C0_CH_T042BCG.mzBIN_calibrated 4.6 s [progress: 47410/47410 (100.00%) - 63129.16 spectra/s] - completed 0.8 s
        002. 180712_C0_CH_T042BCG.mzBIN_calibrated 4.7 s [progress: 47410/47410 (100.00%) - 94820.00 spectra/s] - completed 0.5 s
        003. 180712_C0_CH_T061BCG.mzBIN_calibrated 4.7 s [progress: 44591/44591 (100.00%) - 89003.99 spectra/s] - completed 0.5 s
        004. 180712_C0_CH_T061BCG.mzBIN_calibrated 5.0 s [progress: 44591/44591 (100.00%) - 89003.99 spectra/s] - completed 0.5 s
        005. 180712_C0_CH_T062P.mzBIN_calibrated 3.7 s [progress: 37702/37702 (100.00%) - 75253.49 spectra/s] - completed 0.5 s
        006. 180712_C0_CH_T062P.mzBIN_calibrated 3.9 s [progress: 37702/37702 (100.00%) - 94019.95 spectra/s] - completed 0.4 s
        007. 180712_C0_CH_T080BCG.mzBIN_calibrated 3.5 s [progress: 38652/38652 (100.00%) - 77149.70 spectra/s] - completed 0.5 s
        008. 180712_C0_CH_T080BCG.mzBIN_calibrated 4.1 s [progress: 38652/38652 (100.00%) - 77149.70 spectra/s] - completed 0.5 s
        009. 180712_C0_CH_T083BCG.mzBIN_calibrated 4.9 s [progress: 47542/47542 (100.00%) - 67055.01 spectra/s] - completed 0.7 s
        010. 180712_C0_CH_T083BCG.mzBIN_calibrated 4.6 s [progress: 47542/47542 (100.00%) - 55931.76 spectra/s] - completed 0.9 s
***************************MAIN SEARCH DONE IN 7.738 MIN***************************

*******************************TOTAL TIME 12.881 MIN********************************
time="21:22:30" level=info msg="Running the validation and inference on LTBI"
time="21:22:30" level=info msg="Executing PeptideProphet on LTBI"
 file 1: /scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.pepXML
Unknown file type. No file loaded./scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.mzBIN_calibrated
WARNING: cannot open data file /scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
/scratch/oknjav001/proteomics/bad_RawFiles/LTBI/180712_C0_CH_T042BCG.mzML(1) : parseOffset() 4: Syntax error parsing XML.
time="21:22:34" level=fatal msg="Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files"
time="21:22:35" level=info msg="Executing Workspace  v2.1.1"
time="21:22:36" level=info msg="Removing workspace"
time="21:22:36" level=info msg=Done

**Comment by javanOkendo** [comment]
Unknown file type. No file loaded./scratch/oknjav001/bal_mzML_raw_files/LTBI_mgf/180712_C0_CH_T042BCG.mgf
WARNING: cannot open data file /scratch/oknjav001/bal_mzML_raw_files/LTBI_mgf/180712_C0_CH_T042BCG.mgf in msms_run_summary tag... unrecognized extension .mgf, trying .mzML ...
WARNING: CANNOT correct data file /scratch/oknjav001/bal_mzML_raw_files/LTBI_mgf/180712_C0_CH_T042BCG.mzML in msms_run_summary tag...
Unknown file type. No file loaded./scratch/oknjav001/bal_mzML_raw_files/LTBI_mgf/180712_C0_CH_T042BCG.mgf
WARNING: cannot open data file /scratch/oknjav001/bal_mzML_raw_files/LTBI_mgf/180712_C0_CH_T042BCG.mgf in msms_run_summary tag... unrecognized extension .mgf, trying .mzML ...
WARNING: CANNOT correct data file /scratch/oknjav001/bal_mzML_raw_files/LTBI_mgf/180712_C0_CH_T042BCG.mzML in msms_run_summary tag...
time="08:48:35" level=fatal msg="Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files"

**Comment by prvst** [comment]
are you running from the command line ? Can you show me the commands you executed ?
