### ISSUE TITLE
Requesting for Philoshopher source code to compile it on HPC Cluster

### ISSUE THREAD

**Issue by HiteshKore** [Nesvilab/philosopher#103]
Hello, 

I am currently using MSFragger followed by Philosopher to analyze the Mass-Spectrometry data. I want to compile Philospher from its source code on the HPC cluster with CenOS Linux distribution. I am not able to compile it using the tar file provided on below the URL:
https://github.com/Nesvilab/philosopher/releases/tag/v2.1.1

Are there any additional files required to compile the philosopher from its source code? Could you please provide me the source code for the same?
Lastly, I would like to thank you in advance for your support with regard to this issue.

Best Regards,
Hitesh

**Comment by prvst** [comment]
@HiteshKore 

The source code will be entirely available once our publication is out, hopefully not too far from now. We are currently distributing Philosopher in different ways, including .deb, .rpm and binary. The binaries are compiled to machine language so you should be able to execute them on your cluster. You can find the latest version [here](https://github.com/Nesvilab/philosopher/releases/download/v2.1.1/philosopher_v2.1.1_linux_amd64.zip).
