### ISSUE TITLE
Warnings in PeptideProphet

### ISSUE THREAD

**Issue by kevinkovalchik** [Nesvilab/philosopher#106]
Hello,

I see something like this a lot when running PeptideProphet after MSFragger from Philosopher:
```
 file 1: /data/systemhc_test/Work/2020-02-20_13:48:31.453987/171212_MG_TUMAPs_1fm_JY17#4_aufgetaut20171208_DDA_400-650mz_msms47.pepXML
Unknown file type. No file loaded./data/systemhc_test/Work/2020-02-20_13:48:31.453987/171212_MG_TUMAPs_1fm_JY17#4_aufgetaut20171208_DDA_400-650mz_msms47.mzBIN_calibrated
WARNING: cannot open data file /data/systemhc_test/Work/2020-02-20_13:48:31.453987/171212_MG_TUMAPs_1fm_JY17#4_aufgetaut20171208_DDA_400-650mz_msms47.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
SUCCESS: CORRECTED data file /data/systemhc_test/Work/2020-02-20_13:48:31.453987/171212_MG_TUMAPs_1fm_JY17#4_aufgetaut20171208_DDA_400-650mz_msms47.mzML in msms_run_summary tag...
 processed altogether 17539 results
INFO: Results written to file: /data/systemhc_test/Work/2020-02-20_13:48:31.453987/interact-171212_MG_TUMAPs_1fm_JY17#4_aufgetaut20171208_DDA_400-650mz_msms47.pep.xml
```

What is going on with the unknown file type and the WARNING message? It seems like PeptideProphet is expecting to find `.mzBIN_calibrated` files. I've watched the directory during the MSFragger search, and `.mzBIN_calibrated` files appear, but then they are cleaned up as soon as the search is done. Is this expected?

Best wishes,
Kevin

**Comment by fcyu** [comment]
Hi Kevin,

That is expected and won't affect your results.

Best,

Fengchao

**Comment by kevinkovalchik** [comment]
Okay, thanks. Just for the sake of my curiosity, could I know why these messages are there? Why is it looking for the files if we expect them to not be there?

**Comment by fcyu** [comment]
PeptideProphet tried to correct scan numbers but it only supports mzML or mzXML. So, it tried to read the file according to the info in pepXML file, when failed, it tried to replace the original extension with mzML and read again.

**Comment by kevinkovalchik** [comment]
Ah, I see.

Thanks,
Kevin
