### ISSUE TITLE
Philosopher filter error

### ISSUE THREAD

**Issue by srithegreat** [Nesvilab/philosopher#108]
I am trying to use Philosopher to create a spectral library. I have used peptideprophet followed by iprophet and peptideprophet to create a combined pep.xml and prot.xml files. When I try the filter option  
COMMAND: philosopher filter --razor --pepxml mascot_xtandem_msgfp_combine.pep.xml --protxml interact.prot.xml  --tag REVERSED_
I get the following error:

INFO[02:50:12] Executing Filter  v2.1.1
INFO[02:50:12] Processing peptide identification files
FATA[02:51:01] Cannot decode packed binary. strconv.ParseFloat: parsing "+-0.0000": invalid syntax

What could be the reason?

Thanks,
Srikanth

**Comment by chhh** [comment]
Can you search your pepxml and protxml files for instances of `+-0.0000`?

**Comment by prvst** [comment]
@srithegreat can you share the file mascot_xtandem_msgfp_combine.pep.xml with me ?

**Comment by srithegreat** [comment]
Here are few lines from the xml when I look for the +-0.0000 string.

<search_hit hit_rank="1" peptide="AEIDMLDIR" peptide_prev_aa="R" peptide_next_aa="A" protein="sp|P09525|ANXA4_HUMAN" num_tot_proteins="1" num_matched_ions="5" tot_num_ions="16" calc_neutral_pep_mass="1074.5457" massdiff="+-0.0000" num_tol_term="2" num_missed_cleavages="0" is_rejected="0" protein_descr="Annexin A4 OS=Homo sapiens OX=9606 GN=ANXA4 PE=1 SV=4">
<search_hit hit_rank="1" peptide="SDIDEIVLVGGSTR" peptide_prev_aa="K" peptide_next_aa="L" protein="sp|P11021|BIP_HUMAN" num_tot_proteins="1" num_matched_ions="6" tot_num_ions="26" calc_neutral_pep_mass="1459.7597" massdiff="+-0.0000" num_tol_term="2" num_missed_cleavages="0" is_rejected="0" protein_descr="Endoplasmic reticulum chaperone BiP OS=Homo sapiens OX=9606 GN=HSPA5 PE=1 SV=2">
<search_hit hit_rank="1" peptide="FINNNAVTK" peptide_prev_aa="R" peptide_next_aa="M" protein="sp|Q13616|CUL1_HUMAN" num_tot_proteins="1" num_matched_ions="7" tot_num_ions="16" calc_neutral_pep_mass="1019.5478" massdiff="+-0.0000" num_tol_term="2" num_missed_cleavages="0" is_rejected="0" protein_descr="Cullin-1 OS=Homo sapiens OX=9606 GN=CUL1 PE=1 SV=2">

**Comment by prvst** [comment]
can you share the file with me ?

**Comment by srithegreat** [comment]
> can you share the file with me ?
Its a huge ~3GB file, is there a secure place where I can share the same?

**Comment by srithegreat** [comment]
Its a huge ~3GB file, is there a secure place where I can share the same?

**Comment by prvst** [comment]
send me your email and I'll send you a file request via Box

**Comment by srithegreat** [comment]
You can share the link on srikanth0403@gmail.com

**Comment by prvst** [comment]
Apparently the `+-0.0000` seems to be only reason for the error you see, you have 7 cases like this. Unfortunately I cannot create a rule for parsing this pattern you would have to figure it out which program outputs this string and maybe change it before using Philosopher.
