### ISSUE TITLE
Channel setting error of iTRAQ quantification 

### ISSUE THREAD

**Issue by chliu1992** [Nesvilab/philosopher#109]
Hey all,
I followed the TMT analysis tutorial https://github.com/Nesvilab/philosopher/wiki/TMT-Analysis for the  iTRAQ.After filtering, I set the annotation.txt file like:

113 SN1
114 SN2
115 SN3
116 SN4
117 M1
118 M2
119 M3
120 M4

Then I run 
philosopher labelquant --plex 8 --dir F:\hearttissue\msfragger_test5

However,the errors of  plex settings happened."
"ERRO: Unknown multiplex setting,please define the plex number used in your experiment"

Has anyone seen this before?What format should I set for iTRAQ channel? 

Thank you for your help.
Best wishes.
Conghui

**Comment by prvst** [comment]
Try adding this flag to your command `--brand itraq`

**Comment by chliu1992** [comment]
@prvst Hi Felipe,
I have tried the flag  you mentioned .Then I ran the command but there were same errors.

"philosopher labelquant --brand itraq --plex 8 --dir F:\hearttissue\msfragger_test5"

Did I write a wrong format?May you have some other advices?

Best wishes,
Conghui.

**Comment by prvst** [comment]
There was a bug in a method used for the iTRAQ quantification, everything is working now, including when I use your files. The update will be online shortly, please keep an eye on the releases (you can turn the notifications on for releases only).

Fixed. Added to v3.2.2

**Comment by chliu1992** [comment]
Get it.Thank you very much.
