### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by trishorts** [Nesvilab/philosopher#114]
running philosopher pipeline

[philosopher.yml and comet.params.zip](https://github.com/Nesvilab/philosopher/files/4320429/philosopher.yml.and.comet.params.zip)

![image](https://user-images.githubusercontent.com/16841846/76456874-c4290e00-63a5-11ea-9914-7955855aa6c4.png)

![image](https://user-images.githubusercontent.com/16841846/76456926-dacf6500-63a5-11ea-8927-674cdf7df89c.png)

**Comment by prvst** [comment]
@trishorts when running the pipeline, Philosopher will look for search results with the `pepXML` extension, instead of the `pep.xml`. This happens because MSFragger outputs `pepXML` and Comet outputs `pep.xml`. I'll add a fix to this on the next small release (probably tomorrow), until there you have two options, you can change the search results extensions to `pepXML` and run from PeptideProphet or you can complete your analysis running each step individually

**Comment by prvst** [comment]
Actually there is a third option that youc an try. On the yaml file, look for the PeptideProphet section and change this:

`  extension: pepXML                            # pepXML file extension`

to this:

`  extension: pep.xml                            # pepXML file extension`

Let me know if that works

**Comment by trishorts** [comment]
LOL. now I'm stuck in an endless loop of search. when the pipeline finishes searching files the first time it just starts all over again without moving on..... maybe workspace cleaan

**Comment by prvst** [comment]
Yes, please try again from the beginning with a clean workspace, let me know if you are still stuck on a loop

**Comment by trishorts** [comment]
no mas. stuck in the endless loop.  deleted .meta folder and all .pep.xml files from the data folder. deleted .meta folder from the E:\Programs\philosopher_v3.2.2_windows_amd64\ folder

**Comment by prvst** [comment]
OK, I'm working on this now

**Comment by prvst** [comment]
You actually found a bug on the pipeline command. I just compile a fix and issue a new release [v.3.2.3](https://github.com/Nesvilab/philosopher/releases/tag/v3.2.3). We haven't been using Comet that much lately because of MSFragger, and recent changes in the pipeline command created the issue you found. Thanks for finding that for us and for reporting. Please go ahead and download the new update and try again, let me know if that works for you. I tested here on my computer with your yaml file and your comet param and I got the final tables in a few minutes.

**Comment by anesvi** [comment]
Dear trishorts,
Thank you for using the tools. As Felipe said, we switched 100% to MSFragger, but should have tested Comet with the latest release better.
Thanks for your patience, hopefully the new release fixes the issue.
Best regards,
Alexey

**Comment by trishorts** [comment]
thank you. i will try to do this tomorrow.

**Comment by trishorts** [comment]
i have found it nearly impossible with my meager skills to install fragger. so the comet solution is easier for me.

**Comment by prvst** [comment]
@trishorts If you want I can assist you with the steps necessary to get MSFragger up and running

**Comment by anesvi** [comment]
FragPipe GUI is the easiest way to run MSFragger with Philosopher, in case you may want to consider that option. But as far as running Comet vs. MSFragger, it should be the same. Except MSFragger may require more memory for certain type of searches.
Best,
Alexey

**Comment by trishorts** [comment]
thank you. you've been so kind and responsive. it's really appreciated. staty tuned

**Comment by trishorts** [comment]
i did have some luck with fragpipe. don't know about the batch stuff. only went thrugh it a couple times. that was pretty nice.

**Comment by chliu1992** [comment]
Hi,
I used three mzML files to take a test with the TMT pipeline following https://github.com/Nesvilab/philosopher/wiki/Pipeline-mode-for-TMT-analysis .
And I created a work folder that conains four subfolder as this tutorial said and set the .yml configuration file.
Before running the pipeline command"philosopher pipeline --config philosopher.yml BAT_tmt", which folder should I run the " philosopher workspace --init " command in?

Thank you very much for your recent help.

**Comment by prvst** [comment]
If you are running the pipeline command, then you don't need to create a workspace, the program will do that for you. The pipeline command should ideally be executed on your work folder where you have your fours subfolders:

`philosopher pipeline --config philosopher.yml folder1 folder2 folder3 folder4`

**Comment by chliu1992** [comment]
I take a try but,

F:\MSFragger_test\BAT_TMT6_data_test>philosopher pipeline --config philosopher.yml BAT_tmt
'philosopher' is not recognized as an internal or external command,
operable program or batch file.

Is there anything wrong with my command or else?

**Comment by prvst** [comment]
@chliu1992 I see that your issue is not actually related to the subject reported here previously bytrishorts, can I ask you to open a new issue with the detailed report of your error or problem ?

Thanks

**Comment by chliu1992** [comment]
ok,I'll open a new issue.Thank you.

**Comment by trishorts** [comment]
I wasn't in yesterday so i wasn't able to try P.3.2.3 until today. This version no longer does the endless loop search. But we are back to the original problem. panic error. I did check that pep.xml was the extension in the philosopher.yml file. I attach here a screen shot of the error report and also provide the yml and comet params files for you entertainment. 

![image](https://user-images.githubusercontent.com/16841846/76633686-1b002600-6513-11ea-94cd-33c5e7354aff.png)

[philosopherStuff.zip](https://github.com/Nesvilab/philosopher/files/4330228/philosopherStuff.zip)

**Comment by prvst** [comment]
hi @trishorts 

In your yaml file, in the PeptideProphet section, try changing this:

`extension: pep.XML`

to

`extension: pep.xml`

**Comment by trishorts** [comment]
![image](https://user-images.githubusercontent.com/16841846/76636369-ec844a00-6516-11ea-9bc6-5632c942d5e7.png)

![image](https://user-images.githubusercontent.com/16841846/76636409-fefe8380-6516-11ea-9549-4db490f0ca38.png)

**Comment by prvst** [comment]
Those search parameters you see above PeptideProphet are for MSFragger, if you are running Comet , those parameters will not be used and the search results will be named `pep.xml`.

**Comment by trishorts** [comment]
i changed it everywhere to be safe. i'm not using fragger (which you know). i don't know where else to change it.

**Comment by prvst** [comment]
from your image I see that you are still using `pep.XML` instead of `pep.xml` . Could you try using pep.xml in lowercase ?

**Comment by trishorts** [comment]
VICTORY
![image](https://user-images.githubusercontent.com/16841846/76638745-f6a84780-651a-11ea-9239-94b14ab3e9fd.png)

**Comment by prvst** [comment]
great !

**Comment by trishorts** [comment]
First. thank you so much for your responsiveness. It's commendable. Without your help, I would have be lost. I'm grateful.

But, you can see that philospher is too fragile to extension differences. There are ubiquitous in proteomics: .fasta .FASTA .fa .fas .mzml .mzML pep.xml pepXML. 

There should be a method to deal with this. And, given time I'm sure you will.

For now. Keep up the good work!

**Comment by anesvi** [comment]
Thanks trishort !

Felipe, let’s update our online tutorials now, while we it is still fresh.
We have been using MSFragger exclusively for so long that we need to refresh the Comet-specific parts.

Alexey

**Comment by prvst** [comment]
Thank you for your comments @trishorts.

I'm planning to work on this for the next update, my idea is to follow the behaviour you see on Linux systems where the extension doesn't actually matter and files are evaluated according to their content.

@anesvi 
Sarah uploaded the Comet tutorial to our wiki, we will review the extensions on the documentation as well.

**Comment by jspaezp** [comment]
Sorry for resurrecting this issue but it seems like it has not been "fixed".

My command fails with the `panic: runtime error: index out of range [0] with length 0 ` error when I am using comet unless I specifically change the `Peptideprophet: extension: pep.xml` parameter. 

Would it be possible for `philosopher` to set it to that when the database search is enabled and the search engine is comet, since it is know that it would output such "extension" (or philosopher could just rename it after calling comet...). 

(in an un-related issue, I noticed the .params file that is printed from `philosopher comet --print` is made for low-res data but peptideprophet assumes high res output, could the default comet .params in philosopher be modified to be high-res ??)

```diff
# Default params                                                #  High res params 
#                                                               #                                                            
# fragment ions                                                 # fragment ions                                              
#                                                               #                                                            
# ion trap ms/ms:  1.0005 tolerance, 0.4 offset (mono masses)   # ion trap ms/ms:  1.0005 tolerance, 0.4 offset (mono masses)                                                                
# high res ms/ms:    0.02 tolerance, 0.0 offset (mono masses)   # high res ms/ms:    0.02 tolerance, 0.0 offset (mono masses)                                                                
#                                                               #                                                                                                                            
fragment_bin_tol = 1.0005              # binning to use on fr | fragment_bin_tol = 0.02                # binning to use on fr                                                                
fragment_bin_offset = 0.4              # offset position to s | fragment_bin_offset = 0.0              # offset position to s                                                                
theoretical_fragment_ions = 1          # 0=use flanking peaks | theoretical_fragment_ions = 0          # 0=use flanking peaks                                                                
use_A_ions = 0                                                  use_A_ions = 0                                                                                                               
use_B_ions = 1                                                  use_B_ions = 1                                                                                                               
use_C_ions = 0                                                  use_C_ions = 0                                                                                                               

```

Thanks again for the attention.
Kindest wishes,
Sebastian
