### ISSUE TITLE
pipeline mode for TMT analysis

### ISSUE THREAD

**Issue by chliu1992** [Nesvilab/philosopher#115]
Hi,
I used three mzML files to take a test with the TMT pipeline following https://github.com/Nesvilab/philosopher/wiki/Pipeline-mode-for-TMT-analysis .
and  created a work folder that conains four subfolders as this tutorial said .After setting the .yml configuration file, I ran the pipeline command"philosopher pipeline --config philosopher.yml BAT_tmt" but it didn't work:

F:\MSFragger_test\BAT_TMT6_data_test>philosopher pipeline --config philosopher.yml BAT_tmt
'philosopher' is not recognized as an internal or external command,
operable program or batch file.

Is there anything wrong with my command or else?

**Comment by prvst** [comment]
did you downloaded Philosopher on that folder ?

**Comment by chliu1992** [comment]
Yeah, I put the philosopher.exe and MSFragger-2.3.jar into the bin folder.

**Comment by prvst** [comment]
so what is the path to the program ?

**Comment by chliu1992** [comment]
Could you please describe more detaily? the program means ?

**Comment by hayse1** [comment]
Make sure the `philosopher.exe` program is inside of the `bin` folder, then instead of 

`philosopher pipeline --config philosopher.yml BAT_tmt`, use 

`F:\MSFragger_test\BAT_TMT6_data_test\bin\philosopher.exe pipeline --config philosopher.yml BAT_tmt`

, which has the full path to the philosopher.exe program

**Comment by chliu1992** [comment]
@hayse1 Hi, I checked the bin folder and then ran the new command ,it didn't work either.

F:\MSFragger_test\BAT_TMT6_data_test>F:\MSFragger_test\BAT_TMT6_data_test\bin\philosopher.exe pipeline --config philosopher.yml BAT_tmt
time="2020-03-12T23:17:53+08:00" level=warning msg="The current Workspace is corrupted or was created with an older vers
ion. Please remove it and create a new one"
INFO[23:17:53] Executing Pipeline  v2.1.2
FATA[23:17:53] Cannot read file. open F:\MSFragger_test\BAT_TMT6_data_test\philosopher.yml: The system cannot find the file specified.

**Comment by chliu1992** [comment]
I updated the command and this time it stoped at the database.

F:\MSFragger_test\BAT_TMT6_data_test2>
F:\MSFragger_test\BAT_TMT6_data_test2>F:\MSFragger_test\BAT_TMT6_data_test2\bin\philosopher.exe pipeline --config F:\MSF
ragger_test\BAT_TMT6_data_test2\params\philosopher.yml BAT_tmt
time="2020-03-12T23:43:12+08:00" level=warning msg="The current Workspace is corrupted or was created with an older vers
ion. Please remove it and create a new one"
INFO[23:43:12] Executing Pipeline  v2.1.2
INFO[23:43:12] Initiating the workspace on BAT_tmt
WARN[23:43:13] There is a new version of Philosopher available for download: https://philosopher/releases
INFO[23:43:13] Creating workspace
INFO[23:43:13] Processing database
ERRO[23:43:13] Cannot read file. Cannot open the database file
INFO[23:43:13] Running the Database Search on all data
Error: Unable to access jarfile F:\MSFragger_test\BAT_TMT6_data_test2\BAT_TMT6_data_test2\bin\MSFragger-2.3.jar
INFO[23:43:13] Running the validation and inference on BAT_tmt
INFO[23:43:13] Executing PeptideProphet on BAT_tmt
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/ext/peptideprophet.interactParser(0xc0001d7b00, 0x58, 0xc0001d7b60, 0x57, 0xc0001d7bc0, 0x5e, 0xc0001d7b
00, 0x58, 0xc0001d7b60, 0x57, ...)
        /workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:218 +0x2241
philosopher/lib/ext/peptideprophet.PeptideProphet.Execute(0xc0001d7b00, 0x58, 0xc0001d7b60, 0x57, 0xc0001d7bc0, 0x5e, 0x
c0001d7b00, 0x58, 0xc0001d7b60, 0x57, ...)
        /workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:125 +0x1c2
philosopher/lib/ext/peptideprophet.Run(0xc00001b650, 0x24, 0xc00001b680, 0x2d, 0xc00032c960, 0x45, 0xc00033a3c0, 0x3c, 0
xc00033a400, 0x33, ...)
        /workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:70 +0x4d7
philosopher/lib/pip.Prophets(0xc00001a960, 0x24, 0xc00001a990, 0x2d, 0xc000023e50, 0x45, 0xc00001dc00, 0x3c, 0xc00001dc4
0, 0x33, ...)
        /workspace/philosopher/lib/pip/pip.go:232 +0xa74
philosopher/cmd.glob..func13(0x86fbb00, 0xc0001199b0, 0x1, 0x3)
        /workspace/philosopher/cmd/pipeline.go:77 +0x530
github.com/spf13/cobra.(*Command).execute(0x86fbb00, 0xc000119950, 0x3, 0x3, 0x86fbb00, 0xc000119950)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x86fc580, 0x0, 0x0, 0x0)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
        /workspace/philosopher/cmd/root.go:34 +0x34
main.main()
        /workspace/philosopher/main.go:22 +0x75

**Comment by hayse1** [comment]
It looks like you do not have the `philosopher.yml` file in the correct location. Please have another look at the tutorial and make sure to set the file paths for **your** configuration specifically (e.g. `F:\MSFragger_test\BAT_TMT6_data_test\bin\philosopher.exe` instead of `bin/philosopher`).

**Comment by chliu1992** [comment]
I check the tutorial and make sure the full path of files, the pipeline works successfully.
Thank you~~
