### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/philosopher#116]
I am getting the following error and it looks abnormal for me. What could be causing this type of error? 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at edu.umich.andykong.msfragger.D.a(Unknown Source)
	at edu.umich.andykong.msfragger.F.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
time="16:02:06" level=info msg="Running the validation and inference on LTBI_metaproteomic"
time="16:02:06" level=info msg="Executing PeptideProphet on LTBI_metaproteomic"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/ext/peptideprophet.interactParser(0xc0386201c0, 0x38, 0xc038620240, 0x37, 0xc038620280, 0x3e, 0xc0386202c0, 0x3c, 0xc038620300, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:218 +0x224d
philosopher/lib/ext/peptideprophet.PeptideProphet.Execute(0xc0386201c0, 0x38, 0xc038620240, 0x37, 0xc038620280, 0x3e, 0xc0386202c0, 0x3c, 0xc038620300, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:125 +0x1bd
philosopher/lib/ext/peptideprophet.Run(0xc000308090, 0x24, 0xc000032140, 0x46, 0xc0003080c0, 0x29, 0xc0001141e0, 0x55, 0xc000032190, 0x4c, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:70 +0x4d0
philosopher/lib/pip.Prophets(0xc0818381b0, 0x24, 0xc038620140, 0x33, 0xc0818381e0, 0x29, 0xc03805e000, 0x42, 0xc038620180, 0x39, ...)
	/workspace/philosopher/lib/pip/pip.go:255 +0xa6c
philosopher/cmd.glob..func13(0x86cd460, 0xc0001328a0, 0x4, 0x6)
	/workspace/philosopher/cmd/pipeline.go:77 +0x528
github.com/spf13/cobra.(*Command).execute(0x86cd460, 0xc0001327e0, 0x6, 0x6, 0x86cd460, 0xc0001327e0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x86cdee0, 0x0, 0x0, 0x0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:34 +0x2d
main.main()
	/workspace/philosopher/main.go:22 +0x6e
time="16:02:08" level=info msg="Executing Workspace  v3.2.3"
time="16:02:10" level=info msg="Removing workspace"
time="16:02:10" level=info msg=Done

**Comment by fcyu** [comment]
Hi @javanOkendo,

This error was due the the leak of enough memory. How much memory does your computer have? 

Best,

Fengchao

**Comment by javanOkendo** [comment]
Hi @fcyu I am running this analysis on the server. I did run the same type of data several times and now it is giving the following error which looks weared. I have 191 raw files in mzML format and I am using the philosopher pipeline with MSfragger as the search engine
In total 83412012 peptides.
Too many peptides were generated 2511982023! Cannot continue. The limit is approximately 2 billion peptides. 
If running using FragPipe: in MSFragger tab, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, grad
ually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7
-50 to e.g. 7-35). 
For users running the stand-alone version of MSFragger (i.e. not through FragPipe): please contact the developers for the stand-alone version of MSFragger with “Split database” option enabled.
time="11:59:54" level=info msg="Running the validation and inference on LTBI_metaproteomic"
time="11:59:54" level=info msg="Executing PeptideProphet on LTBI_metaproteomic"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/ext/peptideprophet.interactParser(0xc0033dc780, 0x38, 0xc0033dc7c0, 0x37, 0xc0033dc840, 0x3e, 0xc0033dc8c0, 0x3c, 0xc0033dc900, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:218 +0x224d
philosopher/lib/ext/peptideprophet.PeptideProphet.Execute(0xc0033dc780, 0x38, 0xc0033dc7c0, 0x37, 0xc0033dc840, 0x3e, 0xc0033dc8c0, 0x3c, 0xc0033dc900, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:125 +0x1bd
philosopher/lib/ext/peptideprophet.Run(0xc000128d80, 0x24, 0xc0034765f0, 0x46, 0xc000128de0, 0x29, 0xc00e73c060, 0x55, 0xc003476690, 0x4c, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:70 +0x4d0
philosopher/lib/pip.Prophets(0xc000128180, 0x24, 0xc0033dc140, 0x33, 0xc0001282a0, 0x29, 0xc003476000, 0x42, 0xc0033dc1c0, 0x39, ...)
	/workspace/philosopher/lib/pip/pip.go:255 +0xa6c
philosopher/cmd.glob..func13(0x86cd460, 0xc000134120, 0x4, 0x6)
	/workspace/philosopher/cmd/pipeline.go:77 +0x528
github.com/spf13/cobra.(*Command).execute(0x86cd460, 0xc000134060, 0x6, 0x6, 0x86cd460, 0xc000134060)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x86cdee0, 0x0, 0x0, 0x0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:34 +0x2d
main.main()
	/workspace/philosopher/main.go:22 +0x6e
time="11:59:56" level=info msg="Executing Workspace  v3.2.3"
time="11:59:57" level=info msg="Removing workspace"
time="11:59:57" level=info msg=Done

**Comment by fcyu** [comment]
Looks like your total peptide number is larger than Java's hard limit (~2 billion). If you are using FragPipe, you can increase the split database number to avoid this hard limit.

Best,

Fengchao

**Comment by javanOkendo** [comment]
I only can do this run on the server because the data I have is too big. The error is suggesting "please contact the developers for the stand-alone version of MSFragger with “Split database” option enabled."

Do you have a stand-alone version of the MSfragger with the "split database" enabled? If yes can you share it @fcyu ?
