### ISSUE TITLE
Missing source code in `v3.2.3.tar.gz`

### ISSUE THREAD

**Issue by cpanse** [Nesvilab/philosopher#118]
Hi,

I can not find the source code in the tar archive using that link https://github.com/Nesvilab/philosopher/archive/v3.2.3.tar.gz

```
tobiasko@fgcz-r-033:/tmp$ tar tfz v3.2.3.tar.gz
philosopher-3.2.3/
philosopher-3.2.3/.gitignore
philosopher-3.2.3/CNAME
philosopher-3.2.3/License
philosopher-3.2.3/README.md
philosopher-3.2.3/_config.yml
philosopher-3.2.3/images/
philosopher-3.2.3/images/philosopher.png
tobiasko@fgcz-r-033:/tmp$ md5sum v3.2.3.tar.gz
b36a411574981b94607e10afb377e54c  v3.2.3.tar.gz
tobiasko@fgcz-r-033:/tmp$
```

```
tobiasko@fgcz-r-033:/tmp$ head -c 128 `which philosopher`                                                                                                            
ELF><F@@8@@@@@@
```

Best wishes,

Christian

**Comment by prvst** [comment]
The source code is ready to be shared but currently unavailable. Our publication is under review right now and once its out, the whole project will be accessible. The zip files are placed there because they are automatically generated by Github.

**Comment by cpanse** [comment]
I would be happy to review the code. ;-)
C

**Comment by prvst** [comment]
I would love to have your feedback for sure. I'll send you a message once we have it open to the public.
