### ISSUE TITLE
Create a report with each sample intensity

### ISSUE THREAD

**Issue by pabad1** [Nesvilab/philosopher#119]
Dear developers, 

I'm a begginer in Philosopher and I`m performing a label-free anylisis while dealing with some issues.
 
I want to compare two groups of 5 samples each. To do that, I've created a combined pep.xml with PeptideProphet, a combined prot.xml with ProteinProphet, and applied filter and freequant in each group separately. Then, I've run abacus creating a combined prot.xml from the two combined pep.xml. After doing that, I've obtained a proper report with the combined intensities of each group. 

I was wondering if it's possible to create a report with the intensities of each sample in addition to those combined. I'm dealing with it for some days.  In my analysis I need to know if the protein is present in all samples of the group or only in some of them, or if one sample has a lower intensity, for example. With my current report I can't have this information. Is there any way to do that?

Thank you very much in advance. And congratulations on creating such a great tool. 

Paloma

**Comment by prvst** [comment]
hi Paloma, thanks for the kind words.
Philosopher considers each folder with one or more mzML files a data set, all files inside that folder will be grouped and quantified together. If you wish to process each one of the mzML files individually, then you need to separate them in different mzML folders. If the number of files / folders are to many for running the commands manually, you can try using the [pipeline command](https://github.com/Nesvilab/philosopher/wiki/Pipeline-mode-for-TMT-analysis) which automates the analysis for you.

**Comment by pabad1** [comment]
Thank you for your recomendations, Felipe! I will use the pipeline to do it faster.
