### ISSUE TITLE
Error when using iTRAQ labelling

### ISSUE THREAD

**Issue by o-t** [Nesvilab/philosopher#121]
Hello,

I followed the step-by-step TMT analysis, substituting TMT labels with iTRAQ. Everything worked fine until the label-based quantification step, when I got this error message: 'Unknown multiplex setting, please define the plex number used in your experiment'. Although it did give me a protein report in the end, I am not sure if this error would affect the result.

This is my annotation.txt:
114 N15.1
115 T16.2
116 N15.2
117 T16.2

And my command for that step:
philosopher labelquant --plex 4 --brand itraq --dir ./NCC_N15T16/

Any help appreciated. Thanks!

**Comment by prvst** [comment]
Can you run the command `philosopher version` and paste the result here ?

**Comment by o-t** [comment]
Current Philosopher build and version         build=1583959175 version=v3.2.3

**Comment by o-t** [comment]
I ran with another input file and still got the error. I believe v3.2.3 is the latest version, correct?

**Comment by prvst** [comment]
Yes, that's the latest version. I'll investigate that for you.

**Comment by prvst** [comment]
@o-t 
That is indeed a bug. I fixed and added to the next release that I'm planning to do this week. Thanks for reporting,

**Comment by prvst** [comment]
Fixed. Added to source v3.2.4

**Comment by o-t** [comment]
Thank you so much. Is v3.2.4 in the release page? I couldn't find it there
