### ISSUE TITLE
pipeline --config *.yaml vs. fragger.params

### ISSUE THREAD

**Issue by tobiasko** [Nesvilab/philosopher#128]
Hello philosopher developers,

as simple question: When running `philosopher pipeline --config *.yaml` you can def. a `fragger.params` in the `*.yaml` file. But the individual MSFragger parameters are also present in the `*.yaml`. What is the idea here? Which parameters are actually used by MSFragger?

Best,
Tobi

**Comment by prvst** [comment]
The parameter file has priority over the yaml or the CLI parameters.

**Comment by tobiasko** [comment]
Ok. THX!
