### ISSUE TITLE
multiple variable mods on residue in philosopher report

### ISSUE THREAD

**Issue by merbllab** [Nesvilab/philosopher#129]
**Describe the bug**
I am not sure if this is a bug or just not supported yet. when applying in the MSFragger multiple variable modification on the same amino acid (allow_multiple_variable_mods_on_residue: 1) the philosopher report doesn't list the combined modification detected in the assign modification column.

**Please complete the following information:**
 - OS:  Linux
 - Version: latest 3.2.3

**Comment by prvst** [comment]
Could you share your PSM table with me?

**Comment by prvst** [comment]
I received your email.
Your observation is correct; right now, we do not report combined masses like that. Philosopher cross-checks the modification masses to Unimod, so if you have a combination of modifications, it will not show in that column.

**Comment by assafkacen** [comment]
Thanks, maybe it is better for the pipeline users to avoid using this MSFragger option for now.

נשלח מה-iPhone שלי

‫ב-29 באפר׳ 2020, בשעה 20:20, ‏‏Felipe Leprevost ‏<notifications@github.com> כתב/ה:‬

﻿

I received your email.
Your observation is correct; right now, we do not report combined masses like that. Philosopher cross-checks the modification masses to Unimod, so if you have a combination of modifications, it will not show in that column.

**Comment by prvst** [comment]
I disagree. There are right now many use cases for MSFragger, not all of them necessarily deals with combined modifications on the same amino acid. And, as you pointed that out, you can still find those peptides via modified peptide string.
