### ISSUE TITLE
LFQ for each modified peptide from open search?

### ISSUE THREAD

**Issue by jgmeyerucsd** [Nesvilab/philosopher#130]
***question/request**
Is there currently a way to get separate precursor LFQ values for each of the modified peptide forms detected in open search? I am able to get the combined_peptides.tsv with intensity values, and there is a column "assigned modifications" that only lists the variable modifications set during my search, not any of the mass shifts discovered by open search. 

** desired solution ***
The solution I would like is to get the peak areas for each of the modified peptides that were detected. 

**Describe alternatives you've considered**
Usually I do quantification in skyline but that requires known modifications and not the mass shifts found by open search. 

**Additional context**
This would enable looking for unknown modifications that change across biological treatments.

**Comment by jgmeyerucsd** [comment]
@prvst I don't get a combined PSM or ion report with all the quant in the same format as the combined_peptide.tsv - am I doing something wrong?

**Comment by prvst** [comment]
The only combined reports you will get are the peptide and protein. For the combined peptide table, we collapse the observations at the sequence level, grouping the modifications. You might want to look at the individual PSM tables that are present inside each data set folder.

**Comment by jgmeyerucsd** [comment]
Those tables don't appear to have quantitative values in them - am I missing them? Also, its not clear which of these peptides pass significance cutoffs

**Comment by jgmeyerucsd** [comment]
nvm I was looking in the wrong output folder - I found psm.tsv with an "intensity" column

**Comment by prvst** [comment]
Are the intensity columns empty?

**Comment by jgmeyerucsd** [comment]
It looks like this would work, but it is more difficult to read 15 files and do the matching myself. If its not too much work, adding the modified peptide quant table could be useful since a major advantage of MS-Fragger is discovering these mods and I don't know any other way to quantify them.

**Comment by prvst** [comment]
Do you think that a combined ion table would be useful for you?

**Comment by jgmeyerucsd** [comment]
@prvst How are the tables "ion.tsv" and "psm.tsv" different? It looks like ion has fewer entries by about 20k. 

I'm not sure which is more appropriate, but yes some type of table of modified peptide quants (including all the variants of each parent peptide) would be useful for me.

**Comment by prvst** [comment]
To create the ions list, we collapse all PSMs using the sequence, the calculated peptide mass (which includes the mass of the modifications), and the charge state.

**Comment by jgmeyerucsd** [comment]
Got it, thanks. Then yes a combined ion table with quantification across samples would be useful to me.

**Comment by prvst** [comment]
OK, I'll add this request to our backlog and discuss it with my colleagues on how to implement it.

**Comment by prvst** [comment]
I have added to the backlog, postponed for a future version.
