### ISSUE TITLE
Questions about the report of philosoper.

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/philosopher#141]
Something in the filter log of philosopher makes me confused.

The example is shown below.

"INFO[09:55:24] Converged to 1.00 % FDR with 27888 PSMs       decoy=281 threshold=0.4725 total=28169
INFO[09:55:24] Converged to 1.00 % FDR with 9077 Peptides    decoy=91 threshold=0.7717 total=9168
INFO[09:55:25] Converged to 1.00 % FDR with 12043 Ions       decoy=121 threshold=0.7269 total=12164
INFO[09:55:27] Protein inference results                     decoy=1609 target=4314
INFO[09:55:27] Converged to 1.00 % FDR with 2604 Proteins    decoy=26 threshold=0.9429 total=2630
INFO[09:55:28] Applying sequential FDR estimation            ions=12527 peptides=9493 psms=27506
INFO[09:55:29] Converged to 0.22 % FDR with 27444 PSMs       decoy=62 threshold=0.4725 total=27506
INFO[09:55:29] Converged to 0.29 % FDR with 9465 Peptides    decoy=28 threshold=0.4727 total=9493
INFO[09:55:29] Converged to 0.29 % FDR with 12490 Ions       decoy=37 threshold=0.4727 total=12527"

At 1% FDR with 12043 ions, threshold (the threshold I think is peptideprophet probability) is 0.7269.

However, at 0.29%FDR with 12490 ions, the threshold is 0.427.

To my knowledge, the more stringent FDR (from 1% to 0.29%) should be higher peptideprophet probobility. 

So my question are

1. Why the more stringent FDR means the lower peptideprobability.
2. Under default setting, the ion.tsv, psm.tsv, peptide.tsv or protein.tsv generated by philosoper is filtered at their corresponding 1% ion, peptide, protein FDR, or they are filtered at both corresponding level 1% FDR and 1% protein FDR.

**Comment by prvst** [comment]
1. The PeptideProphet result is broken down into three "layers"; PSMs, Peptides, and Ions. FDR filtering is applied to each layer individually. When using the sequential FDR filtering, like you are doing, the approved PSMs from the first pass, are filtered based on the FDR approved proteins. The product of this second filtering is regrouped into three new layers, which is then used to calculate a new FDR filtering.

2. Each layer is filtered at their own FDR threshold and [you can adjust the individual limits](https://github.com/Nesvilab/philosopher/wiki/Filter)
