### ISSUE TITLE
Building with "go build" fails because Asset is undefined

### ISSUE THREAD

**Issue by dnusinow** [Nesvilab/philosopher#142]
Thank you for providing this project! I'd love to build it myself if possible but I ran in to this bug with a simple "go build". Since there aren't build instructions that I can see it's likely that I'm missing an important step but I don't know what it might be. In case "go build" is the recommended way to build philosopher I'd appreciate any help here since I'm not that experienced with go yet.

**Describe the bug**
I cloned this repository and ran "go build" and got many messages related to the "Asset" function being undefined. I can't find a reference to it in the source code or in the go documentation.

**To Reproduce**
1. Start with Ubuntu and go version "go1.13.8 linux/amd64"
2. Clone this repository
3. Run "go build" inside it

**Expected behavior**
The build would complete without errors.

**Screenshots**

> <david@david-Virtual-Machine:~/src/philosopher> (61) % go build
> # philosopher/lib/dat
> lib/dat/dat.go:252:15: undefined: Asset
> # philosopher/lib/ext/cdhit/unix
> lib/ext/cdhit/unix/unix.go:15:13: undefined: Asset
> # philosopher/lib/ext/cdhit/win
> lib/ext/cdhit/win/win.go:15:13: undefined: Asset

and many more of the same error across the files that use Asset.

**Please complete the following information:**
 - OS: Ubuntu
 - Version: focal (20.04)

**Additional context**

**Comment by prvst** [comment]
@dnusinow I'm going to upload today the instructions on how to build.

**Comment by prvst** [comment]
Here it is. [How to Build](https://github.com/Nesvilab/philosopher/wiki/How-to-Build).

I'll close the ticket, but if you still have issues, please let me know.

**Comment by dnusinow** [comment]
Thank you! I was able to build it with the instructions.
