### ISSUE TITLE
Cannot open cluster file

### ISSUE THREAD

**Issue by clin888** [Nesvilab/philosopher#144]
with philosopher version 3.2.9. An error message is as following, I am not sure it is due to improperly configuration of our local clustering or any configuration I can set in philosopher_329.yml..
INFO[05:45:01] Filtering spectra for label quantification
INFO[05:45:01] Removing 0 PSMs from isobaric quantification
INFO[05:45:03] Calculating normalized protein levels
INFO[05:45:03] Saving
INFO[05:45:38] Executing report on NPM1_AML_Gr01
INFO[05:46:23] Creating reports
INFO[05:46:34] Executing cluster on NPM1_AML_Gr01
INFO[05:46:34] Clustering
INFO[05:46:34] Parsing clusters
FATA[05:46:34] Cannot open cluster file

Thanks

**Comment by prvst** [comment]
What kind of protein database are you using?

**Comment by prvst** [comment]
There was a bug in the code, and I just got it fixed. Thanks for reporting, it will be made available soon.

Added to source v4.0.0
