### ISSUE TITLE
Greater Flexibility in Temporary Directory Handling for Linux

### ISSUE THREAD

**Issue by atombaby** [Nesvilab/philosopher#145]
The [current logic for handling temporary files](https://github.com/Nesvilab/philosopher/blob/8f389e2fd53dafde5fdcb16d7c5703e0b8f7326a/lib/sys/sys.go#L41
) sets the temporary directory to `/tmp` for Linux platforms. 

It would be useful if Philosopher were to use the convention of detecting the `TMPDIR` environment variable then falling back to `/tmp` (should that be unset) as the temporary directory for its work. This is useful in our environment as /tmp is pretty small but we maintain larger temporary file systems for cluster jobs.

Thanks

**Comment by prvst** [comment]
This request is similar to #83. I added to the upcoming version the possibility to define a new directory to be used as a temporary folder. The latest version will be available soon.
