### ISSUE TITLE
Error message in cmd prompt

### ISSUE THREAD

**Issue by rameshrajn** [Nesvilab/philosopher#147]
![Error_Philosopher](https://user-images.githubusercontent.com/69099114/89115903-6a87c400-d4ab-11ea-8916-501dc4ab66f1.PNG)

The following error is seen when I try to prepare database using philosopher. 
How to proceed further.  For your info, my pc is brand new. So am I missing any prerequisite tools that are required to run philosopher in cmd prompt? 

Thanks

**Comment by hayse1** [comment]
Hi Ramesh, is `C:\FragPipe_Skyline\philosopher_windows_amd64.exe` the correct path to philosopher? Depending on the database you want to make, you may be able to construct it within FragPipe instead of the command line.

**Comment by prvst** [comment]
You probably forgot to put philosopher inside that folder.

**Comment by rameshrajn** [comment]
@hayse1  I was trying to run a hands-on from the protocol "Fast Proteome Identification and Quantification from Data-Dependent Acquisition–Tandem Mass Spectrometry (DDA MS/MS) Using Free Software Tools" by Jesse Meyer. I am at the step where the databases are prepared using philosopher using command line. I will try with Fragpipe instead. Thk u. 
 @prvst  I have checked once again. The exe file exists in the location. Have attached the image.
![err](https://user-images.githubusercontent.com/69099114/89127059-40b0ba80-d508-11ea-8ef6-1bed854c5bb8.PNG)

**Comment by prvst** [comment]
check the name of the program you have in the folder and the name of the program you are trying to run, they are different.

**Comment by rameshrajn** [comment]
@prvst  First time in command prompt. 
Thanks a lot
