### ISSUE TITLE
Example report for the tutorial

### ISSUE THREAD

**Issue by Niveda-S** [Nesvilab/philosopher#149]
I am trying to follow the step-by-step tutorial provided in the link https://github.com/Nesvilab/philosopher/wiki/Simple-Data-Analysis. Is there a corresponding report for the example data provided in the link, so that I can validate that the workflow I've followed (along with flags/parameters) is correct?

**Comment by prvst** [comment]
Hi @Niveda-S. We don't have an example of output for you to validate, but I'll be glad to take a look at yours if you want.
