### ISSUE TITLE
Database command on full swissprot fails with `index out of range`-error

### ISSUE THREAD

**Issue by rababerladuseladim** [Nesvilab/philosopher#151]
**Describe the bug**
Processing the entire swissprot database with philosopher fails with the error message: `panic: runtime error: index out of range [1] with length 0`

**To Reproduce**
1. Download [swissprot fasta](ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz)
2. unpack
3. Run `philosopher workspace --init`
4. Run `philosopher database --custom uniprot_sprot.fasta --contam`

**Expected behavior**
Creation of a concatenated target-decoy fasta with contaminants.

**Please complete the following information:**
 - OS: Ubuntu Linux
 - Version: 18.04.5

<details>
  <summary>Log</summary>

philosopher database --custom uniprot_sprot.fasta --contam
INFO[13:24:02] Executing Database  v3.2.9
INFO[13:24:02] Processing decoys
INFO[13:24:23] Creating file
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
philosopher/lib/dat.ProcessUniProtKB(0xc01593ced1, 0x2e, 0xc01528fe00, 0x1fd, 0xbf294c, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /workspace/philosopher/lib/dat/db.go:251 +0xc42
philosopher/lib/dat.(*Base).ProcessDB(0xc00010c690, 0xc033f29f20, 0x56, 0xbf294c, 0x4)
        /workspace/philosopher/lib/dat/dat.go:119 +0x82d
philosopher/lib/dat.Run(0xc000130510, 0x24, 0xc000130540, 0x24, 0xc000130570, 0x29, 0xc0001001c0, 0x33, 0xc0001305a0
, 0x2a, ...)
        /workspace/philosopher/lib/dat/dat.go:94 +0x430
philosopher/cmd.glob..func4(0x86dbda0, 0xc00018bef0, 0x0, 0x3)
        /workspace/philosopher/cmd/database.go:23 +0xc1
github.com/spf13/cobra.(*Command).execute(0x86dbda0, 0xc00018be90, 0x3, 0x3, 0x86dbda0, 0xc00018be90)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x86ddfc0, 0x0, 0x0, 0x0)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
        /workspace/philosopher/cmd/root.go:35 +0x2d
main.main()
        /workspace/philosopher/main.go:22 +0x6e
</details>

**Comment by prvst** [comment]
Hi @rababerladuseladim 

The entire UniProt Swissprot database contains more than half-million protein entries from possibly hundreds of different organisms. The overlap between the proteins and the complexity of the shared peptides will be so high that it could make your data interpretation pretty much impossible for some cases. Could you tell me a little bit more about your experiment?

**Comment by rababerladuseladim** [comment]
Hey @prvst 
Sure I can: 
We are doing metaproteomics experiments and have a sample at hand with absolutely no knowledge about the origin. Hence, we want to search it against swissprot as a first measure to get a very rough idea what kind of sample it might be.

**Comment by prvst** [comment]
That is pretty interesting for sure. I suggest that you try using the [UniRef](https://www.uniprot.org/help/uniref) database, instead of the entire UniProt. It could be a good starting point. Have in mind that pinpointing an organism species or even genus will be extremely difficult at the peptide level.

**Comment by rababerladuseladim** [comment]
Thanks for the hint, it works with the uniref database based on reviewed seqs. Do you think that the error is due to the high level of redundancy of the swissprot fasta? If so, would it be possible to include an error message that points in that direction?

**Comment by prvst** [comment]
I can't say for sure without debugging, but it seems that the parser broke trying to read one or more sequences.
