### ISSUE TITLE
Cannot decoy large database using philosopher cmd prompt

### ISSUE THREAD

**Issue by antdit** [Nesvilab/philosopher#158]
I am trying to add decoys and contaminants to a large database (~70G on disk) using philosopher v3.3.11. The process initiates but never finishes and does not throw any errors. Is there a size limit on custom databases? The database is formatted like this:  

>GUT_GENOME180114_01696 hypothetical protein  
PROTEINSEQUENCE1
>GUT_GENOME079393_00785 hypothetical protein  
PROTEINSEQUENCE2
...

I am running on Windows Server 2012, 128G RAM with the following commands:
philosopher workspace --init
philosopher database --custom db.fasta --contam

Thanks

Antje

**Comment by prvst** [comment]
@antdit Although you can use Philosopher for really (really) large-scale analysis, the program wasn't designed having in mind use cases like yours. The database command takes the information from the FASTA entries, annotates them for future use, and creates the decoy entries. All of this is done in memory, while the database annotation is saved on disk. So a 70GB database would end-up consuming approximately 140GB with the decoys. That's more than what you have in your system.
