### ISSUE TITLE
Labelquant function in philospher

### ISSUE THREAD

**Issue by surPoudel** [Nesvilab/philosopher#159]
Hi,

I am trying to use philosopher in order to perform quantification. I first performed MSFragger and got to the point where I generated interact.prot.xml.

Now when I run the following code:
$philosopherPath labelquant --brand tmt --plex 11 --dir $dataDirPath

I am getting following error
INFO[17:25:04] Executing Workspace  v3.3.11
INFO[17:25:05] Removing workspace
INFO[17:25:05] Done
 /home/spoudel1/PengProteomics/PTM_study/philosopher workspace --init
INFO[17:25:05] Executing Workspace  v3.3.11
INFO[17:25:05] Creating workspace
INFO[17:25:05] Done
 /home/spoudel1/PengProteomics/PTM_study/philosopher labelquant --brand tmt --plex 11 --dir /research/projects/penggrp/psychENCODE/penggrp/software_dev/PTM_study/AD_Serum/Test
INFO[17:25:05] Executing Isobaric-label quantification  v3.3.11
FATA[17:25:05] Cannot read file:open .meta/ev.param.bin: no such file or directory

I am not sure how to fix this issue. 
Another question, does philosopher handle TMT pro data (TMT16)?

Thank you for the help.

Sincerely,
Suresh

**Comment by surPoudel** [comment]
My annotation.txt looks like this:
126 S1
127N S2
127C S3
128N S4
128C S5
129N S6
129C S7
130N S8
130C S9
131N S10
131C S11

**Comment by prvst** [comment]
Hi @surPoudel. The commands need to be executed in a specific order. They also need to be executed inside the workspace; as you progress with your analysis, data will be kept in the workspace saved in a special format that Philosopher can read. The error above indicates that some of these data are missing, more specifically from the FDR filtering (the filter command). I suggest that you take a look [here](https://github.com/Nesvilab/philosopher/wiki/Philosopher-Basics) to see what is the expected flow of information and then try again.

**Comment by surPoudel** [comment]
Thank you very much. It worked now.

Sincerely,
Suresh
