### ISSUE TITLE
yaml parsing error when specifying mass_offsets in philosopher.yaml

### ISSUE THREAD

**Issue by asalt** [Nesvilab/philosopher#160]
**Describe the bug**
If you try to specify mass_offsets in philosopher.yaml:

![Screenshot from 2020-10-18 19-44-34](https://user-images.githubusercontent.com/11843940/96390505-a103df80-117a-11eb-879a-449f57715688.png)

You get an error, presumably as the value is expected to be integer only
![Screenshot from 2020-10-18 19-44-12](https://user-images.githubusercontent.com/11843940/96390522-b0832880-117a-11eb-8567-3d9d92a3f5b4.png)

Note if mass_offsets is set in fragger.params, and fragger.params is given to philosopher.yaml, everything works! 

**Please complete the following information:**
 - OS: Linux Ubuntu

**Comment by prvst** [comment]
Fixed. Added to v3.5.14
