### ISSUE TITLE
Spectral counting on iprophet results

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/philosopher#163]
Dear Felipe,

I am not sure whether this is an intended behavior or not but I realized today that Philosopher does not apply spectral counting when the input to the filter step was refined by iprophet. The corresponding columns in the proteins.tsv contain only zero, while the same columns have values when using the interact.pep.xml file used as input to iprophet.
I understand that in many cases there is no reason to calculate aggregated spectral counts from multiple experiments, however, we use iprophet to merge results from one gel lane at a time as we think this improves the quality compared to peptide prophet alone. Would it be possible to calculate spectral counts on this data as well?

Best,
Juergen

**Comment by prvst** [comment]
Hi @JB91451, Could you elaborate a little more on what you are doing? Are you running the filter command using the Prophet output?

**Comment by JB91451** [comment]
Hi Filipe,

yes I run the filter command on the output of iprophet (from a search with spectraST, but the same happens when using MSFragger):

\philosopher_3311\philosopher.exe iprophet --decoy DECOY_ --threads 3 interact.pep.xml

\philosopher_3311\philosopher.exe proteinprophet --iprophet --maxppmdiff 20 --output combined interact.iproph.pep.xml

\philosopher_3311\philosopher.exe filter --pep 0.01 --pepxml interact.iproph.pep.xml --prot 0.01 --protxml combined.prot.xml --2d --tag DECOY_

\philosopher_3311\philosopher.exe report --decoys

**Comment by prvst** [comment]
So you are running iProphet on a single internact.pep.xml?

**Comment by JB91451** [comment]
Yes, this might be a bit redundant, but is a remaining from an old Sequest-sorcerer workflow which did that always.

**Comment by anesvi** [comment]
I would add –nonsp to iprophet command.
For some reason, in recent years ISB folks added NSP (number of sibling peptides) to iProphet as well. So it is applied at both iProphet and ProteinProphet level. So I unusually turn it off via “No NSP” flag.
But that should not be an issue, just as a side note
Alexey
