### ISSUE TITLE
Spectral clustering prior to database search

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/philosopher#164]
Could you guys consider adding the spectral clustering functionality within the philosopher pipeline? Spectral clustering is known to remove the redundant spectra and by doing this it reduces the database search time significantly. It also improves the overall quality of the spectra. With spectral indexing approach used in MSfragger, I hope this can further shorten the MSfragger search time. What do you guys think of this suggestion?

**Comment by anesvi** [comment]
Thank you for your feedback, Javan. There are several strategies we are considering that could further speed things up for certain searches, some may be related to what you proposing.
Best,
Alexey

**Comment by javanOkendo** [comment]
@anesvi I have thought about it and I hope you will consider it. It will really improve the search speed for the MSfragger

**Comment by anesvi** [comment]
Perhaps you can provide us with more info on the types of searches you are doing. MSFragger itself is very fast. The downstream steps often take more time. You can also turn off parameter optimization, and also mass calibration, if that is a slow step for you.
Best
Alexey

**Comment by javanOkendo** [comment]
I was doing some spectral clustering analysis on a certain disease condition. I was then to compare the search results of clustered and unclustered spectra. I still do not know if clustering this data will improve the ID rate but I will use MSfragger to assess the ID rates of clustered and unclustered spectra.
