### ISSUE TITLE
ProteinProphet: 'std::runtime_error' -what():  locale::facet::_S_create_c_locale name not valid time="15:20:59" level=fatal msg="Cannot execute program. There was an error with ProteinProphet, please check your parameters and input files"

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/philosopher#165]
Dear Developers

**Describe the bug**
I reproducibly get an error with ProteinProphet using FragPipeGUI 14. I tried already different databases (human, mouse) (always with splittingDB option) before I would like to run my huge metaProteomics database.
Human and mouse were downloaded and annotated by philosopher as described in the tutorial. I am aware that using these DBs I will mostly identify contaminant proteins in these samples.. Nevertheless I should not run into an error.

ProteinProphet [Work dir: /scratch/j_p3635_wFragPipe/outputFresh]
/scratch/FragPipe14/philosopher proteinprophet --maxppmdiff 2000000 --output combined /scratch/j_p3635_wFragPipe/outputFresh/j_p3635_wFragPipe/interact.pep.xml
time="15:20:58" level=info msg="Executing ProteinProphet  v3.3.11"
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
time="15:20:59" level=fatal msg="Cannot execute program. There was an error with ProteinProphet, please check your parameters and input files"
Process 'ProteinProphet' finished, exit code: 1
Process returned non-zero exit code, stoppingProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64))
PhilosopherDbAnnotate [Work dir: /scratch/j_p3635_wFragPipe/outputFresh/j_p3635_wFragPipe]
/scratch/FragPipe14/philosopher database --annotate /scratch/j_p3635_wFragPipe/2020-10-26-decoys-reviewed-contam-UP000000589.fas --prefix rev_

**To Reproduce**
It is the default LFQ-MBR workflow. I can share all you need.

**Expected behavior**
not throwing the error of ProteinProphet.

**Please complete the following information:**
 - OS: Linux 
 - Version: 
Philosopher version: 3.3.11 (build 1601497354)

**Additional context**
This should only be the testrun before I want to excecute the workflow completely from commandline and then switching to the huge MetaproteomicsDB.

**Comment by prvst** [comment]
Hi @jjGG, this problem seems to be related to your system locale settings. I saw it happen before with systems that were not initially set to use English as their main language. Could you type and paste here the output of the following commands?

`neofetch`
and
`locale`

**Comment by jjGG** [comment]
Hello @prvst .. here the stdout.

jonas@fgcz-r-033:/scratch/j_p3635_wFragPipe/outputFresh/j_p3635_wFragPipe$ neofetch
-bash: neofetch: command not found
jonas@fgcz-r-033:/scratch/j_p3635_wFragPipe/outputFresh/j_p3635_wFragPipe$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

best regards - jonas

**Comment by prvst** [comment]
Run the following command, then open a new terminal and run Philosopher one more time.

`export LC_ALL=en_US.UTF-8`

If it works, you can add the command to your .bash_rc file.

**Comment by jjGG** [comment]
Dear @prvst, I added the file to .bashrc but after logging in with another terminal it still would show the error. 
But if I do the export before starting the fragPipeGUI it works like a charm now. 

Thanks for the super response time. 

Best regards and with this I close the issue 
- jonas

**Comment by soymintc** [comment]
Just for the record, I had a similar error, and `export LC_ALL=en_US.UTF-8` didn't work.
From https://github.com/EOSIO/eos/issues/5586, I tried `export LC_ALL="C"`, and `philosopher proteinprophet` worked like a charm 😁
