### ISSUE TITLE
Report without ProteinProphet

### ISSUE THREAD

**Issue by nirkoty** [Nesvilab/philosopher#168]
Hi,

I am running running philosopher (3.3.11) with MSFragger and I am interested in peptides specifically, not proteins. I use a large custom database and I have a high number of runs to work on, therefore ProphetProphet is taking a very long time. I would like to skip it in order to only have the peptide.tsv and psm.tsv files (not interested in protein.tsv).
Therefore I run PeptideProphet, followed by filter but then I get an error saying "./meta/prot.bin not found" which I assume means it's looking for the ProteinProphet output.

For filter, I use the following flags --sequential --razor --tag DECOY_ --pepxml combined.pep.xml

Would it be possible to use filter and report without having to run ProteinProphet?

Thanks

**Comment by prvst** [comment]
Hi @nirkoty 
As you correctly pointed, if you are using a huge database, like a metaproteomics one, the standard protein inference approach might be feasible. 

If you want to go ahead with your analysis without the protein inference, try removing the `--sequential` and `--razor` tags from your command. Those flags trigger different functions that affect how the PSMs are processed and filtered together with the protein inference data; that is why you see the error message.

As an alternative to ProteinProphet, I added to Philosopher a custom algorithm that can apply a protein correction to the PSM list. The process is much faster, and it applies a logic very similar to the razor approach based on a ProteinProphet output. For that, you need to remove the `--razor` add the `--inference` tag to your command.

**Comment by nirkoty** [comment]
Hi Felipe,

Many thanks for the quick reply, it worked indeed!
