### ISSUE TITLE
Intensity values for proteins.tsv only show 0s

### ISSUE THREAD

**Issue by Niveda-S** [Nesvilab/philosopher#169]
Hi,
I am trying to run philosopher on iprophet results and I see that the report generated for proteins (proteins.tsv) contains 0s for the intensity columns:
![image](https://user-images.githubusercontent.com/17713621/99827875-0e56b780-2b0f-11eb-9778-adad151d47c6.png)

The report for peptides (peptide.tsv) shows intensity values:
![image](https://user-images.githubusercontent.com/17713621/99828485-d8fe9980-2b0f-11eb-9add-5315f3f9c503.png)

Here are the steps I run:
1) InterProphetParser
InterProphetParser DECOY=DECOY 4771.kscore.interact.pep.xml 4771.iprophet.pep.xml

2) ProteinProphet
ProteinProphet 4771.iprophet.pep.xml 4771.proteinprophet.prot.xml IPROPHET

3) Philosoper

- Initialize workspace
philosopher workspace --init

- Database
philosopher database --annotate "$fasta"

- filter based on FDR
philosopher filter --razor --pepxml "4771.iprophet.pep.xml" --protxml "4771.proteinprophet.prot.xml"

- quantification
philosopher freequant --dir "$output"

- create ion, peptide and protein reports
philosopher report

I tried using the "NONSP" flag for iprophet and proteinprophet but that didn't help with the 0s issue. Is there something else I should be doing?

**Comment by prvst** [comment]
Hi @Niveda-S . 
You are first running the TPP Prophets, and then after that, you run Philosopher? Also, could you give me a brief description of your experiment and the type of data you have?

**Comment by Niveda-S** [comment]
Hi Felipe,

Yes, I am using the TPP iprophet and protein prophet files and use that to run philosopher
The input files I am using are Thermo DDA files that have been converted to mzML from raw format using thermo ms convert

I am also attaching the philosopher logs if that would be useful:
[philosopher.log](https://github.com/Nesvilab/philosopher/files/5575381/philosopher.log)

**Comment by prvst** [comment]
Can you share your interact files with me?

**Comment by Niveda-S** [comment]
Please see attached files from the steps: 1) Peptide prophet 2) Interprophet parser 3) ProteinProphet 4) Philosopher

[Sample-Inputs.zip](https://github.com/Nesvilab/philosopher/files/5575729/Sample-Inputs.zip)

**Comment by prvst** [comment]
@Niveda-S , I suggest that you try repeating your workflow, but this time, instead of running interact, run the Prophets shipped together with Philosopher. You don't need to have TPP installed on your computer to do so.

Instead of running:

```
Command : xinteract -OARPwd -dDECOY_  -N/hpc/home/sharman/iphronesis_dev/platform_workspace/jobs/SJOB4771/peptideprophet/4771.kscore.interact.pep.xml /hpc/home/sharman/iphronesis_dev/platform_workspace/jobs/SJOB4771/tandem/20181011AMcA_Ather_Crude_2_centroid.kscore.tandem.pep.xml /hpc/home/sharman/iphronesis_dev/platform_workspace/jobs/SJOB4771/tandem/20181011AMcA_Ather_Crude_3_centroid.kscore.tandem.pep.xml /hpc/home/sharman/iphronesis_dev/platform_workspace/jobs/SJOB4771/tandem/20181011AMcA_Ather_Crude_1_centroid.kscore.tandem.pep.xml
```

You can run:

`philosopher peptideprophet --database <file.fasta> --accmass --nonparam --decoy DECOY_ --decoyprobs <pep.xml files>`

Please check our [documentation](https://github.com/Nesvilab/philosopher/wiki) to see how to set other options. You can also run the Prophets from Philosopher. I'm closing the issue, but feel free to reopen it if necessary.
