### ISSUE TITLE
search peptides with custom database

### ISSUE THREAD

**Issue by XiaofengxBjmu** [Nesvilab/philosopher#170]
Hi,
I wanted to search for peptides that contained some mutations and added variant peptides to the human protein database. So the database contains both original and variant proteins like this:

>tr|X6RM59|X6RM59_HUMAN X6RM59,rs1415218625,307,M/V,291,329 OS=Homo sapiens OX=9606 GN=NT5C3A PE=1 SV=1
IGYLNDRVDELLEKYVDSYDIVLVQDESLEVANSILQK

>tr|X6RM59|X6RM59_HUMAN 5'-nucleotidase OS=Homo sapiens OX=9606 GN=NT5C3A PE=1 SV=1
MDRAAVARVGAVASASVCALVAGVVLAQYIFTLKRKTGRKTKIIEMMPEFQKSSVRIKNPTRVEEIICGLIKGGAAKLQIITDFDMTLSRFSYKGKRCPTCHNIIDNCKLVTDECRKKLLQLKEKYYAIEVDPVLTVEEKYPYMVEWYTKSHGLLVQQALPKAKLKEIVAESDVMLKEGYENFFDKLQQHSIPVFIFSAGIGDVLEEVIRQAGVYHPNVKVVSNFMDFDETGVLKGFKGELIHVFNKHDGALRNTEYFNQLKDNSNIILLGDSQGDLRMADGVANVEHILKIGYLNDRVDELLEKYMDSYDIVLVQDESLEVANSILQKIL

Philosopher gives me an **Bus error** when I use **philosopher database --custom** , So how to build the database can avoid error reporting and meet the requirements of Comet, PeptideProphet, ProteinProphet and filter I will use later.

Thank you for the help.

Sincerely,
Xiaofeng

**Comment by prvst** [comment]
Hi @XiaofengxBjmu , could you describe what exactly is the error? You can post the message here.

**Comment by XiaofengxBjmu** [comment]
Hi,
The output is **Bus error** only,

[00@login01 MS_philosopher]$ philosopher database --custom ./db/2020-11-16-contam-UP000005640.fas
INFO[02:56:47] Executing Database  dev
WARN[02:56:47] Contaminants are not going to be added to database
INFO[02:56:47] Processing decoys
Bus error
[00@login01 MS_philosopher]$

**Comment by XiaofengxBjmu** [comment]
In addition, I also tried to divide the original and variant proteins into two databases. I searched two database with the same raw file **MS.mzML** using Comet and got **MS-O.pep.xml** and **MS-V.pep.xml**. I got **interact.pep.xml** with PeptideProphet. None of this has gone wrong. 

But there was an error when I ran **philosopher proteinprophet interact.pep.xml**, the error is:

> (base) [00@login01 MS_philosopher]$ philosopher proteinprophet interact.pep.xml
> INFO[15:02:50] Executing ProteinProphet  dev
> ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64))
>  (no FPKM) (using degen pep info)
> Reading in /home/qusaisi/MS_philosopher/interact.pep.xml...
> ...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05
> WARNING: no data - output file will be empty
> FATA[15:02:52] Cannot execute program. There was an error with ProteinProphet, please check your parameters and input files

Thank you for the help.

Sincerely,
Xiaofeng

**Comment by prvst** [comment]
>INFO[15:02:50] Executing ProteinProphet dev

Which version of Philosopher are you running? Are you compiling the code yourself?

**Comment by XiaofengxBjmu** [comment]
I compile the code myself. I run **philosopher version** like this:

> [0016181044@login01 MS_philosopher]$ philosopher version
> INFO[09:20:49] Current Philosopher build and version         build=build version=dev

**Comment by prvst** [comment]
I'm not sure what is the cause of the issue. A bus error is usually something raised by the system hardware.
