### ISSUE TITLE
Questions related to pipeline

### ISSUE THREAD

**Issue by Niveda-S** [Nesvilab/philosopher#171]
Hi,
I have a few questions regarding the pipeline command:

1) I am trying run the pipeline command on philosopher and I get combined report for protein and peptide but not for ion. Is there some setting I must run to generate ion.tsv?

2) The pipeline command marks proteinprophet as 'no' and does not have the iprophet tool listed according to the yaml file:
![image](https://user-images.githubusercontent.com/17713621/100904371-d25f1300-347b-11eb-9362-714c38aef5cc.png)
but the combined.pep.xml and combined.prot.xml are still being generated. Are there other steps being run that are independent of the pipeline? Is there a way to find out the exact commands run in the pipeline?

3) I am trying to get mzML file level reports. I have tried 3 ways:
a) Use filter, freequant and report commands to all of the input pepXML files. -> This generates a report but there is no file level breakdown.
 b) Use the same command as a) but generate msstats compatible report. -> This generates a msstats.tsv file that contains a column called 'spectrum file' that contains file-level information    
c) Use pipeline command with each mzML in a separate folder. -> This generates combined protein and peptide tsv that contain file level information.
How are the reports different between b) and c)? 

4) I am trying to run 2 search engines in parallel before generating the report (ex: pipeline command has the option to run comet and MSFragger) but this errors out pipeline with a message saying that only one search engine can be run at a time. Is there a way for me to do this? I am trying to use search engines (comet and tandem) outside of philosopher to be compatible and generate reports?

Thanks,
Niveda

**Comment by prvst** [comment]
Hi @Niveda-S,

1. There's no combined ion report yet.

2. Changing ProteinProphet to `yes` will force the pipeline to run ProteinProphet in each folder. You want to do that only if you want to have individual protein inference, not combined.

3. There's no option for iProphet in the pipeline as a separate tool. iProphet is executed if you choose to run the combined analysis and have combined peptide reports.

4. There is no way to run two search engines in tandem; you must set them manually.

It seems to me that you're getting confused because of the way how data must be organized. You have to separate in different folders each one of your data sets. If you are testing two different searches with different engines, put them in two separate folders. If the goal is to do a combined analysis, leave ProteinPrpphet: no, and put yes on Abacus. If you want individual reports, do the other way around.

**Comment by Niveda-S** [comment]
Hi @prvst ,

Thanks for your response. I just have a couple of follow-up questions:
1) Since ProteinProphet is no, does that mean that the filter command is run with only the interact.pep.xml file as input i.e. no prot.xml is required? 

2) For a multi-search engine, if I separate them in two folders, then will the combined analysis try to distinguish the results between the two search engines? For example, if I have three samples separated in three folders, then the combined results are as below:
![image](https://user-images.githubusercontent.com/17713621/101086628-ff87f000-3565-11eb-91b5-716bf4a9928f.png)
where crude_1, crude_2 and crude_3 are samples separated into different folders. 
In the above case I only ran the comet search engine but if I also ran the MSFragger search engine, would I now have 6 folders - 3 samples with comet and 3 with MSFragger? In that case, will my results show 6 columns? Is there a way to merge the results of the sample sample coming from comet and MSFragger search engines?

**Comment by prvst** [comment]
If **ProteinProphet** = **no** & **Abacus** = **no** => no protein inference is used

If **ProteinProphet** = **yes** & **Abacus** = **no** => local protein inference is used. ProteinProphet will be executed once for each folder, creating individual protein inference that will be used for each filtering.

If **ProteinProphet** = **no** & **Abacus** = **yes**. Global or combined protein inference will be used. ProteinProphet will be executed once with pep.xml files from all experiments. This is the way if you are comparing multiple experiments.

Regarding your second question; Each column in the final table represents a different folder. If you are comparing the search results from two different engines, make them separate folders (i.e. Crude_1_Comet, Crude_1_Fragger, etc.). IF you put all results from both searches in the same folder, they will be combined.
