### ISSUE TITLE
Philosopher: variable modifications are missed in "assigned modification" column due to rounding error

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#173]
Hi Felipe,

This is a bug from a user. In the pepXML's header, there is a modification like this
```xml
<aminoacid_modification aminoacid="C" massdiff="470.3059" mass="630.3365" variable="Y"/>
```

In the PSM hit, it shows
```xml
<mod_aminoacid_mass mass="630.3366" position="7"/>
```

As you can see, the mass value is off by 0.0001 due to a rounding error, which is unavoidable since we are using limited precision in expressing a floating point number.

I think this is not a small issue since some downstream tools rely on the "assigned modification" column. Could you please it by adding a tolerance (e.g., 0.001) in checking if two numbers are the same?

Best,

Fengchao

**Comment by prvst** [comment]
Added to 3.5.14.
