### ISSUE TITLE
Not all peptides shown in peptide.tsv

### ISSUE THREAD

**Issue by o-t** [Nesvilab/philosopher#178]
Hi,

I analysed some label-free data with the pipeline mode, but for some reason much fewer peptides are shown in peptide.tsv than in psm.tsv. When I compared the 2 output files, lots of peptides present in psm.tsv are absent in peptide.tsv. Why would that be? Thank you!

**Comment by prvst** [comment]
Hi @o-t. Thanks for reaching out. You stumbled on a problem that was recently reported. A fix is on the way, so keep your repository updates to get notified about the release.
