### ISSUE TITLE
MSFragger with PTMProphet for orbitrap data

### ISSUE THREAD

**Issue by EvaLangu** [Nesvilab/philosopher#182]
We are trying out MSFragger for our timsTOF data and we have faced some issues with PTMProphet and MSFragger as in issue #110. While we are waiting for a fix for that, we wanted to try MSFragger and PTMProphet on our orbitrap phosho enriched data, which we usually analyzed with MaxQuant. 

We have managed to run PTMProphet on MSFragger's output of the Orbitrap data but we get only the site probabilities and we wanted a way to filter the PSMs the same way we use the 'Localization prob' of MaxQuant (I think this is equivalent to the _information content of modified PSM site assignments_ discussed in the PTMProphet article ?). Is it possible to get this added to the output? The other thing is PTMProphet updates only the psm table and was wondering if there is an easy way the PTM information is propagated to the peptide and protein tables as well. 

My apologies if I have overlooked a tutorial or some other information regarding these issues; if there is a material out there I could reference, please let me know.  

Thank you for your consideration,
Eva

**Comment by hayse1** [comment]
Hi Eva, thanks for your question and your patience! For now, the site probabilities are listed only in the 'Phosopho Site Localization' column of the psm.tsv table as you mentioned, but we are currently working on some changes to PTM localization reporting that may make it easier to filter by localization probabilities. Sorry I don't have a more specific answer/timeline for you at the moment.

Sarah

**Comment by EvaLangu** [comment]
Hello Sarah,

Thank you for your message. I will keep watching this thread for new developments.

BR,
Eva
