### ISSUE TITLE
incosistency in the combined_peptide.tsv file?

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/philosopher#187]
Dear MSFragger team,

Today I found out that when I run a non-specific search and generate a combined_peptide.tsv file there seems to be some inconsistency between the 'Protein' and 'ProteinID' columns. 

In the 'Protein' column, sometimes the incorrect name is written (or the other way around?). I have manually checked a few and  to me it seems they might come from the 'Mapped Proteins' column from the sample's 'peptide.tsv' file.

I could send you some example files of course.

Best,
Patrick

**Comment by PatrickvanZalm** [comment]
Thank you. Please let me know if you'd need some additional info and/or files.

**Comment by prvst** [comment]
Fixed. Added to v3.5.14

**Comment by PatrickvanZalm** [comment]
Hi Felipe,

 

Thank you very much!! I will re-do some of my searches. 

 

Cheers,

Patrick
