### ISSUE TITLE
Headers for custom db with 6-frame translations

### ISSUE THREAD

**Issue by katriken** [Nesvilab/philosopher#190]
Hello,

my custom protein db consists of potential protein fragments. What headers would work here?

Best,
Katja

**Comment by prvst** [comment]
Hi @katriken, You can follow the examples found [here](https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database).

**Comment by katriken** [comment]
According to that page, I should use protein ids from Uniprot/NCBI/ENSEMBL. I don't have these ids, because I have a db of potential protein fragments.

**Comment by prvst** [comment]
That means you can use their format, it does not mean you need to download the sequence from them. If that is too complicated, you can go for the simple custom format, see below:

- UniProt: >sp|P02489|CRYAA_HUMAN Alpha-crystallin A chain OS=Homo sapiens OX=9606 GN=CRYAA PE=1 SV=2

- NCBI: >NP_000385.1 alpha-crystallin A chain isoform 1 [Homo sapiens]

- ENSEMBL: >ENSP00000291554.2 pep chromosome:GRCh38:21:43169008:43172805:1 gene:ENSG00000160202.7 transcript:ENST00000291554.6 gene_biotype:protein_coding transcript_biotype:protein_coding gene_symbol:CRYAA description:crystallin alpha A [Source:HGNC Symbol;Acc:HGNC:2388]

- or generic: >P02489

**Comment by prvst** [comment]
The generic format can be a simple ID like the example above:

>P02489

And you can also append other things to it:

>P02489_Protein__Gene_Description
