### ISSUE TITLE
Failed workspace checkup

### ISSUE THREAD

**Issue by im281** [Nesvilab/philosopher#194]
Commands run:
ubuntu@ip-10-82-196-34:~/apps/philosopher-container/app$ ./philosopher workspace init
INFO[16:02:50] Executing Workspace  v3.4.13                 
INFO[16:02:51] Done      

Then:
./philosopher peptideprophet --database  2021-03-04-decoys-contam-UP000005640.fas --ppm --accmass --expectscore --decoyprobs --nonparam peptides.pepXML

**WARN[0000] Workspace not detected                       
FATA[16:04:03] Workspace not found. Failed to checkup the initialization**

**Comment by prvst** [comment]
try `philosopher workspace --init`

**Comment by im281** [comment]
On Linux this results in 'command not found'

ubuntu@ip-10-82-196-34:~/apps/philosopher-container$ philosopher workspace --init
bash: philosopher: command not found

**Comment by prvst** [comment]
'Command not found' means that the program is not in the local directory or not in the path. Double-check where your files are.

**Comment by im281** [comment]
thank you
