### ISSUE TITLE
Increasing computational resources did not reduce run time

### ISSUE THREAD

**Issue by o-t** [Nesvilab/philosopher#195]
Hi,

I am running the pipeline mode, and I want to optimise the computational resources used. I have tried assigning different amount of RAM and number of threads to analyse the same set of files, but it seems the time the analysis took did not change much, even though I have significantly increased the amount of RAM and number of threads in the parameters files. Are there some steps that only uses a single thread, no matter how many I set? Or what would be some other reasons for this behaviour?

Thanks so much!

**Comment by hayse1** [comment]
Hi o-t, there are certain steps that can only run on a single thread and/or aren't sped up by increasing RAM. If you are running an MSFragger search, you can set `calibrate_mass: 0` to skip mass calibration and parameter optimization and save some time (check previous calibration/optimization logs to ensure this makes sense for your data & adjust your initial MSFragger parameters if needed). If you are running PTM Localization, make sure to set the `maxthreads` parameter in the PTMProphet section of the philosopher.yml file as well.

Sarah

**Comment by o-t** [comment]
Hi Sarah,

Thanks for the swift response. How can I check which steps can only run on a single thread and/or aren't sped up by increasing RAM?

**Comment by hayse1** [comment]
In the philosopher.yml file, you can see/adjust the relevant parameters in their respective sections:

**msfragger:**
`memory`
`num_threads`

**PTM Localization**
`maxthreads`

**Integrated Isobaric Quantification**
`memory`

**Comment by anesvi** [comment]
Thanks, Sarah

To add to that, MSFragger is fast and takes advantage of memory and multiple cores well. So does IonQuant.

But Philosopher components are mostly single core (expect PTM-Prophet). So usually PeptideProphet and ProteinProphet and filtering take a quite a bit of time and these steps do not benefit from memory or more cores.

In FragPipe, we at least can each file through PeptideProphet in parallel on separate cores, and that helps. But I am not sure if running via philosopher yaml file can do that, and it only  makes sense if you do not combine separate runs in one pep.xml file anyway (which I think Philosopher’s pipeline  does, not sure if there is a n option)

Alexey

**Comment by prvst** [comment]
Hi @o-t  To add something to what was said above, Philosopher is composed of different tools. The Prophets work mostly on a single core, so there isn't much we can do about it, and the part that is native to Philosopher takes advantage of concurrent processing when possible. Giving more RAM won't improve things either. Philosopher base RAM usage is 500MB, and the memory usage is only related to your data file size (i.e., the bigger the files, the more RAM you will need). What will help is getting a computer with a faster CPU.

**Comment by o-t** [comment]
I see. Thank you so much for the help!
