### ISSUE TITLE
Sequence window

### ISSUE THREAD

**Issue by jayieh** [Nesvilab/philosopher#196]
Hi,

I was trying to find some information on the sequence context of peptides identified by MSFragger within the philosopher output.

Other pipelines give e.g. N- and C-terminal cleavage window, adjacent AA or the position within a protein.

Am I missing a column, or is this simply not reported?

**Comment by prvst** [comment]
Hi, @jayieh . Which report are you using?

**Comment by jayieh** [comment]
Plain and simple

"philosopher report"

**Comment by prvst** [comment]
Sorry, I meant which report file are you using? the PSM table?

**Comment by jayieh** [comment]
Hi @prvst,

sorry - I thought I had mentioned that in my initial post: I was checking the tsv files (PSM, peptides, etc ...), but could not find that information. Also according to the "Reports" section in the Wiki, this information is not provided.

What you be your suggestion?

**Comment by prvst** [comment]
Yes, the information is not in the reports. I'll discuss internally with my colleagues the possibility of adding them back. If so, it will be available on the next release.

**Comment by jayieh** [comment]
That sounds great! Thanks!
