### ISSUE TITLE
Result of Philosopher pipeline

### ISSUE THREAD

**Issue by o-t** [Nesvilab/philosopher#197]
Hi,

Not sure if this question is more related to MSFragger or Philosopher. Apologies if I asked at the wrong place. I have just run the Philosopher pipeline on some TMT data with multiple batches. I've also run TMT-integrator on the data. My question is, for the protein intensities in the protein.tsv files for the respective batches, have they been normalised within a batch? If I were to analyse a single TMT experiment, and so (I think) TMT-integrator is not necessary, can I directly take the protein intensity in the protein.tsv file for further analyses? Thank you so much.

**Comment by prvst** [comment]
Hi @o-t. Philosopher tables contain only "raw" intensity values, so these are not normalized nor adjusted at all. If you are going to use them, you will have to do it using your chosen method. I would suggest that you run TMT-I regardless. You can choose between the tables with or without normalization.

**Comment by o-t** [comment]
I see. Thanks for the help!
