### ISSUE TITLE
philosopher comet got nothing

### ISSUE THREAD

**Issue by limbo1996** [Nesvilab/philosopher#200]
**Describe the bug**
Hi !  I ran the code based on this article [Step-by-step-analysis-with-Comet](https://github.com/Nesvilab/philosopher/wiki/Step-by-step-analysis-with-Comet).

When I download the example data, it don't have  `06_CPTAC_TMTS1-NCI7_Z_JHUZ_20170509_LUMOS.mzML`, But there are two similar files `06_CPTAC_TMTS1-NCI7_P_JHUZ_20170509_LUMOS.mzML` and `06_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML`, So I download both of them.

Next I ran
```
philosopher comet --param comet.params 06_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML
```
I got
```
INFO[19:32:02] Executing Comet  v3.4.13                     
INFO[19:32:03] Done 
```
But there is no 06_CPTAC_TMTS1-NCI7_Z_JHUZ_20170509_LUMOS.pep.xml file what [Step-by-step-analysis-with-Comet](https://github.com/Nesvilab/philosopher/wiki/Step-by-step-analysis-with-Comet) said. The same thing happens with another file

This is the head of my comet.params file
```
# comet_version 2019.01 rev. 1
# Comet MS/MS search engine parameters file.
# Everything following the '#' symbol is treated as a comment.

database_name = /home/limbo1996/Github/MS_data_process/MS_workspace/2021-04-13-decoys-reviewed-contam-UP000005640.fas
decoy_search = 0                       # 0=no (default), 1=concatenated search, 2=separate search
peff_format = 0                        # 0=no (normal fasta, default), 1=PEFF PSI-MOD, 2=PEFF Unimod
peff_obo =                             # path to PSI Mod or Unimod OBO file

num_threads = 0                        # 0=poll CPU to set num threads; else specify num threads directly (max 128)
```

**Please complete the following information:**
 - OS: Windows WSL  Ubuntu 20.04 LTS

Thanks !

**Comment by hayse1** [comment]
Hi! There is a typo in the file name, thanks for catching it.

It looks like Comet did not initialize properly, it might have to do with running on the Linux subsystem. We have not tested in environments like that since Philosopher works on both Windows and Linux. Can you try running on just Windows (in the cmd) instead?

Sarah

**Comment by limbo1996** [comment]
> Hi! There is a typo in the file name, thanks for catching it.
> 
> It looks like Comet did not initialize properly, it might have to do with running on the Linux subsystem. We have not tested in environments like that since Philosopher works on both Windows and Linux. Can you try running on just Windows (in the cmd) instead?
> 
> Sarah

Thanks！ It works correctly on Linux and Windows.
