### ISSUE TITLE
PeptideProphet parsers not found

### ISSUE THREAD

**Issue by aezimmerman** [Nesvilab/philosopher#201]
I am new to Philosopher, and tried to run PeptideProphet on a linux cluster using a database generated with Philosopher and pepXML output from an MSFragger search, but got the following error that I'm uncertain how to address. I extracted the philosopher_v3.4.13_linux_amd64.zip release to use Philosopher on the server. Any recommendations would be appreciated.

Thanks very much,
Amy

OS information: 
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Description:	Red Hat Enterprise Linux Workstation release 6.6 (Santiago)

(philos_env) [zimm824@constance01 ~]$ ./philosopher workspace --init
INFO[19:55:22] Executing Workspace  v3.4.13                 
INFO[19:55:23] Creating workspace                           
INFO[19:55:23] Done                                         
(philos_env) [zimm824@constance01 ~]$ ./philosopher peptideprophet --database EndoPop/Data/ref/2021-04-07-decoys-contam-2615840639.genes.faa.fas --ppm --accmass --expectscore --decoyprobs --nonparam EndoPop/Data/N15_fragger_all_2021-04-14/Endopop_Proteomics_1_31Mar21_Merry_20-11-14/Endopop_Proteomics_1_31Mar21_Merry_20-11-14.pepXML
INFO[20:06:10] Executing PeptideProphet  v3.4.13            
/tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/InteractParser: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/InteractParser)
/tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/InteractParser: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/InteractParser)

  - /people/zimm824/EndoPop/Data/N15_fragger_all_2021-04-14/Endopop_Proteomics_1_31Mar21_Merry_20-11-14/interact-Endopop_Proteomics_1_31Mar21_Merry_20-11-14.pep.xml
/tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/RefreshParser: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/RefreshParser)
/tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/RefreshParser: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/RefreshParser)
/tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/PeptideProphetParser: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/PeptideProphetParser)
/tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/PeptideProphetParser: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/da53fa22-ac3f-453b-9ded-c7dd497beb13/PeptideProphetParser)
INFO[20:06:40] Done

**Comment by fabianegli** [comment]
Hi Amy, you might want to check the documentation of the cluster you use to see if you need to load some module before you can run C code. The cluster I have access to sometimes provides multiple module versions and you might need to choose a newer one. If the file `/lib64/libc.so.6` exists, you can check from which package it originates by `rpm -qf /lib64/libc.so.6`. It should give you a string with the version number of the installed `glibc` version.

**Comment by aezimmerman** [comment]
Thank you for your assistance. I'll work with the cluster administrator to get this sorted out.
