### ISSUE TITLE
macOS permissions

### ISSUE THREAD

**Issue by snp** [Nesvilab/philosopher#21]
➜  tmp ~/bin/philosopher workspace --init
INFO[16:24:39] Executing Workspace 20180518
INFO[16:24:40] Creating workspace
FATA[16:24:40] cannot create directory: Can't find temporary directory; check folder permissions

Current directory is writable, .meta directory is created, but then nothing:
➜  tmp ls -la .meta
total 0
drwxr-xr-x  2  staff   64 May 21 16:24 .
drwxr-xr-x  7  staff  224 May 21 16:24 ..

But, executing philosopher with sudo works. Which folders does it try to access?

**Comment by prvst** [comment]
Philosopher creates a local hidden folder called `.meta`. This folder is always created on the path where you run the `workspace` command. It looks to me, by what you are describing, that there's still some issue with your local permissions, specially because you are able to run it as sudo. Have you tried the same command on your home folder ?

**Comment by snp** [comment]
I've tried it in a home folder. And .meta folder is being created as you can see above, with normal privileges and without problem writing into it. It seems like it also tries to create some temporary folder in a wrong place:
FATA[16:24:40] cannot create directory: Can't find temporary directory; check folder permissions

Maybe some linux-stile temporary folders like /var/tmp are tried, which are not available on Macs.

**Comment by gozzdzik** [comment]
the same issue with my OSX 10.13.15. any ideas so far?

**Comment by prvst** [comment]
not yet, but I'm working on it. So far I suggest you to try running the program on a Linux or Windows machine. have in mind that the full pipeline will not work on a MAc as well because there are no prophets version for Mac OS.

**Comment by prvst** [comment]
@gozzdzik have you tried again with a recent version ?

**Comment by xyz1396** [comment]
Is it possible to compile the project on macOS?

**Comment by guoci** [comment]
not supported
