### ISSUE TITLE
zero intensity from freequant

### ISSUE THREAD

**Issue by taejoon** [Nesvilab/philosopher#238]
**Describe the bug**

After running 'freequant' for quantification, all intensities in the report were zero. 

**To Reproduce**

~/src/MS/philosopher/v3.4.13/philosopher workspace --init
~/src/MS/philosopher/v3.4.13/philosopher database --annotate ../../2021-06-12-decoys-contam-UP000005640.fas
~/src/MS/philosopher/v3.4.13/philosopher comet --param comet.params *mzML
~/src/MS/philosopher/v3.4.13/philosopher peptideprophet --database ../../2021-06-12-decoys-contam-UP000005640.fas --ppm --accmass --combine --expectscore --decoyprobs *pep.xml
~/src/MS/philosopher/v3.4.13/philosopher proteinprophet interact.pep.xml
~/src/MS/philosopher/v3.4.13/philosopher filter --razor --pepxml interact.pep.xml --protxml interact.prot.xml
~/src/MS/philosopher/v3.4.13/philosopher freequant --dir ./
~/src/MS/philosopher/v3.4.13/philosopher report

Just in case, I also uploaded mzML files and the workspace directory at https://pub.taejoonlab.org/repo/philosopher/

**Expected behavior**

Ion/peptide/protein tsv tables from "report" will have some intensity values for quantification, not zero. 

**Please complete the following information:**

 - OS: Ubuntu 20.04 LTS
 - Version: build=1611589727 version=v3.4.13

**Comment by prvst** [comment]
Can you tell more about your data, and you converted the raw?

**Comment by taejoon** [comment]
Ah.. previously I used the mzML converted from mzXML file (RAW -> mzXML -> mzML). 

After your comment, I tried to use mzML converted from RAW file directly, and it works. I think there is some missing info between mzXML and mzML. 

Thank you for your help (you may close this ticket).
