### ISSUE TITLE
Means of determining program versions from results

### ISSUE THREAD

**Issue by mriffle** [Nesvilab/philosopher#244]
Just throwing this out there because it would be helpful to me:

I don't see an easy way of determining which versions of philosopher, comet, MSFragger, or TPP were run when examining the TSV files generated by running ``philosopher report``. I could look into the pepXML file and get versions for comet/MSFragger and TPP, but not philosopher (unless I'm missing that).  But ideally, if I'm only processing, say, psm.tsv, I would be able to see what versions of the programs generated those results.

Maybe some comment lines at the top of the file?

**Comment by prvst** [comment]
Hi @mriffle. We are studying a way to add a new report containing information like that with some run QC. As you noticed, both MSFragger, and the Prophets usually write their version at the XML file headers, including name, version, and build. Our idea is to try maintaining the tables with a tidy format as much as possible, so we want to avoid adding lines at the top with metadata.
