### ISSUE TITLE
Problem with Assigned Modification in psm.tsv

### ISSUE THREAD

**Issue by uonnet** [Nesvilab/philosopher#245]
Hi,

I recently re-run an phospho analysis with the philosopher pipeline, and found the results quite strange. As you can see in the screenshot, even when the columns of Modified Peptide, Number of Phospho Sites and Phospho Site Localization show these PSMs have phospho mod, phospho mod does not show up at the Assigned Modification column. Also, I found the group by site result from TMT-integrator also has very few phosphosites, much fewer than when I previously analysed the same files.

![螢幕擷取畫面 2021-07-19 113857](https://user-images.githubusercontent.com/54391198/126099872-9503eb91-c46d-460a-95a2-da89c5818ab9.png)

I checked the parameters for the 2 analysis runs and they are the same. What may be causing these problems? Thank you so much!

**Comment by prvst** [comment]
Hi @uonnet. This is a known issue that we fixed recently. A new update will be released soon.
