### ISSUE TITLE
Issue with PTMProphet in philosopher pipeline

### ISSUE THREAD

**Issue by uonnet** [Nesvilab/philosopher#258]
I was running the pipeline mode of philosopher and encountered this error message
```
Creating 40 threads
Wait for threads to finish ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
Unknown file type. No file loaded.INFO: Reading file interact.pep.xml ...
/home/Core/BatchD/Enriched_PMSYDPool-F1_180min_MS2.mzMLUnknown file type. No file loaded./home/Core/BatchD/Enriched_PMSYDPool-F1_180min_MS2.mzMLINFO: Reading file interact.pep.xml ...


INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
Unknown file type. No file loaded./home/Core/BatchD/Enriched_PMSYDPool-F1_180min_MS2.mzML
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
INFO: Reading file interact.pep.xml ...
time="17:13:46" level=fatal msg="Cannot execute program. there was an error with PTMProphet, please check your parameters and input files"
```
This is the full log:  [o1008529.txt](https://github.com/Nesvilab/philosopher/files/6916027/o1008529.txt)

Just in case, here is the mzML file mentioned in the error message: https://we.tl/t-A5sdimV0uY. I don't think there is something wrong with it though.

Thanks for your help!

**Comment by sarah-haynes** [comment]
Hi, thanks for sharing your log and mzML. I was able to run the pipeline successfully on that file, here is the pipeline configuration file I used with [Philosopher 4.0.0](https://github.com/Nesvilab/philosopher/releases/tag/v4.0.0) and [MSFragger 3.3](https://msfragger.arsci.com/upgrader/):

[philosopher.yml.zip](https://github.com/Nesvilab/philosopher/files/6925987/philosopher.yml.zip)

Can you try those versions? Let me know if it doesn't work for you.
--Sarah

**Comment by prvst** [comment]
@uonnet to complement what @sarah-haynes is telling you, PTMProphet sometimes behaves weirdly when you request for many threads. My suggestion for future cases like this is to reduce the number of threads, and try again.

**Comment by quark-spec** [comment]
Thanks Sarah for your config. Yes it worked on that mzML file when only that file was analysed, but once I used the config on all 18 mzML files, the error message again mentioned the same mzML I shared is problematic.

Thanks Felipe for the suggestion. I will try that. What number threads do you recommend?

Thanks again!

**Comment by uonnet** [comment]
Thanks Sarah for your config. It worked on that file when only that mzML file was analysed, but once I used the config on all 18 files I have, the error message again highlighted that mzML.

Thanks Felipe for the suggestion. I will try that. How many threads do you recommend?

Thanks again!

**Comment by prvst** [comment]
There's no "right" number, so I would suggest trying 10 first. If the issue persists, I recommend reaching out to the PTMProphet developers at the TPP forum. Since we are not maintaining PTMProphet, there's not much we can do to fix it.
