### ISSUE TITLE
Philosopher Filter Error

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/philosopher#262]
Dear Team,  

after a SpectraST search I generated *interact.pep.xml and *interact.prot.xml files peptide- and proteinprophat. Afterwards I wanted to filter the output for FDRs. Although numbers of target and decoy entries were comparable with other datasets I had one, which resulted in an error during filtering on protein level. Please find more details in the attached image.

I'm looking forward for your support.

![Error](https://user-images.githubusercontent.com/51822132/129347638-03cf248e-cd9f-49d1-a8f1-a2e7bafeee93.png)

**Comment by prvst** [comment]
Did you try increasing the protein FDR, as the program suggested?

**Comment by anesvi** [comment]
What is the sample? I see a lot of peptides passing 1% FDR. If it is a purified protein or something like it, then there will not be enough proteins to get 1% FDR threshold established. But if there are many proteins in the sample, then something not right.

**Comment by JB91451** [comment]
Hi Felipe and Alexey,

we did not increase the protein FDR, as the sample is the measurement of a gel lane loaded with a cellular extract. So we expect ~1600+ proteins. With the very same settings the ID rate for all other gel lanes of the same batch was quite normal. 

I assumed that by coincidence there was a decoy hit ranking among the top protein hits and that the FDR calculation than stopped to early. However, when sorting the protein prophet output in the TPP viewer by protein probability, the first decoy was only after approx. 1/3 of the list.

Best,
Sandra and Juergen

**Comment by anesvi** [comment]
Thanks, then we need to see the files. Was it a regular database (downloaded by philosopher)?
Would have to ask Felipe to take a look

**Comment by prvst** [comment]
Can you please try increasing the threshold to 100% (_--prot 1_)? That will tell us how many proteins you have in that sample.

**Comment by anesvi** [comment]
Can you send us excel table with proteins from the tpp viewer?
But sending the files (the database + pep.xml and prot.xml) would be helpful too, so we can run it

**Comment by JB91451** [comment]
In the meantime we re-run the filter with the --prot 1 option:
In the complete data set the protein FDR reaches ~3% with 2546 proteins at a proteinProphet threshold of 0.7774.

![Filter_Prot_1](https://user-images.githubusercontent.com/51822132/129534353-257c4667-1608-4482-bcc9-0c57b75fe3da.png)

We also exported the protein list from TPP viewer. In the attached file, peptides are displayed and the first decoy can be found in row 36960.

[Protein_interact.prot.txt](https://github.com/Nesvilab/philosopher/files/6990837/Protein_interact.prot.txt)

**Comment by prvst** [comment]
That means this data set filtering in particular cannot reach 1%, and the lowest it can go is 3%. I suggest adjusting the value, so your processing won't stop again.

**Comment by anesvi** [comment]
Hi Felipe,
I looked at the file. Sorted by best peptide probability. Removed protein duplicated. The first decoy is protein #1784. So there is no way best FDR would be 3%. We need to take a closer look
Alexey

**Comment by prvst** [comment]
If you want me to take a closer look, then I need all XML files, and the database.

**Comment by JB91451** [comment]
Hi Felipe,

we could send it tomorrow morning. Could you open us a box folder? 

Best,
Juergen

**Comment by prvst** [comment]
https://www.dropbox.com/request/PKXgs11nKHWt44weAdXI

**Comment by JB91451** [comment]
As far as I remember, it was the Prophets that come with the philosopher but I need to cross-check with Sandra.

**Comment by anesvi** [comment]
We looked into this closer, and we see that there are a lot of entries that have the same probability from PeptideProphet, 0.999 (‘initial probability’). They include decoys, with the same probability. Philosopher uses the initial probability of the best peptide as the protein score, and thus the best it can get is gets 3% FDR. It could be that PeptideProphet modeling with SpectraST is not very good. We do not have an easy fix in philosopher for that. It seem to be caused by something in spectraST scores. You can try to run through iprophet, delete the original pep.xml, and run filter. Or ask Felipe to make a version that uses nsp adjusted probability instead of the initial probability.
Alexey

**Comment by prvst** [comment]
Actually, I have a different suggestion. If you add _--razor_ to your filtering, then the peptides get re-assigned and the filter can move forward below 3%. I was able to get 1% FDR by doing that.

**Comment by anesvi** [comment]
Oh, in FragPipe –razor is default. Yes, use --razor.

**Comment by JB91451** [comment]
Dear Felipe and Alexey,

Thank you for investigating this issue so thoroughly. Using the --razor option fixed it for our data set and I clearly prefer this solution over applying an increased protein-FDR threshold.

Thanks again,
Juergen

**Comment by prvst** [comment]
Glad to know!
