### ISSUE TITLE
PeptideProphet - InteractParser.exe 

### ISSUE THREAD

**Issue by kevinnestler** [Nesvilab/philosopher#263]
Hello,

I am running into an error with PeptideProphet. The full log is attached, but the error reads 
"Cannot execute program. fork/exec P:\Users\nestlerk\AppData\Local\Temp\4\efb4f3eb-b205-46a9-82ae-cbcea0322323\InteractParser.exe: %1 is not a valid Win32 application." 

I am running FragPipe v16.0 with Philosopher v4.0.0 on Windows. 
Is this just a system error on my end? I've cleared the cache and had the admin reinstall the applications and that did not work. Thank you for any help and advice.

[log_2021-08-19_17-54-26.txt](https://github.com/Nesvilab/philosopher/files/7017931/log_2021-08-19_17-54-26.txt)

**Comment by prvst** [comment]
What kind of Windows you have ?

**Comment by kevinnestler** [comment]
Windows server 2019

**Comment by prvst** [comment]
This is a problem related to your system. As far as I investigated, the source could be anything from a corrupted file system to hardware issues. I advise you to get assistance from your IT support.
