### ISSUE TITLE
itraq YML parameters

### ISSUE THREAD

**Issue by apataskar** [Nesvilab/philosopher#269]
Hi,

Thanks for the nice pipeline version of philosopher. worked very well with TMT data. I want to analyze similarily the iTRAQ data (4 plex) . Could you upload an example parameter file for such a data? I want to see in variable modification masses I have are correct

**Comment by prvst** [comment]
@apataskar You can use [Unimod](https://www.unimod.org/modifications_list.php?a=search&value=1&SearchFor=itraq&SearchOption=Contains&SearchField=) to verify the correct mass. For iTRAQ4, you can use 144.105918
