### ISSUE TITLE
rows with Zeros in combined_protein.tsv 

### ISSUE THREAD

**Issue by asifratul** [Nesvilab/philosopher#272]
To describe my exp design -
I metabolically labelled (N15) insects and did a mating experiment to find out N15-labelled male proteins, which got transferred in non-labelled females (and also opposite scenario). I dissected out female organs and have the following scheme -

2 samples (Normal Female mated with N15 male, N15 Female mated with Normal male) X 
3 replicates X 8 fractions X
2 runs in different machines (Orbitrap and QExactive). 

I am considering 2 parameters - 
Normal matching - to identify the normal protein from all samples. 
Heavy matching - to identify N15-labelled proteins.

I have modified the parameter files and ran them (in a linux HPC) using Comet, MSFragger, MsGF+ and Xtandem of TPP. As it is a gene/protein discovery project, I want to get the maximum number of proteins with high confidence. For the database - I downloaded the proteins from NCBI and added DECOY_ from the TPP utility.

For a mock run, I ran philosopher (from peptide validation to label-free quantification) on few fractions (ran on MSFragger). It ran well with ~190 proteins got picked up the combined.tsv file. but for some rows, there are no intensity scores (all zero).   

![image](https://user-images.githubusercontent.com/40979705/132184124-161aecfc-e640-4160-8f68-6fd073065f94.png)

Can you please advise me, how to deal with this zero intensity? 
I am attaching the pipeline in text.
[philosopher.yml.txt](https://github.com/Nesvilab/philosopher/files/7114394/philosopher.yml.txt)

Asif

**Please complete the following information:**
 - Philosopher
 - OS: Linux
 - Version: v4.0.0

**Comment by prvst** [comment]
Hi @asifratul. The combined analysis includes in the individual reports the proteins from the other experiments, that is why you see them with 0 quant. I changed this for the upcoming version.
