### ISSUE TITLE
philosopher pipeline does not run through

### ISSUE THREAD

**Issue by fstein** [Nesvilab/philosopher#289]
Hi,

I tried to set up the pipeline for running msfragger and philosopher. When I do this, I stops after the Protein Inference step. If I then modify the parameter.yml file and set only one step to yes to be executed, the analysis does finish if I execute it in the following order:
FDR Filtering:
Label-Free Quantification
Isobaric Quantification
Individual Reports
Integrated Reports

I have a TMT11 plex experiment (1 raw file which I converted to an mzML file with the following command: 'msconvert" *.raw --mzML --64 --zlib --filter "peak Picking true 1-"'

I attached my parameter file.
I also have another issue: When trying to print the philosopher.yml file using the "philosopher pipeline --print" command, it would print me a philosopher.yml file from version Version 3.6.0. The latest version is 4.0.1. If I use the Version 3.6.0, the pipeline complains alot about missing parameter.

Thanks for your help.

Cheers,

Frank
[philosopher.yml.txt](https://github.com/Nesvilab/philosopher/files/7553822/philosopher.yml.txt)

**Comment by sarah-haynes** [comment]
Hi Frank, can you share the log (console output) from the pipeline run so we can see the error message?
Thanks,
Sarah

**Comment by fstein** [comment]
I updated to the new philosopher version 4.1.1 and also used the updated parameter.yml file. I still get the same error.

**Comment by fstein** [comment]
Here is the new console output:
INFO[11:24:22] Executing Pipeline  v4.1.1                   
INFO[11:24:22] Creating workspace                           
INFO[11:24:22] Initiating the workspace on C:/MS_TestRun    
INFO[11:24:22] Creating workspace                           
WARN[11:24:22] A meta data folder was found and will not be overwritten.  
INFO[11:24:22] Annotating the database                      
INFO[11:24:23] Running the Database Search                  
MSFragger version MSFragger-3.4
Batmass-IO version 1.23.6
timsdata library version timsdata-2-8-7-1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 53 GB memory
Checking database...
Checking spectral files...
C:\MS_TestRun\Ernie_200910_P0000_Ernie_TMTyeast_25ng_60min_R1.mzML: Scans = 15246
***********************************FIRST SEARCH************************************
Parameters:
num_threads = 8
database_name = C:\MS_TestRun\2021-11-15-decoys-contam-Saccharomyces_cerrevisiae_UP000002311_05202016_6749entries.fasta.fas
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = false
write_calibrated_mgf = 0
isotope_error = 0/1
mass_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
ion_series_definitions = 
search_enzyme_name = stricttrypsin
search_enzyme_sense_1 = C
search_enzyme_cut_1 = KR
search_enzyme_nocut_1 = 
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = tsv_pepxml_pin
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 200.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
deisotope = 1
deneutralloss = true
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.500000,1.500000
clear_mz_range_low = 125.5
clear_mz_range_high = 131.5
excluded_scan_list_file = 
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = true
variable_mod_01 = 15.994900 M 3
variable_mod_02 = 42.010600 [^ 1
variable_mod_06 = 229.162930 n^ 1
variable_mod_07 = 229.162930 S 1
add_A_alanine = 0.000000
add_C_cysteine = 57.021460
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_K_lysine = 229.162930
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_Y_tyrosine = 0.000000
Number of unique peptides
	of length 7: 84703
	of length 8: 81329
	of length 9: 77405
	of length 10: 72902
	of length 11: 71900
	of length 12: 66591
	of length 13: 63744
	of length 14: 60464
	of length 15: 56608
	of length 16: 54471
	of length 17: 51326
	of length 18: 48168
	of length 19: 44809
	of length 20: 43036
	of length 21: 40923
	of length 22: 37881
	of length 23: 36015
	of length 24: 33916
	of length 25: 31304
	of length 26: 29495
	of length 27: 27834
	of length 28: 26493
	of length 29: 24903
	of length 30: 22759
	of length 31: 21176
	of length 32: 19741
	of length 33: 18323
	of length 34: 17128
	of length 35: 15792
	of length 36: 14514
	of length 37: 13725
	of length 38: 12801
	of length 39: 11748
	of length 40: 10738
	of length 41: 9971
	of length 42: 8783
	of length 43: 7439
	of length 44: 5553
	of length 45: 3682
	of length 46: 2135
	of length 47: 1133
	of length 48: 525
	of length 49: 264
	of length 50: 118
In total 1384268 peptides.
Generated 10920963 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.10 Da.
507847942 fragments to be searched in 1 slices (7.57 GB total)
Operating on slice 1 of 1: 
	Fragment index slice generated in 6.58 s
	001. Ernie_200910_P0000_Ernie_TMTyeast_25ng_60min_R1.mzML 0.9 s | deisotoping 0.8 s
		[progress: 15228/15228 (100%) - 15523 spectra/s] 1.0s | postprocessing 0.1 s
***************************FIRST SEARCH DONE IN 0.238 MIN**************************

*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |   3.48   1.45 |   0.02   0.91 |   0.30   1.32 |   0.10   1.26  
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count |   6409|   6426|   6398| skip rest
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1 
-------|-------|-------|-------|-------|-------|-------
 Count |   6472|   6472|   6472|   6426| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |   6453
-------|-------
-------|-------
 Rm P. |    1  
-------|-------
 Count |   6448
-------|-------
New fragment_mass_tolerance = 7 PPM
New use_topN_peaks = 175
New minimum_ratio = 0.000000
New intensity_transform = 0
New remove_precursor_peak = 0
************MASS CALIBRATION AND PARAMETER OPTIMIZATION DONE IN 1.300 MIN*********

************************************MAIN SEARCH************************************
Checking database...
variable_mod_03 has an empty value.
variable_mod_04 has an empty value.
variable_mod_05 has an empty value.
Parameters:
num_threads = 8
database_name = C:\MS_TestRun\2021-11-15-decoys-contam-Saccharomyces_cerrevisiae_UP000002311_05202016_6749entries.fasta.fas
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 7.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = false
write_calibrated_mgf = 0
isotope_error = -1/0/1/2/3
mass_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
ion_series_definitions = 
search_enzyme_name = stricttrypsin
search_enzyme_sense_1 = C
search_enzyme_cut_1 = KR
search_enzyme_nocut_1 = 
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = tsv_pepxml_pin
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = true
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 200.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
deisotope = 1
deneutralloss = true
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 175
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.0
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.500000,1.500000
clear_mz_range_low = 125.5
clear_mz_range_high = 131.5
excluded_scan_list_file = 
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = true
variable_mod_01 = 15.994900 M 3
variable_mod_02 = 42.010600 [^ 1
variable_mod_06 = 229.162930 n^ 1
variable_mod_07 = 229.162930 S 1
add_A_alanine = 0.000000
add_C_cysteine = 57.021460
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_K_lysine = 229.162930
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_Y_tyrosine = 0.000000
Number of unique peptides
	of length 7: 84703
	of length 8: 81329
	of length 9: 77405
	of length 10: 72902
	of length 11: 71900
	of length 12: 66591
	of length 13: 63744
	of length 14: 60464
	of length 15: 56608
	of length 16: 54471
	of length 17: 51326
	of length 18: 48168
	of length 19: 44809
	of length 20: 43036
	of length 21: 40923
	of length 22: 37881
	of length 23: 36015
	of length 24: 33916
	of length 25: 31304
	of length 26: 29495
	of length 27: 27834
	of length 28: 26493
	of length 29: 24903
	of length 30: 22759
	of length 31: 21176
	of length 32: 19741
	of length 33: 18323
	of length 34: 17128
	of length 35: 15792
	of length 36: 14514
	of length 37: 13725
	of length 38: 12801
	of length 39: 11748
	of length 40: 10738
	of length 41: 9971
	of length 42: 8783
	of length 43: 7439
	of length 44: 5553
	of length 45: 3682
	of length 46: 2135
	of length 47: 1133
	of length 48: 525
	of length 49: 264
	of length 50: 118
In total 1384268 peptides.
Generated 10920963 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.03 Da.
507847942 fragments to be searched in 1 slices (7.57 GB total)
Operating on slice 1 of 1: 
	Fragment index slice generated in 6.17 s
	001. Ernie_200910_P0000_Ernie_TMTyeast_25ng_60min_R1.mzBIN_calibrated 0.1 s
		[progress: 15182/15182 (100%) - 23834 spectra/s] 0.6s | postprocessing 1.6 s
***************************MAIN SEARCH DONE IN 0.187 MIN***************************

*******************************TOTAL TIME 1.725 MIN********************************
INFO[11:26:09] Running the validation and inference on C:/MS_TestRun 
INFO[11:26:09] Executing PeptideProphet on C:/MS_TestRun    
 file 1: C:\MS_TestRun\Ernie_200910_P0000_Ernie_TMTyeast_25ng_60min_R1.pepXML
 processed altogether 10667 results
INFO: Results written to file: C:\MS_TestRun\interact.pep.xml

  - C:\MS_TestRun\interact.pep.xml

  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

  - Building Commentz-Walter keyword tree...using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)
adding ACCMASS mixture distribution
using search_offsets in ACCMASS mixture distr: 0
init with X! Tandem stricttrypsin 
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ... 
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906281613-exported (Windows_NT-x86_64)) AKeller@ISB
 read in 0 1+, 8857 2+, 1396 3+, 414 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 1963 Decoys, and 8704 Non-Decoys
Iterations: .........10.........20......
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 27 iterations
INFO[11:26:28] Running the validation and inference on C:/MS_TestRun 
INFO[11:26:28] Executing ProteinProphet on C:/MS_TestRun    
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v6.0.0-rc15 Noctilucent, Build 202105101442-exported (Windows_NT-x86_64))
 (no FPKM) (using degen pep info)
Reading in C:/MS_TestRun/interact.pep.xml...
...read in 0 1+, 6020 2+, 840 3+, 44 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Initializing 6646 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating protein lengths and molecular weights from database c:/MS_TestRun/2021-11-15-decoys-contam-Saccharomyces_cerrevisiae_UP000002311_05202016_6749entries.fasta.fas
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........13000
.........:.........:.........:.........:.........:.........:.........:..  Total: 13728
Computing degenerate peptides for 1870 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Computing probabilities for 1966 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 1966 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 1966 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 1966 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 1966 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing 1706 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating sensitivity...and error tables...
Computing MU for 1966 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO: mu=2.16234e-05, db_size=12304840
INFO[11:26:32] Integrating peptide validation               
Running FPKM NSS NRS NSE NSI NSM Model EM:
Computing NSS values ... 

Creating 6 threads 
Wait for threads to finish ...
...... done
Computing NRS values ... 

Creating 6 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
Computing NSE values ... 

Creating 6 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
Computing NSI values ... 

Creating 6 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
Computing NSM values ... 

Creating 6 threads 
Wait for threads to finish ...
0--------------------------------------------------50------------------------------------------------100%
..................................................................................................... done
FPKM values are unavailable ... 
Iterations: ......done
INFO[11:26:36] Creating combined protein inference          
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v6.0.0-rc15 Noctilucent, Build 202105101442-exported (Windows_NT-x86_64))
 (no FPKM) (using degen pep info)
Reading in C:/MS_TestRun/interact.pep.xml...
...read in 0 1+, 5465 2+, 793 3+, 41 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.9

Initializing 6123 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating protein lengths and molecular weights from database c:/MS_TestRun/2021-11-15-decoys-contam-Saccharomyces_cerrevisiae_UP000002311_05202016_6749entries.fasta.fas
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........13000
.........:.........:.........:.........:.........:.........:.........:..  Total: 13728
Computing degenerate peptides for 1546 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Computing probabilities for 1629 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 1629 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 1629 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 1629 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing 1395 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating sensitivity...and error tables...
Computing MU for 1629 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO: mu=2.28031e-06, db_size=12304840
INFO[11:26:41] Protein inference results                     decoy=85 target=1310
INFO[11:26:41] Converged to 1.05 % FDR with 1144 Proteins    decoy=12 threshold=0.965 total=1156
2021/11/19 11:26:41 RemoveAll .: invalid argument

**Comment by fstein** [comment]
And here is the new parameter.yml fil
[philosopher.yml.txt](https://github.com/Nesvilab/philosopher/files/7569612/philosopher.yml.txt)
e:

**Comment by fstein** [comment]
Any idea what I might do wrong?

**Comment by fstein** [comment]
This is the output of the folder after running the pipeline command:
![image](https://user-images.githubusercontent.com/4124421/142858565-11b74db3-8a7f-4074-9778-062d6e6c9363.png)

**Comment by fstein** [comment]
I just realized, that the files combined.prot and combined.pep are the output of the "Integrated Reports:" step and all files of the intermediate steps are missing. So with the philosopher.yml file it runs the "Integrated Reports:" directly after the "Protein Inference:" step.
Is there a way to set the order of the steps? Or why is it skipping FDR Filtering, Label-Free Quantification, Isobaric Quantification and Individual Reports?
Thanks for your help.

Cheers,

Frank

**Comment by fstein** [comment]
I guess I found the solution myself. Looks like Integrated Reports with Abacus only work if one has multiple folders and not just a single one.

**Comment by prvst** [comment]
Hi @fstein As you noticed we recently pushed an update, and Sarah was investigating your issue. We're glad that you found the reason. Thanks for reaching out.

**Comment by fstein** [comment]
Dear @prvst, 
maybe it could be an option to have a bit more descriptive error message in this case. One could check if multiple folders were given as an argument and only then allow execution of the Integrated Reports steps by Abacus.
