### ISSUE TITLE
Filtered pep.xml in text format

### ISSUE THREAD

**Issue by GeorgesBed** [Nesvilab/philosopher#30]
To whom it may concern,
I am using philosopher in my pipeline and I think it is a very stable and useful tool. At the moment I am trying to process the filtered output of "philosopher filter" command and I need the data in a pep.xml format. However, the "filter" command stores the filtered pep.xml file in a binary format inside of the "workspace".

Could you help me convert the pepxml.bin inside the workspace (.meta folder) to a non binary format?

Thank you.

**Comment by prvst** [comment]
I'm glad you find our project useful.
The filter output is printed in text format as a table, can't you use that as input ? Are you planning to pass philosopher's output to another downstream analysis ?

**Comment by GeorgesBed** [comment]
Exactly, I am aligning the results back on the genome with a tool that requires a pepxml format as input.

**Comment by prvst** [comment]
The binary file you see inside the workspace doesn't actually holds the pepxml file itself, but the PSMs. I'm going to add your request to my todo list so it can be added to the program in a future release.

**Comment by GeorgesBed** [comment]
Thank you for considering this :)
