### ISSUE TITLE
label MS

### ISSUE THREAD

**Issue by XiaofengxBjmu** [Nesvilab/philosopher#300]
Hi there,
Is it possible to analysed SILAC or itraq4/8 samples with Philosopher?
If I get a Arg10, Lys8, Arg6, Lys4 SILAC Phosphoproteome data. Will the variable_mod be right?

> variable_mod01 = 15.994915 M 0 3 -1 0 0 0.0
> variable_mod02 = 79.966331 STY 0 3 -1 0 0 97.976896
> variable_mod03 = 42.010565 n 0 3 -1 0 0 0.0
> variable_mod04 = 4.025107 K 1 3 -1 0 0 0.0
> variable_mod05 = 6.020129 R 1 3 -1 0 0 0.0
> variable_mod06 = 8.014199 K 2 3 -1 0 0 0.0
> variable_mod07 = 10.008269 R 2 3 -1 0 0 0.0
> variable_mod08 = 0.0 X 0 3 -1 0 0 0.0
> variable_mod09 = 0.0 X 0 3 -1 0 0 0.0
> max_variable_mods_in_peptide = 5
> require_variable_mod = 0

Thank you very much in advance.

**Comment by prvst** [comment]
Hi @XiaofengxBjmu, you should redirect those questions to the Comet maintainers, we just distribute their program within our tools. You can reach out to them [here](https://github.com/UWPR/Comet)
