### ISSUE TITLE
Issue with pipeline LFQ

### ISSUE THREAD

**Issue by Naadir-Ganief** [Nesvilab/philosopher#323]
Hi, 

When using philosopher pipeline (in ubuntu 20.04) i get an error Cannot execute program during label free quant, when using bruker .d files from a timstof (using pasef in DDA).

I have used the same "philosopher.yml" with .mzML files with no issue. the only differences in the .yml file being changing the expected spectrum file format from .mzML to .d. and for theLFQ to use the raw file instead of .mzML.

I have attached the .yml as a text file, as well as the output from the terminal.

I am not sure what else to change?

Thanks

[pipeline_terminal_log.txt](https://github.com/Nesvilab/philosopher/files/8207533/pipeline_terminal_log.txt)
 

[philosopher.yml.txt](https://github.com/Nesvilab/philosopher/files/8207554/philosopher.yml.txt)

**Comment by prvst** [comment]
Hi @Naadir-Ganief, Philosopher does not support native Bruker files, convert them to mzML first.

**Comment by Naadir-Ganief** [comment]
okay, with msconvert? are there any preferred settings for philosopher?

Thanks

**Comment by prvst** [comment]
Yes, and I think that the default settings might be good for most cases, unless you have data acquired in some different ways.
