### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by prvst** [Nesvilab/philosopher#326]
### Discussed in https://github.com/Nesvilab/philosopher/discussions/325

<div type='discussions-op-text'>

<sup>Originally posted by **XiaofengxBjmu** March  9, 2022</sup>
Hello, 
I encountered such an error when I used philosoper pipeline to process CPTAC PDA phosphoproteome data, but there was no error when I used the same parameter to process CPTAC CCRCC phosphoproteome. 
Looking forward to your reply!

> time="11:02:57" level=info msg="Processing 13CPTAC_PDA_P_JHU_20191214_LUMOS_f08"
> time="11:03:19" level=info msg="Processing 13CPTAC_PDA_P_JHU_20191214_LUMOS_f09"
> time="11:03:40" level=info msg="Processing 13CPTAC_PDA_P_JHU_20191214_LUMOS_f10"
> time="11:04:02" level=info msg="Processing 13CPTAC_PDA_P_JHU_20191214_LUMOS_f11"
> time="11:04:23" level=info msg="Processing 13CPTAC_PDA_P_JHU_20191214_LUMOS_f12"
> time="11:04:45" level=info msg="Assigning intensities to data layers"
> time="11:04:45" level=info msg="Executing label-based quantification on 13CPTAC_PDA_Phosphoproteome_JHU_20191214/"
> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 1 [running]:
> philosopher/lib/uti.GetLabelNames(0xc45755, 0xe, 0x0)
>  /home/prvst/workspace/philosopher/lib/uti/uti.go:107 +0x36e
> philosopher/lib/qua.RunIsobaricLabelQuantification(0xc002eee600, 0x7a, 0xc3f7a7, 0x4, 0xc3f70f, 0x4, 0xc0000907e0, 0x69, 0xc00002d7f5, 0x3, ...)
>  /home/prvst/workspace/philosopher/lib/qua/qua.go:89 +0x1a47
> philosopher/lib/pip.LabelQuant(0xc000440000, 0x24, 0xc0000900e0, 0x69, 0xc000440030, 0x29, 0xc000338080, 0x78, 0xc000090150, 0x6f, ...)
>  /home/prvst/workspace/philosopher/lib/pip/pip.go:596 +0x4ca
> philosopher/cmd.glob..func13(0x894f1a0, 0xc00011d830, 0x1, 0x3)
>  /home/prvst/workspace/philosopher/cmd/pipeline.go:118 +0xa2c
> github.com/spf13/cobra.(*Command).execute(0x894f1a0, 0xc00011d7d0, 0x3, 0x3, 0x894f1a0, 0xc00011d7d0)
>  /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2aa
> github.com/spf13/cobra.(*Command).ExecuteC(0x894fc20, 0x0, 0x0, 0x0)
>  /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
> github.com/spf13/cobra.(*Command).Execute(...)
>  /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
> philosopher/cmd.Execute()
>  /home/</div>

**Comment by prvst** [comment]
@XiaofengxBjmu Looks like you forgot to assign an annotation file. Do you have one in that folder?

**Comment by XiaofengxBjmu** [comment]
My annotation file miss a TMT channel, thanks a lot!
