### ISSUE TITLE
Writing philosopher output automatically into log file

### ISSUE THREAD

**Issue by fstein** [Nesvilab/philosopher#327]
Hello,

would it be possible to automatically write the command line output into a log file? I know, that you could direct command line outputs into a file. However, I am starting the pipeline command from within the R environment. Here these strategies do not work as usual. Therefore, it would be great, if the output could be written automatically into a log file (maybe into the .meta folder?).

Thanks a lot for your consideration.

Best,
Frank

**Comment by prvst** [comment]
Hi @fstein, are you running the pipeline command ?

**Comment by fstein** [comment]
Yes.

**Comment by prvst** [comment]
The executing strings use the same parameters you see in the parameter file. If you want to run them "manually", or to have them as a record for your experiment, you can just use the same names and values from the parameter file.

**Comment by fstein** [comment]
I would be rather interested in the output of potential error messages which I cannot find in the parameter file. Or which parameter file are you referring to?

**Comment by fstein** [comment]
Thanks.
I would rather like to see the error output messages in some log file. In my case, the other members of the research group will start the philosopher pipeline with a batch file. If something goes wrong, they would come to me and I would like to retrace what could have happened. At this point, the command line ouptut is already closed and not saved anywhere and I do not have the chance to look at it unless I restart the whole pipeline again.

**Comment by prvst** [comment]
When running the pipeline via command line, I normally add a separate command at the end to capture all output. You can try adding ` >log.txt 2>&1` to the bash scripts, in the same pipeline execution command.

**Comment by fstein** [comment]
I managed to redirect the output into an extra txt file. However, one has to decide if one wants to display the output in the command line or write it to a file. I would like to have both. Therefore, it would be nice if philosopher could automatically write the command line output into a log file when using the pipeline command.

**Comment by prvst** [comment]
Good to know that you got the file. The current settings we have will print either to a terminal or a file if you redirect the output.
