### ISSUE TITLE
TMT6 quantification using pipeline command does not quantify correct channels

### ISSUE THREAD

**Issue by fstein** [Nesvilab/philosopher#330]
Hello,

I am using the pipeline command of philosopher as well as the philosopher.yml file for the quantification of TMT experiments. Everything works as expected. However, when setting the plex parameter to 6, it quantifies the wrong TMT channels. 
For labeling, I used the labels 126, 127N, 128C, 129N, 130C and 131N. When quantifying these labels by setting plex to 11, everything works as expected. However, when setting plex to 6, channels 128C and 129N are empty. Is it possible that channels 128N instead of 128C and 129C instead of 129N are quantified? Because they are empty indeed.

Here is how my annotation file looks like:
126 channel_126
127N channel_127N
128C channel_128C
129N channel_129N
130C channel_130C
131N channel_131N

Thanks a lot for looking into this.

Best,
Frank

PS: I am using the latest version of FragPipe, philosopher and MSFragger

**Comment by prvst** [comment]
Are the channels empty in all tables?

**Comment by prvst** [comment]
I actually found the issue, and you were right. We introduced a type in the channel names and swapped a couple of them. For you please use the tmt10 for outputting the values, and the fix will be available in the soon-to-be-release version. Thanks for finding and reporting that.

Fixed. Added to v4.2.1
