### ISSUE TITLE
Philosopher Filter not recognizing .pepxml?

### ISSUE THREAD

**Issue by tjlundgren** [Nesvilab/philosopher#332]
**Describe the bug**

I am trying to output unfiltered results with PeptideProphet score to .tsv to model the decoy distribution across all sample (similar to the sample_model.png already output per sample) and to look at low scoring spectra. When I change settings in FragPipe to include all PSMs, I get an error at the filter step... 
"FATA[17:40:58] Missing input file. you must provide a pepXML file or a folder with one or more files, Run 'philosopher filter --help' for more information "

When I look at the directory indicated in the filter command, I see a sample.pepxml. 

**To Reproduce**

1. Mass-offset search
2. PeptideProphet with --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel 2 --minprob 0 --accmass
3. ProteinProphet --maxppmdiff 2000000
4. Philosopher Filter with --sequential --razor --mapmods --prot 1 --psm 1 --ion 1 -- pep 1 --pepProb 0 --protProb 0 --models, Print decoys option selected in FragPipe GUI

**Expected behavior**

Regular .tsv outputs (specifically looking for psm.tsv) with all decoys and low scoring targets.

**Screenshots**

**Please complete the following information:**

 - OS: Windows
 - FragPipe Version: 17.1
 - Philosopher version: 4.1.0 (build 1635640020)

**Additional context**
This is following a MSFragger mass-offset search. I noticed an updated tooltip for the 'Report as variable mod' option in MSFragger suggested the PeptideProphet --accmass tag, which I had previously not been using. Adding this tag did not cause errors in the normally filtered results, but it is another setting I've changed recently before encountering this issue. 
Thank you in advance for your help,
FragPipe log:
[log_2022-03-28_17-40-58.txt](https://github.com/Nesvilab/philosopher/files/8383244/log_2022-03-28_17-40-58.txt)
First sample.pepxml:
[2021-06-18-ECL_Slot1-41_1_1711.zip](https://github.com/Nesvilab/philosopher/files/8383254/2021-06-18-ECL_Slot1-41_1_1711.zip)
Filter.log file for first sample:
[filter.log](https://github.com/Nesvilab/philosopher/files/8383257/filter.log)

**Comment by prvst** [comment]
I'm closing this one to avoid keeping duplicates
