### ISSUE TITLE
Asynchronous file reading issue with folders

### ISSUE THREAD

**Issue by prvst** [Nesvilab/philosopher#338]
According to [#635](https://github.com/Nesvilab/FragPipe/issues/635), the filtering fails because the interact file is in a sub-folder. I pinpointed the issue to the snippet below. Could you take a look for us?

https://github.com/Nesvilab/philosopher/blob/02cf8f1e6d0517d427ba31d08e302be84e8d07be/lib/id/pep.go#L412-L424

**Comment by prvst** [comment]
I noticed the different error message, somehow my debug can move further

**Comment by guoci** [comment]
@prvst can you show me the error message and send me the files used for testing?

**Comment by guoci** [comment]
Nothing to do with the parallel file reading, the cause is incorrect file paths.
Fixed at https://github.com/Nesvilab/philosopher/commit/da0019e249842653eba25a488d82e608d2c7c7e4

**Comment by prvst** [comment]
Good to know, thanks. Let's hope it will fix both behaviours.
