### ISSUE TITLE
Add flag to not check for new versions with every command

### ISSUE THREAD

**Issue by chhh** [Nesvilab/philosopher#34]
- checking for new version takes a long time in many cases
- needed in FragPipe
- FragPipe checks for philosopher updates once it starts up

**Comment by prvst** [comment]
Could you explain to me why FragPipe needs to have the update message with every command ? Initially we decided to not show that on every command because it wasn't necessary it it was causing some visual pollution.

**Comment by anesvi** [comment]
Useful to see what commands are executed, I always pay attention to that

**Comment by chhh** [comment]
@prvst I'm asking for the opposite. A flag to **NOT** check for updates. Every time Workspace, for example, is called through FragPipe there's a message that there's a new version of Philosopher on github.

**Comment by prvst** [comment]
It should only show up when there is a new version. If you are concerned with the message frequency, it will be reduced because I'm planning to do monthly releases instead of as it is now.

**Comment by chhh** [comment]
FragPipe checks the version once. I had problems with github because of constant version checking - sometimes I have to wait 10 seconds for every command to just start executing becuase the internet connection is flaky, sometimes I get some HTTPS errors from github. It shouldn't be hard to add a flag `--no-version-check` or something like that. It can even be hidden from the help screen.

**Comment by chhh** [comment]
Also, I just downloaded version `20190225` get "new version available" for every command, yet there is no newer version on github.

**Comment by anesvi** [comment]
I also get that warning for every comamnd

**Comment by prvst** [comment]
Its not hard at all, I'm just curious about the reason.

I'm aware of this new message about a new version that does not exists, it will be fixed. I had to add a test data to the release section, this is part of the addition of unit tests and continuous integration that I'm  implementing right now. With this, Philosopher will have continuous testing of its major functions and methods using real world data, any change in the results will raise a red flag.

**Comment by anesvi** [comment]
You can check just once, not every command. Also, when the  user starts FragPipe, they will get a message that there is new version

**Comment by prvst** [comment]
added, version 20190301

**Comment by chhh** [comment]
what's the new flag?

**Comment by prvst** [comment]
--nocheck
