### ISSUE TITLE
Update PeptideProphet

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/philosopher#347]
Dear Felipe,

I realized that the PeptideProphet version used by Philospher is from TPP v5.2.1-dev. Would it be possible to update this in a future release? This would be important to keep compatibility with more recent versions of comet (starting from the release 2020.01 the value for deltaCNstar was removed from the pep.xml files and therefore for results generated with newer comet versions no spectra are read in to the PeptideProphet analysis). The requirement of deltaCNstar was removed in TPP 6.0.

Best,
Juergen

http://comet-ms.sourceforge.net/release/release_202001/
http://tools.proteomecenter.org/wiki/index.php?title=TPP:6.0.0_Release_Notes

**Comment by prvst** [comment]
Hi Juregen. it is in our plans to update the prophets for the next release. We first need to evaluate if any of the changes and updates on PeptideProphet will affect our pipeline.
