### ISSUE TITLE
Philosopher updated but generated bugs. Can I get back Philosopher 4.1.1?

### ISSUE THREAD

**Issue by chuliangcui** [Nesvilab/philosopher#349]
Hi, 
I'm using FragPipe v17.1 for MassOffSet search. I updated Philosopher today then errors showed up:
```
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping
INFO[14:08:40] Protein inference results                     decoy=688 target=858
INFO[14:08:40] Converged to 0.93 % FDR with 70 Proteins      decoy=0 threshold=0.947 total=70

~~~~~~~~~~~~~~~~~~~~
Cancelling 8 remaining tasks
```
With Philosopher 4.1.1 before it worked with no errors.
Can I download version 4.1.1 again? I can't find the windows version in 4.1.1 folder.
Thanks.

**Comment by prvst** [comment]
Hi @chuliangcui. Coming back to an older version is never a good option. If you give me more information about what you're doing, what data you have, and how you're processing it, I can help you.

**Comment by chuliangcui** [comment]
Hi,

I put my files in the dropbox.

Input files are two .mzML

workflow is XRNAX-MassOffsetTsuiRNA, it contains all the parameters I used.

Database is 2022-03-14-decoys-contam-proteome_GB_NArm.fasta

Custom annotation file is unimod_20211122_RNAadductsAvK.

https://www.dropbox.com/sh/ejtvmbbmtjsps8a/AAA1wXrd-woGOY6a0QZMnsbsa?dl=0

Cheers,

Liangcui

**Comment by chuliangcui** [comment]
> Did you modify any of the current workflows? What kind of data you have and what kind of search are you doing?

Yes, I changed the workflow for mass offset following the XRNAX method:
https://fragpipe.nesvilab.org/docs/tutorial_custom_mass_offset.html
I added more masses: 
`# Workflow: XRNAX-MassOffsetTsuiWorks
crystalc.run-crystalc=true
database.decoy-tag=rev_
diann.fragpipe.cmd-opts=
diann.library=
diann.q-value=0.01
diann.quantification-strategy=0
diann.run-dia-nn=false
diaumpire.AdjustFragIntensity=false
diaumpire.BoostComplementaryIon=false
diaumpire.CorrThreshold=
diaumpire.DeltaApex=
diaumpire.ExportPrecursorPeak=false
diaumpire.Q1=false
diaumpire.Q2=false
diaumpire.Q3=false
diaumpire.RFmax=
diaumpire.RPmax=
diaumpire.RTOverlap=
diaumpire.SE.EstimateBG=false
diaumpire.SE.IsoPattern=
diaumpire.SE.MS1PPM=
diaumpire.SE.MS2PPM=
diaumpire.SE.MS2SN=
diaumpire.SE.MassDefectFilter=false
diaumpire.SE.MassDefectOffset=
diaumpire.SE.NoMissedScan=
diaumpire.SE.SN=
diaumpire.run-diaumpire=false
freequant.mz-tol=10
freequant.rt-tol=0.4
freequant.run-freequant=true
ionquant.excludemods=
ionquant.heavy=
ionquant.imtol=0.05
ionquant.ionfdr=0.01
ionquant.light=
ionquant.locprob=0.75
ionquant.maxlfq=1
ionquant.mbr=0
ionquant.mbrimtol=0.05
ionquant.mbrmincorr=0
ionquant.mbrrttol=1
ionquant.mbrtoprun=10
ionquant.medium=
ionquant.minexps=1
ionquant.minfreq=0.5
ionquant.minions=2
ionquant.minisotopes=2
ionquant.minscans=3
ionquant.mztol=10
ionquant.normalization=1
ionquant.peptidefdr=1
ionquant.proteinfdr=1
ionquant.requantify=1
ionquant.rttol=0.4
ionquant.run-ionquant=false
ionquant.tp=3
ionquant.writeindex=0
msbooster.predict-rt=true
msbooster.predict-spectra=true
msbooster.run-msbooster=false
msfragger.Y_type_masses=0 324.035867 306.025302 226.058971 244.069536 404.002198 94.016713 112.02727
msfragger.add_topN_complementary=0
msfragger.allowed_missed_cleavage_1=2
msfragger.allowed_missed_cleavage_2=2
msfragger.calibrate_mass=2
msfragger.clip_nTerm_M=true
msfragger.deisotope=1
msfragger.delta_mass_exclude_ranges=(-1.5,3.5)
msfragger.deneutralloss=1
msfragger.diagnostic_fragments=
msfragger.diagnostic_intensity_filter=0
msfragger.digest_max_length=50
msfragger.digest_min_length=7
msfragger.fragment_ion_series=b,y
msfragger.fragment_mass_tolerance=20
msfragger.fragment_mass_units=1
msfragger.intensity_transform=0
msfragger.ion_series_definitions=
msfragger.isotope_error=0/1/2
msfragger.labile_search_mode=off
msfragger.localize_delta_mass=true
msfragger.mass_diff_to_variable_mod=0
msfragger.mass_offsets=0 151.994 324.035871 306.025306 226.058973 385.991639 244.069538 404.002204 653.088394 635.077829 555.111496 715.044162 573.122061 733.054727 669.083308 651.072743 571.10641 731.039076 589.116975 749.049641 629.077161 611.066596 531.100263 691.032929 549.110828 709.043494 630.061177 612.050612 532.084279 692.016945 550.094844 710.02751 982.140917 964.130352 884.164019 1044.096685 902.174584 1062.10725 998.135831 980.125266 900.158933 1060.091599 918.169498 1078.102164 958.129684 940.119119 860.152786 1020.085452 878.163351 1038.096017 959.1137 941.103135 861.136802 1021.069468 879.147367 1039.080033 1014.130745 996.12018 916.153847 1076.086513 934.164412 1094.097078 974.124598 956.114033 876.1477 1036.080366 894.158265 1054.090931 975.108614 957.098049 877.131716 1037.064382 895.142281 1055.074947 934.118451 916.107886 836.141553 996.074219 854.152118 1014.084784 935.102467 917.091902 837.125569 997.058235 855.136134 1015.0688 936.086483 918.075918 838.109585 998.042251 856.12015 1016.052816 1242.111789 1224.101224 1144.134891 1304.067557 1162.145456 1322.078122 1281.13392 1263.123355 1183.157022 1343.089688 1201.167587 1361.100253 1359.178182 1341.167617 1261.201284 1421.13395 1279.211849 1439.144515 1241.127773 1223.117208 1143.150875 1303.083541 1161.16144 1321.094106 1280.149904 1262.139339 1182.173006 1342.105672 1200.183571 1360.116237 1319.172035 1301.16147 1221.195137 1381.127803 1239.205702 1399.138368 1240.143757 1222.133192 1142.166859 1302.099525 1160.177424 1320.11009 1279.165888 1261.155323 1181.18899 1341.121656 1199.199555 1359.132221 1239.159741 1221.149176 1141.182843 1301.115509 1159.193408 1319.126074 1265.139006 1247.128441 1167.162108 1327.094774 1185.172673 1345.105339 1304.161137 1286.150572 1206.184239 1366.116905 1224.194804 1384.12747 1343.183268 1325.172703 1245.20637 1405.139036 1263.216935 1423.149601 1264.15499 1246.144425 1166.178092 1326.110758 1184.188657 1344.121323 1303.177121 1285.166556 1205.200223 1365.132889 1223.210788 1383.143454 1263.170974 1245.160409 1165.194076 1325.126742 1183.204641 1343.137307 1288.166223 1270.155658 1190.189325 1350.121991 1208.19989 1368.132556 1327.188354 1309.177789 1229.211456 1389.144122 1247.222021 1407.154687 1287.182207 1269.171642 1189.205309 1349.137975 1207.215874 1367.14854 1311.19344 1293.182875 1213.216542 1373.149208 1231.227107 1391.159773 1320.156051 1302.145486 1222.179153 1382.111819 1240.189718 1400.122384
msfragger.max_fragment_charge=2
msfragger.max_variable_mods_combinations=5000
msfragger.max_variable_mods_per_peptide=3
msfragger.min_fragments_modelling=2
msfragger.min_matched_fragments=4
msfragger.minimum_peaks=15
msfragger.minimum_ratio=0.01
msfragger.misc.fragger.clear-mz-hi=0
msfragger.misc.fragger.clear-mz-lo=0
msfragger.misc.fragger.digest-mass-hi=5000
msfragger.misc.fragger.digest-mass-lo=500
msfragger.misc.fragger.enzyme-dropdown-1=stricttrypsin
msfragger.misc.fragger.enzyme-dropdown-2=null
msfragger.misc.fragger.precursor-charge-hi=4
msfragger.misc.fragger.precursor-charge-lo=1
msfragger.misc.fragger.remove-precursor-range-hi=1.5
msfragger.misc.fragger.remove-precursor-range-lo=-1.5
msfragger.misc.slice-db=1
msfragger.num_enzyme_termini=2
msfragger.output_format=pepXML
msfragger.output_max_expect=50
msfragger.output_report_topN=1
msfragger.override_charge=false
msfragger.precursor_mass_lower=-10
msfragger.precursor_mass_mode=corrected
msfragger.precursor_mass_units=1
msfragger.precursor_mass_upper=10
msfragger.precursor_true_tolerance=20
msfragger.precursor_true_units=1
msfragger.remove_precursor_peak=0
msfragger.report_alternative_proteins=true
msfragger.restrict_deltamass_to=all
msfragger.run-msfragger=true
msfragger.search_enzyme_cut_1=KR
msfragger.search_enzyme_cut_2=
msfragger.search_enzyme_name_1=stricttrypsin
msfragger.search_enzyme_name_2=null
msfragger.search_enzyme_nocut_1=
msfragger.search_enzyme_nocut_2=
msfragger.search_enzyme_sense_1=C
msfragger.search_enzyme_sense_2=C
msfragger.table.fix-mods=0.000000,C-Term Peptide,true,-1; 0.000000,N-Term Peptide,true,-1; 0.000000,C-Term Protein,true,-1; 0.000000,N-Term Protein,true,-1; 0.000000,G (glycine),true,-1; 0.000000,A (alanine),true,-1; 0.000000,S (serine),true,-1; 0.000000,P (proline),true,-1; 0.000000,V (valine),true,-1; 0.000000,T (threonine),true,-1; 57.021460,C (cysteine),true,-1; 0.000000,L (leucine),true,-1; 0.000000,I (isoleucine),true,-1; 0.000000,N (asparagine),true,-1; 0.000000,D (aspartic acid),true,-1; 0.000000,Q (glutamine),true,-1; 0.000000,K (lysine),true,-1; 0.000000,E (glutamic acid),true,-1; 0.000000,M (methionine),true,-1; 0.000000,H (histidine),true,-1; 0.000000,F (phenylalanine),true,-1; 0.000000,R (arginine),true,-1; 0.000000,Y (tyrosine),true,-1; 0.000000,W (tryptophan),true,-1; 0.000000,B ,true,-1; 0.000000,J,true,-1; 0.000000,O,true,-1; 0.000000,U,true,-1; 0.000000,X,true,-1; 0.000000,Z,true,-1
msfragger.table.var-mods=15.994900,M,true,2; 42.010600,[^,false,1; 79.966330,STY,false,3; -17.026500,nQnC,false,1; -18.010600,nE,false,1; 4.025107,K,false,2; 6.020129,R,false,2; 8.014199,K,false,2; 10.008269,R,false,2; 0.000000,site_10,false,1; 0.000000,site_11,false,1; 0.000000,site_12,false,1; 0.000000,site_13,false,1; 0.000000,site_14,false,1; 0.000000,site_15,false,1; 0.000000,site_16,false,1
msfragger.track_zero_topN=0
msfragger.use_all_mods_in_first_search=false
msfragger.use_topN_peaks=150
msfragger.write_calibrated_mgf=false
msfragger.zero_bin_accept_expect=0
msfragger.zero_bin_mult_expect=1
peptide-prophet.cmd-opts=--nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2
peptide-prophet.combine-pepxml=true
peptide-prophet.run-peptide-prophet=true
percolator.cmd-opts=--only-psms --no-terminate --post-processing-tdc
percolator.keep-tsv-files=false
percolator.run-percolator=false
phi-report.dont-use-prot-proph-file=false
phi-report.filter=--sequential --razor --prot 0.01 --mapmods
phi-report.pep-level-summary=false
phi-report.philosoher-msstats=false
phi-report.print-decoys=false
phi-report.prot-level-summary=true
phi-report.run-report=true
protein-prophet.cmd-opts=--maxppmdiff 2000000
protein-prophet.run-protein-prophet=true
ptmprophet.cmdline=
ptmprophet.run-ptmprophet=false
ptmshepherd.adv_params=false
ptmshepherd.annotation-common=false
ptmshepherd.annotation-custom=true
ptmshepherd.annotation-glyco=false
ptmshepherd.annotation-unimod=false
ptmshepherd.annotation_file=C\:\\Users\\Desktop\\MSFragger\\unimod_20211122_RNAadductsAvK.txt
ptmshepherd.annotation_tol=0.01
ptmshepherd.assign_glycans=false
ptmshepherd.cap_y_ions=324.035867 306.025302 226.058971 244.069536 404.002198 94.016713 112.02727
ptmshepherd.decoy_type=1
ptmshepherd.diag_ions=
ptmshepherd.glyco_adducts=
ptmshepherd.glyco_fdr=0.01
ptmshepherd.glyco_isotope_max=3
ptmshepherd.glyco_isotope_min=-1
ptmshepherd.glyco_mode=false
ptmshepherd.glyco_ppm_tol=50
ptmshepherd.glycodatabase=
ptmshepherd.histo_smoothbins=2
ptmshepherd.iontype_a=false
ptmshepherd.iontype_b=true
ptmshepherd.iontype_c=false
ptmshepherd.iontype_x=false
ptmshepherd.iontype_y=true
ptmshepherd.iontype_z=false
ptmshepherd.localization_allowed_res=
ptmshepherd.localization_background=4
ptmshepherd.max_adducts=0
ptmshepherd.n_glyco=true
ptmshepherd.normalization-psms=true
ptmshepherd.normalization-scans=false
ptmshepherd.output_extended=false
ptmshepherd.peakpicking_mass_units=1
ptmshepherd.peakpicking_minPsm=10
ptmshepherd.peakpicking_promRatio=0.3
ptmshepherd.peakpicking_width=3
ptmshepherd.precursor_mass_units=1
ptmshepherd.precursor_tol=10
ptmshepherd.print_decoys=false
ptmshepherd.prob_dhexOx=
ptmshepherd.prob_dhexY=
ptmshepherd.prob_neuacOx=
ptmshepherd.prob_neugcOx=
ptmshepherd.prob_phosphoOx=
ptmshepherd.prob_regY=
ptmshepherd.prob_sulfoOx=
ptmshepherd.remainder_masses=
ptmshepherd.remove_glycan_delta_mass=false
ptmshepherd.run-shepherd=true
ptmshepherd.spectra_maxfragcharge=2
ptmshepherd.spectra_ppmtol=20
ptmshepherd.varmod_masses=Failed_Carbamidomethylation\:-57.021464
quantitation.run-label-free-quant=false
run-psm-validation=true
speclibgen.easypqp.extras.max_delta_ppm=15
speclibgen.easypqp.extras.max_delta_unimod=0.02
speclibgen.easypqp.extras.rt_lowess_fraction=0.01
speclibgen.easypqp.im-cal=Automatic selection of a run as reference IM
speclibgen.easypqp.rt-cal=ciRT
speclibgen.easypqp.select-file.text=
speclibgen.easypqp.select-im-file.text=
speclibgen.keep-intermediate-files=false
speclibgen.run-speclibgen=false
tmtintegrator.add_Ref=-1
tmtintegrator.aggregation_method=0
tmtintegrator.allow_overlabel=true
tmtintegrator.allow_unlabeled=false
tmtintegrator.best_psm=true
tmtintegrator.channel_num=10
tmtintegrator.dont-run-fq-lq=false
tmtintegrator.groupby=-1
tmtintegrator.max_pep_prob_thres=0
tmtintegrator.min_ntt=0
tmtintegrator.min_pep_prob=0.9
tmtintegrator.min_percent=0.05
tmtintegrator.min_purity=0.5
tmtintegrator.min_site_prob=-1
tmtintegrator.mod_tag=none
tmtintegrator.ms1_int=true
tmtintegrator.outlier_removal=true
tmtintegrator.print_RefInt=false
tmtintegrator.prot_exclude=none
tmtintegrator.prot_norm=-1
tmtintegrator.psm_norm=false
tmtintegrator.quant_level=2
tmtintegrator.ref_tag=pool
tmtintegrator.run-tmtintegrator=false
tmtintegrator.top3_pep=true
tmtintegrator.unique_gene=0
tmtintegrator.unique_pep=false
workflow.description=Description not present
workflow.input.data-type.im-ms=false
workflow.input.data-type.regular-ms=true
workflow.saved-with-ver=17.1`

**Comment by chhh** [comment]
It seems like there are several issues with TMT in general and with version 4.2.1 in particular.
Version 4.2.1:
- Crashes at freequant for FAIMS mzML files:
```
FreeQuant [Work dir: D:\Project\ASD\Search_output_4\ASD_10pelx_fraction_10_-35]
C:\Software\fragpipe\tools\philosopher_v4.2.1_windows_amd64\philosopher.exe freequant --ptw 0.4 --tol 10 --dir E:\ASD\mzML_CV
panic: reflect: reflect.flag.mustBeAssignable using unaddressable value

goroutine 1 [running]:
reflect.flag.mustBeAssignableSlow(0x16)
	/usr/lib/go-1.13/src/reflect/value.go:247 +0x13f
reflect.flag.mustBeAssignable(...)
	/usr/lib/go-1.13/src/reflect/value.go:234
reflect.Value.Set(0xbab4c0, 0xc000166520, 0x16, 0xbab4c0, 0x0, 0x16)
	/usr/lib/go-1.13/src/reflect/value.go:1531 +0x42
github.com/vmihailenco/msgpack/v5.ptrValueDecoder.func1(0xc000327dd0, 0xbab4c0, 0xc000166520, 0x16, 0xbab4c0, 0xc000166520)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode_value.go:130 +0x103
github.com/vmihailenco/msgpack/v5.(*Decoder).DecodeValue(0xc000327dd0, 0xbab4c0, 0xc000166520, 0x16, 0xc000166520, 0x16)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:309 +0x93
github.com/vmihailenco/msgpack/v5.(*Decoder).Decode(0xc000327dd0, 0xb0ee60, 0xc00026a1e0, 0xc000296000, 0xc00030e090)
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:288 +0x1e5
philosopher/lib/sys.Restore(0xbab4c0, 0xc000166520, 0xc0002c53b0, 0xd, 0x0)
	/workspace/philosopher/lib/sys/sys.go:269 +0x235
philosopher/lib/rep.RestoreProtein(0xc000166520)
	/workspace/philosopher/lib/rep/io.go:79 +0xdd
philosopher/lib/rep.(*Evidence).RestoreGranular(0xc000166000)
	/workspace/philosopher/lib/rep/io.go:59 +0x79
philosopher/lib/qua.RunLabelFreeQuantification(0x0, 0x0, 0x0, 0x0, 0xc4ce46, 0x4, 0xc00001e360, 0x17, 0x0, 0x0, ...)
	/workspace/philosopher/lib/qua/qua.go:44 +0x7d
philosopher/cmd.glob..func6(0x2314f20, 0xc00007a8a0, 0x0, 0x6)
	/workspace/philosopher/cmd/freequant.go:46 +0x156
github.com/spf13/cobra.(*Command).execute(0x2314f20, 0xc00007a7e0, 0x6, 0x6, 0x2314f20, 0xc00007a7e0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2316c00, 0x456570, 0xc0000abf48, 0xc0000abf40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x34
main.main()
	/workspace/philosopher/main.go:25 +0x83
Process 'FreeQuant' finished, exit code: 2
```
- When I ran it with a single file, it complained about "Purity" column missing in "psm tables"
- Splitting FAIMS mzML files into separate files by CV doesn't help
- v4.1.1 also doesn't work for a single file
- But v4.1.1 works for multiple FAIMS files that have multiple CVs inside each mzML

**Comment by chhh** [comment]
Could you please bring back 4.1.1 while 4.2.1 is not fixed? This is breaking people's workflows.

**Comment by guoci** [comment]
@chhh That freequant issue was fixed at https://github.com/Nesvilab/philosopher/commit/95084a9129c8ffe174f86cb322c89e437c7906ed, after `4.2.1`

**Comment by chhh** [comment]
> @chhh `4.1.1` has the Thermo Raw file reader, which we recently discovered cannot be distributed with Philosopher, so `4.1.1` was deleted.

Oh, that is interesting - what was the problem with Philosopher and Thermo Raw reader?

**Comment by guoci** [comment]
@chhh As pointed out by @fcyu,
![image](https://user-images.githubusercontent.com/1260178/167180164-3bd3f160-1b75-48ec-b4ec-35a37b870cca.png)

**Comment by chhh** [comment]
> @chhh That freequant issue was fixed at [95084a9](https://github.com/Nesvilab/philosopher/commit/95084a9129c8ffe174f86cb322c89e437c7906ed), after `4.2.1`

@guoci Could you please provide some basic instructions how to build Philosopher? 4.2.2 is not in releases.
E.g. which go version is needed, how to generate Asset() function etc.

**Comment by prvst** [comment]
Hi Dmitry, please check the Wiki 
https://github.com/Nesvilab/philosopher/wiki/How-to-Build

**Comment by anesvi** [comment]
Thermo Raw reader cannot be included in a GPL licensed code

**Comment by prvst** [comment]
Please reopen if you have issues with the build

**Comment by chuliangcui** [comment]
Hi,

I put my files in the dropbox. 

Input files are two .mzML 

workflow is XRNAX-MassOffsetTsuiRNA, it contains all the parameters I used.

Database is 2022-03-14-decoys-contam-proteome_GB_NArm.fasta

Custom annotation file is unimod_20211122_RNAadductsAvK.

https://www.dropbox.com/sh/ejtvmbbmtjsps8a/AAA1wXrd-woGOY6a0QZMnsbsa?dl=0

Cheers,

Tsui
