### ISSUE TITLE
reprint output (abacus) - mislabeled columns

### ISSUE THREAD

**Issue by anesvi** [Nesvilab/philosopher#35]
Reprint formatted file generated by Abacus has the second annotation line incorrect
See below 
Bait and controls flipped. The second line should correspond to the first line, just stripping '_SPC' from the columns name
 
PROTID | CONTROL_1_SPC | CONTROL_2_SPC | HDAC5_1_SPC | HDAC5_2_SPC
na | CONTROL | HDAC5 | HDAC5 | CONTROL
P19474 | 164 | 20 | 200 | 153
Q9UQL6 | 0 | 0 | 179 | 201
P62258 | 4 | 7 | 175 | 87
P63104 | 2 | 8 | 88 | 33
P60709 | 21 | 55 | 86 | 15
P61981 | 1 | 2 | 81 | 25
P07437 | 19 | 53 | 80 | 60
P04264 | 370 | 186 | 77 | 116

**Comment by prvst** [comment]
fixed
