### ISSUE TITLE
Problem for quantification of TMT16 experiments

### ISSUE THREAD

**Issue by fstein** [Nesvilab/philosopher#350]
Hi,

using the new philosopher 4.2.1, I have some problems with TMT16. Almost all proteins in the protein.tsv output have a quantification value of 0 for the different TMT channels. 
When looking into the psm.tsv output, I see that psm's are quantified as aspected.
Also TMT channels are named as indicated in my annotation.txt file (channel_126	channel_127N	channel_127C	channel_128N	channel_128C	channel_129N	channel_129C	channel_130N	channel_130C	channel_131N	channel_131C	channel_132N	channel_132C	channel_133N	channel_133C	channel_134N).
However, when looking into the ion.tsv, channels names are wrong and having a "126" as a prefix before the correct channel name (now channel_126126	channel_126127N	channel_126127C	channel_126128N	channel_126128C	channel_126129N	channel_126129C	channel_126130N	channel_126130C	channel_126131N	channel_126131C	channel_126132N	channel_126132C	channel_126133N	channel_126133C	channel_126134N). 
This is also true for peptides.tsv and protein.tsv outputs. 
At least for the peptides.tsv and ion.tsv, I have quantified values. So quantification is only missing for protein.tsv output.
Is this information enough to identify a bug?

Or was I doing something wrong?
I am using the pipeline command of philosopher via the command line.

Thanks for looking into this.

Best,

Frank

**Comment by prvst** [comment]
Can you try running it again but this time without using the annotation file?

**Comment by fstein** [comment]
Don't you need the annotation file? Or is it just to name the columns?

**Comment by prvst** [comment]
Thee annotation file is just in case you want to rename the columns to something else besides the channel numbers. You can also rename them manually later if you prefer.

**Comment by fstein** [comment]
If I leave out the annotation file, I get an error:
Executing label-based quantification on xxx
FATA[...] Cannot read file. open annotation.txt: The system cannot find the file specified.

So apparently, it's not possible to run it without the annotation file :-(

There is definetly, a bug somewhere which was not there in the previous version and also does not appear with TMT11 quantification.

**Comment by fstein** [comment]
Here is the content of the annotation file:
126 channel_126
127N channel_127N
127C channel_127C
128N channel_128N
128C channel_128C
129N channel_129N
129C channel_129C
130N channel_130N
130C channel_130C
131N channel_131N
131C channel_131C
132N channel_132N
132C channel_132C
133N channel_133N
133C channel_133C
134N channel_134N

**Comment by fstein** [comment]
I just build our standard pipeline using the pipeline command of philosopher. As I understood, the command line interface for FragPipe is still in the development phase. Therefore, I would like to wait a bit before integrating it.

**Comment by fcyu** [comment]
Hi @fstein ,

Can you use FragPipe GUI first to make sure that everything is good. Then, you can switch to the headless mode if you want. 

ps. The FragPipe headless mode is using the same code base as the FragPipe GUI. There is no difference in terms of the way of running tools and the result files.

Best,

Fengchao

**Comment by fstein** [comment]
> Soon, maybe this month.

That's great. So I will move towards the headless version.

**Comment by fstein** [comment]
Apparently, TMT16 quantification also did not work without the phosphorylation. I am starting to believe that it's maybe something machine/raw file specific.

What kind of TMT quality filters do you apply for the signal? Do you remove something if it does not fullfill some QC filter?

Do you also remove "bleedthrough" from certain TMT channels to other channels due to chemical impurity of the labels? With the TMT order you get a product data sheet telling you the percentage of impurities which you can use to reduce signal intensity coming from wrong channels.

**Comment by anesvi** [comment]
You can see the filters in TMT-Integrator tab (Purity score, PSM with low intensity, etc.).

We do not apply isotope impurity correction in FragPipe

**Comment by prvst** [comment]
@fstein got your email, I'll reply with Alexey in copy. Best

**Comment by prvst** [comment]
closing this issue because the discussion moved to email.
