### ISSUE TITLE
RemoveAll .: invalid argument

### ISSUE THREAD

**Issue by prvst** [Nesvilab/philosopher#356]
### Discussed in https://github.com/Nesvilab/philosopher/discussions/355

<div type='discussions-op-text'>

<sup>Originally posted by **Bin-cc** May 11, 2022</sup>
Hi Philosopher group,

 Maybe we need a new discussion to discuss the error I haven't solved for several weeks. Here, I would like to describe the detials when I use Philosopher pipeline. And then, it will be useful for you to help me to resolve those problems.

- Firstly, I used Philosopher pipeline for [simple data analysis](https://github.com/Nesvilab/philosopher/wiki/Simple-Data-Analysis). I could run it successfully. But I found that if I used the Uniprot database contained reviewed+unreviewed proteins, it reported the error `Cannot read file. open .meta\db.bin: The system cannot find the file specified`. However, when I only changed the database and used reviewed Uniprot, I could complete it smoothly. 

1. So, the first question is whether I can use the reviewed and unreviewed protein database in Philosopher, and how? (I can use this database successfully in FragPipe)

- Secondly, I used Philosopher pipeline for [PPI analysis](https://github.com/Nesvilab/philosopher/wiki/REPRINT-Analysis) with the search engine MSFragger. I once ran it successfully with the Philosopher of version 3.4.13 with the search engine Comet. However, when I use the latest version of Philosopher and MSFragger, I always encounter the same problem `RemoveAll .: invalid argument`. I attached my [philosopher.yml](https://github.com/Nesvilab/philosopher/files/8671064/philosopher.txt) and [fragger.params](https://github.com/Nesvilab/philosopher/files/8671066/fragger.txt), and also the [Processing&error.txt](https://github.com/Nesvilab/philosopher/files/8671214/Processing.error.txt) I had used in philosopher.yml to find the reason but obviously I failed.

    I want to point out that I used the reviewed Uniprot database with decoys and contam which could run successfuly in 
    simple data analysis, and that while the error happened, the `combined.pep.xml` and `combined.prot.xml` had been producted.

2. So, the second question is what should I need to do next? Are there any details I ignored?

Thank you for your patience to read my questions. If you have any confusions about my description, please let me know. I really grateful that if you could help me to resolve those problems. Thanks!

All the best,
Bin

</div>

**Comment by prvst** [comment]
Let's go over both issues separately; the first one you report is the db.bin missing when you use a full database. I can assure you that the missing binary data has nothing to do with the fact you're including Tremble records into your database. The db.bin file is a binary representation of the database, it needs to be in place regardless of thee content. Are you getting that error with FragPipe or the pipeline?

**Comment by Bin-cc** [comment]
Thank you for your in time replying. I tried both FragPipe and Philosopher pipeline, and I only got the error in pipeline.

**Comment by prvst** [comment]
The pipeline needs the database in place before you start the analysis. If you're getting an error like that, then it means you're probably not running the program correctly. Make sure you have the target-decoy database ready to use before you launch the pipeline.

**Comment by Bin-cc** [comment]
I have done the same process for both the reviewed and reviewed+unreviewed Uniprot database before running pipeline. I added decoys and contaminants with the command
```
philosopher workspace --init 
philosopher database --custom <file_name> --contam
```
And I used the target-decoy database for later program.

**Comment by prvst** [comment]
Does your database contains target and decoys already? IF so, use the _annotate_ command, not the _custom_

**Comment by prvst** [comment]
Fixed. Added to v4.2.2

**Comment by Bin-cc** [comment]
Thanks! And how about my second question? Are there any solution for it? I have no idea about this problem.

Best

**Comment by Bin-cc** [comment]
Hi, 

I wonder if I can send a group of AP-MS data to you, so that I can eliminate the situation that the error is caused by my computer. Thank you for your patient instruction.

All the best

**Comment by prvst** [comment]
@Bin-cc, I added a fix to your issue. It will be available in the next release that will happen this or the following week.

**Comment by Bin-cc** [comment]
That's a good news. Thanks!
