### ISSUE TITLE
Database - Protein existence

### ISSUE THREAD

**Issue by f-huber** [Nesvilab/philosopher#357]
Dear Philosopher team, 

I am using philosopher (with Frapipe) with a custom fasta database. For a good compatibility, I format my fasta headers following uniprot format.
However, I noticed that when using a custom value in the "PE" field, it is not used in the annotation.
Therefore, I had a quick look at your code that parses databases (db.go) and I noticed that you only support pre-defined values (1, 2, 3, 4, 5) within "PE" and ignore other inputs.
Here is the code:
```
	if pem != nil {
		switch pem[1] {
		case "1":
			e.ProteinExistence = "1:Experimental evidence at protein level"
		case "2":
			e.ProteinExistence = "2:Experimental evidence at transcript level"
		case "3":
			e.ProteinExistence = "3:Protein inferred from homology"
		case "4":
			e.ProteinExistence = "4:Protein predicted"
		case "5":
			e.ProteinExistence = "5:Protein uncertain"
		}
	} else {
		e.ProteinExistence = ""
	}
```
I wonder if it would be possible to keep the value in "pem[1]" if it does not match any of the cases that you support?

With best regards,

Florian

**Comment by prvst** [comment]
Hi Florian. The protein existence level comes from the HUPO/neXtProt annotation. Are you using your own "existence" level annotation? Can you give me some examples?

**Comment by f-huber** [comment]
Hi @prvst,

Thanks for your quick reply. 
I am indeed using my own annotation which is simply some key words to describe different protein groups (PC, NC, VIRAL,..). 
I don’t know if using non-standard protein existence annotation would cause problems with philosopher - if not, I think that having the possibility to use non-standard annotation may be useful. If it is a problem, I fully understand; this is not a big issue. 

Thanks again and best,

Florian

**Comment by f-huber** [comment]
Thanks a lot, this is awesome!

**Comment by prvst** [comment]
Added to v4.2.2
