### ISSUE TITLE
"panic: Cannot execute program. there was an error with PeptideProphet"

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/philosopher#372]
I am running an open search pipeline with DIA-Umpire and MSFragger. I had previously generated the pseudo-DDA mzmL files from my GPF-DIA mzxml input files with DIA-Umpire, and was trying out some different search settings in MSFragger. I am getting an error and it crashes after MSFragger completes, when it tries to start PeptideProphet. 

I have the open search settings for PeptideProphet loaded, and the error is as follows below. I've also attached the full FragPipe log. I'm running on Windows 10 Enterprise, MSFragger v3.5, Philospher v4.4.0. 

Thanks,
Josh

"PeptideProphet [Work dir: H:\AdductomicsData\2022\220613\MSFragger\Output4]
C:\Users\jossmith\MSFragger\FragPipe-17.1\fragpipe\tools\philosopher\philosopher.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --nontt --nonmc --decoy rev_ --database C:\Users\jossmith\MSFragger\Philosopher\2022-01-15-decoys-reviewed-contam-UP000005640.fasta --combine JS-CS-220613_GroopmanJ_JS_PAA_1_NALCS2_2097_Q1.tsv JS-CS-220613_GroopmanJ_JS_PAA_1_NALCS2_2097_Q2.tsv JS-CS-220613_GroopmanJ_JS_PAA_1_NALCS2_2097_Q3.tsv JS-CS-220613_GroopmanJ_JS_PAA_1_P19_Q1.tsv JS-CS-220613_GroopmanJ_JS_PAA_1_P19_Q2.tsv JS-CS-220613_GroopmanJ_JS_PAA_1_P19_Q3.tsv JS-CS-220613_GroopmanJ_JS_PAA_2_NALCS2_2097_Q1.tsv JS-CS-220613_GroopmanJ_JS_PAA_2_NALCS2_2097_Q2.tsv JS-CS-220613_GroopmanJ_JS_PAA_2_NALCS2_2097_Q3.tsv JS-CS-220613_GroopmanJ_JS_PAA_2_P19_Q1.tsv JS-CS-220613_GroopmanJ_JS_PAA_2_P19_Q2.tsv JS-CS-220613_GroopmanJ_JS_PAA_2_P19_Q3.tsv JS-CS-220613_GroopmanJ_JS_PAA_3_NALCS2_2097_Q1.tsv JS-CS-220613_GroopmanJ_JS_PAA_3_NALCS2_2097_Q2.tsv JS-CS-220613_GroopmanJ_JS_PAA_3_NALCS2_2097_Q3.tsv JS-CS-220613_GroopmanJ_JS_PAA_3_P19_Q1.tsv JS-CS-220613_GroopmanJ_JS_PAA_3_P19_Q2.tsv JS-CS-220613_GroopmanJ_JS_PAA_3_P19_Q3.tsv
INFO[01:55:58] Executing PeptideProphet  v4.4.0             
panic: Cannot execute program. there was an error with PeptideProphet, please check your parameters and input files

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc0000e0070, 0x6c}, {0xf212c0, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.ExecutingBinary({0x10700c0?, 0xc000056000?}, {0xf212c0, 0x5})
	/workspace/philosopher/lib/msg/msg.go:209 +0x6e
philosopher/lib/ext/peptideprophet.interactParser({{0xc0000683c0, 0x5c}, {0xc000068420, 0x5b}, {0xc000292000, 0x62}, {0xc0000683c0, 0x5c}, {0xc000068420, 0x5b}, ...}, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:235 +0xb5e
philosopher/lib/ext/peptideprophet.PeptideProphet.Execute({{0xc0000683c0, 0x5c}, {0xc000068420, 0x5b}, {0xc000292000, 0x62}, {0xc0000683c0, 0x5c}, {0xc000068420, 0x5b}, ...}, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:86 +0x105
philosopher/lib/ext/peptideprophet.Run({{0xc0001805a0, 0x24}, {0xc0001805d0, 0x30}, {0xc0000217c0, 0x49}, {0xc00017bcc0, 0x3f}, {0xc00017bd00, 0x36}, ...}, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:67 +0x3d3
philosopher/cmd.glob..func12(0x24c1e20?, {0xc000120c00, 0x12, 0x20})
	/workspace/philosopher/cmd/peproph.go:26 +0xb4
github.com/spf13/cobra.(*Command).execute(0x24c1e20, {0xc000120400, 0x20, 0x20})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x24c2b40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
ERRO[01:56:03] Cannot execute program. there was an error with PeptideProphet, please check your parameters and input files "

[log_2022-07-26_01-56-03.txt](https://github.com/Nesvilab/philosopher/files/9191756/log_2022-07-26_01-56-03.txt)

**Comment by prvst** [comment]
Hi @jossmi. You're getting an error message because you should be passing .pepXML files to PeptideProphet, and not TSV files like you're doing.

**Comment by jossmi** [comment]
Duh, thanks. I had accidentally selected TSV only instead of TSV and Pepxml in MSFragger. Thanks for the quick fix!
