### ISSUE TITLE
Remove --raw flag since Philosopher does not support Thermo raw format

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#377]
In the `labelquant` help doc, there are
```
Usage:
  philosopher labelquant [flags]

Flags:
      --annot string      annotation file with custom names for the TMT channels
      --bestpsm           select the best PSMs for protein quantification
      --brand string      isobaric labeling brand (tmt, itraq)
      --dir string        folder path containing the raw files
  -h, --help              help for labelquant
      --level int         ms level for the quantification (default 2)
      --minprob float     only use PSMs with the specified minimum probability score (default 0.7)
      --plex string       number of reporter ion channels
      --purity float      ion purity threshold (default 0.5)
      --raw               read raw files instead of converted XML
      --removelow float   ignore the lower % of PSMs based on their summed abundances. 0 means no removal, entry value must be a decimal
      --tol float         m/z tolerance in ppm (default 20)
      --uniqueonly        report quantification based only on unique peptides
```

Felipe @prvst , can you remove `--raw` flag since Philosopher does not support Thermo raw format?

Thanks,

Fengchao

**Comment by prvst** [comment]
We initially left the tag to prevent breaking scripts & to let people know that the raw function is temporarily disabled. It prints a message in the terminal explaining that it's not available anymore.

**Comment by fcyu** [comment]
I don't think Philosopher will support Thermo raw format in the near future due to the license constrain. Why not just remove the tag? Is that too complicated to implement?

**Comment by prvst** [comment]
Sorry, implement what exactly?
We are evaluating an alternative right now that will allow the raw reading again. Besides, its good to have in place for some time for people to find the message. Later we can just hide it.
