### ISSUE TITLE
Parameter setting

### ISSUE THREAD

**Issue by JasonYJWei** [Nesvilab/philosopher#385]
Hi,

I'm running philosopher pipeline to do a TMT analysis. I have setup the parameters as following:
    search_enzyme_name_1: Trypsin                # Name of the first enzyme.
    search_enzyme_cut_1: KR                      # First enzyme's cutting amino acid.
    search_enzyme_nocut_1: P                     # First enzyme's protecting amino acid.
    allowed_missed_cleavage_1: 2                 # First enzyme's allowed number of missed cleavages per peptide. Maximum value is 5.
    search_enzyme_sense_1: C                     # First enzyme's cutting terminal.
    search_enzyme_name_2:                        # Name of the second enzyme.
    search_enzyme_cut_2:                         # Second enzyme's cutting amino acid.
    search_enzyme_nocut_2:                       # Second enzyme's protecting amino acid.
    allowed_missed_cleavage_2:                   # Second enzyme's allowed number of missed cleavages per peptide. Maximum value is 5.
    search_enzyme_sense_2: C                     # Second enzyme's cutting terminal.
    num_enzyme_termini: 2                        # 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion

but it report:
Parameter 'search_enzyme_name' was not supplied. Using default value: stricttrypsin
Parameter 'search_enzyme_cutafter' was not supplied. Using default value: KR
Parameter 'search_enzyme_butnotafter' was not supplied. Using default value:
Unknown parameters:
        allowed_missed_cleavage_1 = 0
        allowed_missed_cleavage_2 = 0
        search_enzyme_cut_1 =
        search_enzyme_cut_2 =
        search_enzyme_name_1 =
        search_enzyme_name_2 =
        search_enzyme_nocut_1 =
        search_enzyme_nocut_2 =
        search_enzyme_sense_1 =
        search_enzyme_sense_2 =

Even when I set it as:
    search_enzyme_name: trypsin                  # Name of enzyme to be written to the pepXML file.
    search_enzyme_cutafter: KR                   # Residues after which the enzyme cuts.
    search_enzyme_butnotafter: P                 # Residues that the enzyme will not cut before.
    num_enzyme_termini: 2                        # 0 for non-enzymatic, 1 for semi-enzymatic, and 2 for fully-enzymatic.
    allowed_missed_cleavage: 2                   # Allowed number of missed cleavages per peptide. Maximum value is 5.
    #search_enzyme_name_1: Trypsin                # Name of the first enzyme.
    #search_enzyme_cut_1: KR                      # First enzyme's cutting amino acid.
    #search_enzyme_nocut_1: P                     # First enzyme's protecting amino acid.
    #allowed_missed_cleavage_1: 2                 # First enzyme's allowed number of missed cleavages per peptide. Maximum value is 5.
    #search_enzyme_sense_1: C                     # First enzyme's cutting terminal.
    #search_enzyme_name_2:                        # Name of the second enzyme.
    #search_enzyme_cut_2:                         # Second enzyme's cutting amino acid.
    #search_enzyme_nocut_2:                       # Second enzyme's protecting amino acid.
    #allowed_missed_cleavage_2:                   # Second enzyme's allowed number of missed cleavages per peptide. Maximum value is 5.
    #search_enzyme_sense_2: C                     # Second enzyme's cutting terminal.
    #num_enzyme_termini: 2                        # 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion

it still said:
Parameter 'search_enzyme_name' was not supplied. Using default value: stricttrypsin
Parameter 'search_enzyme_cutafter' was not supplied. Using default value: KR
Parameter 'search_enzyme_butnotafter' was not supplied. Using default value:

So, could you please help me with this issue?

Thanks a lot.

**Comment by prvst** [comment]
Can you tell me the versions of Philosopher and Fragger?

**Comment by JasonYJWei** [comment]
> Can you tell me the versions of Philosopher and Fragger?

The Philosopher version is 4.4.0

**Comment by prvst** [comment]
and what about fragger?

**Comment by JasonYJWei** [comment]
> and what about fragger?

MSFragger-3.3 was used

**Comment by prvst** [comment]
That's the reason, you need to upgrade fragger to v3.5. Please reopen the ticket if you still have issues.

**Comment by JasonYJWei** [comment]
> That's the reason, you need to upgrade fragger to v3.5. Please reopen the ticket if you still have issues.

I see. Thanks a lot.
