### ISSUE TITLE
Cannot decode packed binary

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/philosopher#387]
Trying to process some files just to get pep.xml files and getting this error: 'ERRO[17:36:16] Cannot decode packed binary. read C:\TPP\data\Nathan\chx_cc_repeat\pepXMLs\milla009620: The handle is invalid.'

Here's the log.

Help me please?

Thanks in advance.

[log_2022-10-28_17-36-16.txt](https://github.com/Nesvilab/philosopher/files/9898845/log_2022-10-28_17-36-16.txt)

**Comment by prvst** [comment]
`Cannot decode packed binary. read C:\TPP\data\Nathan\chx_cc_repeat\pepXMLs\milla009620: The handle is invalid. `

The program cannot read what you're passing as input. Is that a folder or a file?

**Comment by ndtivendale** [comment]
A folder. This is what is in the folder
![image](https://user-images.githubusercontent.com/54612207/199129769-e24e2c85-a664-43aa-9720-ef79fb88527d.png)

**Comment by prvst** [comment]
try passing the `interact.pep.xml` file instead

**Comment by ndtivendale** [comment]
How do I do that?

**Comment by prvst** [comment]
pass the file path to the program.

**Comment by ndtivendale** [comment]
I am sorry, I do not understand what you mean. Where in FragPipe can I specify the file path to the interact file?

**Comment by ndtivendale** [comment]
And why would I need to specify the interact file? I have not had to do that before.

**Comment by prvst** [comment]
Did some digging on the error, and it could be related to your setup, but I'm not entirely sure, we never got it before. Can you describe which workflow are you running? What kind of computer you have, and what kind of analysis are you trying to do?

**Comment by ndtivendale** [comment]
Here is the workflow file and a screenshot of the computer information.
I am just trying to generate a combined interact.pep.xml file that I can feed into an in-house pipeline.
 
[CHX_pep_xml_generation.workflow.pdf](https://github.com/Nesvilab/philosopher/files/9934174/CHX_pep_xml_generation.workflow.pdf)
![Screenshot 2022-11-04 091519](https://user-images.githubusercontent.com/54612207/199864795-a50fc013-12b8-408c-891a-27c15a9d85ed.png)

**Comment by prvst** [comment]
I have no idea what triggered the error, first time I see this message. I don't have a solution for you, I suggest you clean the directories, remove temporary files, get updated versions of all software, and try again.

**Comment by ndtivendale** [comment]
OK. I will give that a try.

**Comment by ndtivendale** [comment]
I did all of your suggestions and I'm still getting the same error.

**Comment by ndtivendale** [comment]
Earlier in the run, I get these kind of warnings:

Process 'CheckCentroid' finished, exit code: 0
WorkspaceCleanInit [Work dir: C:\data\Nathan\cc_CHX_repeat\pepXMLs\CHX_cc_t0_1]
C:\data\Nathan\FragPipe-jre-18.0\fragpipe\tools\philosopher_v4.4.0_windows_amd64\philosopher.exe workspace --clean --nocheck
Process 'WorkspaceCleanInit' finished, exit code: 0
INFO[08:10:37] Executing Workspace  v4.4.0                  
INFO[08:10:37] Removing workspace                           
**WARN[08:10:37] Cannot read file. open .meta\meta.bin: The system cannot find the path specified.** 
INFO[08:10:37] Done           

Could that have something to do with it?

**Comment by ndtivendale** [comment]
My colleague and I determined the source of the problem. The program was mistaking the directory for the pepxml file because I had named the output directory 'pepXMLs'. I changed the name of the output directory and now it works fine.
