### ISSUE TITLE
Multi-experiment report, intensities missing 

### ISSUE THREAD

**Issue by anesvi** [Nesvilab/philosopher#39]
When using multi-experiment report, with label-free intensities option, combined_peptide.tsv file is missing intensity data (only spectral counts). The protein report (combined_protein.tsv) is OK, both intensities and spectral counts are there.

In the future, it would also be nice to generate reprint.tsv with intensities as well (as a separate file). E.g., when intensity data is available, there will be reprint_spc.tsv and reprint_int.tsv. Otherwise just reprint_spc.tsv

**Comment by prvst** [comment]
The intensity for the combined peptide report was not added yet, but I'll add it to my To Do list.
