### ISSUE TITLE
Importing TMTIntegrator parameter file

### ISSUE THREAD

**Issue by Yonghao-Holden** [Nesvilab/philosopher#390]
Hello, I'm trying to run the philosopher TMT pipeline analysis and got this error as followed saying that my parameter setting file for TMTIntegrator is not present:

```
time="17:13:35" level=info msg="Processing intensities"
time="17:13:40" level=info msg="Running TMT-Integrator"
TMT-Integrator v4.0.2
Exception in thread "main" java.io.FileNotFoundException: /scratch/yliang/HNSCC/data/CPTAC/test1/MassSpec_CPTAC_PDC000221_HNSCC_mini_bluemoon_integrator/philosopher.yml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at TMTIntegrator.LoadParam(TMTIntegrator.java:174)
	at TMTIntegrator.main(TMTIntegrator.java:29)
time="17:15:53" level=info msg=Done
```

Following is the folder structure I have and I have the philosopher.yml file in the params folder. However, I think TMTIntegrator is trying to read the philosopher in the current folder instead of in the params folder as instructed by the wiki.
```
yliang@chimay:/scratch/yliang/HNSCC/data/CPTAC/test1/MassSpec_CPTAC_PDC000221_HNSCC_mini_bluemoon_integrator$ ll /scratch/yliang/HNSCC/data/CPTAC/test1/MassSpec_CPTAC_PDC000221_HNSCC_mini_bluemoon_integrator
total 316M
   0 drwxrwxr-x 3 yliang yliang   66 Nov 14 17:01 01CPTAC_HNSCC_W_JHU_20190507/
   0 drwxrwxr-x 3 yliang yliang   66 Nov 14 17:02 02CPTAC_HNSCC_W_JHU_20190513/
1.0K -rw-rw-r-- 1 yliang yliang  24M Nov 14 17:10 combined_peptide.tsv
289M -rw-rw-r-- 1 yliang yliang 1.4G Nov 14 15:11 combined.pep.xml
1.0K -rw-rw-r-- 1 yliang yliang 2.1M Nov 14 17:13 combined_protein.tsv
 28M -rw-rw-r-- 1 yliang yliang 182M Nov 14 15:13 combined.prot.xml
   0 drwxrwxr-x 2 yliang yliang    1 Nov 11 13:47 params/
   0 -rw-rw-r-- 1 yliang yliang    0 Nov 14 10:50 PDC000221_HNSCC_mini.err
133K -rw-rw-r-- 1 yliang yliang 134K Nov 14 17:15 PDC000221_HNSCC_mini.log
```

When I looked into the code in the pipeline where it calls TMTIntegrator, it seems like it's indeed calling the philosopher.yml file in the current folder instead of the params folder as instructed by the wiki. 

https://github.com/Nesvilab/philosopher/blob/f6bab636a1916be5cf1753f8a70e40821aefffee/lib/ext/tmtintegrator/tmtintegrator.go#L85

I'm not sure whether the philosopher.yml file TMTIntegrator is using the same as the one what the philosopher TMT pipeline is using. If it's, is it possible to edit the pipeline so that I can automatically take the philosopher.yml file from the ./params folder? 

Thank you ahead for your help!
Holden

**Comment by prvst** [comment]
which version are you using ?

**Comment by Yonghao-Holden** [comment]
I'm using philosopher_v4.4.0_linux_amd64.zip and TMTIntegrator_v4.0.2.jar.

**Comment by Yonghao-Holden** [comment]
After putting philospher.yml in the folder, and re-running the pipeline, I got a warning message saying that:

`time="01:49:54" level=info msg="Processing combined file"
time="01:50:16" level=info msg="Converged to 1.01 % FDR with 10941 Proteins" decoy=110 threshold=0.9913 total=11051
time="01:50:38" level=info msg="Restoring protein results"
time="01:52:30" level=info msg="Processing spectral counts"
time="01:52:33" level=info msg="Processing peptide counts"
time="01:52:41" level=info msg="Processing intensities"
time="01:52:44" level=info msg="Running TMT-Integrator"
TMT-Integrator v4.0.2
TMT-Integrator can't find the reference channel. Please check if the reference tag is correctly defined in the parameter file.
time="01:52:46" level=info msg=Done`

It seems like the philopher.yml file TMTIntegrator is looking for is not the same as the one Philosopher is looking for?

**Comment by prvst** [comment]
The message from TMT-Integrator means you are asking for an analysis using a reference channel, but the program cannot find it. If you wish to use a channel as a reference for normalization, you have to put the channel label in the proper field in the TMT-I parameter file.
