### ISSUE TITLE
Can't download Philosopher

### ISSUE THREAD

**Issue by ZhangXiangye** [Nesvilab/philosopher#392]
Hi, 
I'm sorry to bother you, but when we come to download the philosopher, it does not work.
1. Go to 'FragePipe v18.0'
2. Click on 'Philosopher -Download/update- Automatically ' 
3. See error:
java.lang.IllegalStateException: Did not find supported download links on the page
	at com.dmtavt.fragpipe.tools.philosopher.Philosopher.downloadPhilosopherAutomatically(Philosopher.java:226)
	at com.dmtavt.fragpipe.tabs.TabConfig.lambda$actionPhilosopherDownload$28(TabConfig.java:1206)
	at java.base/java.lang.Thread.run(Unknown Source)

4. When we click the manually, we can't find the right place to download.

Could you please give me some advice?

**Comment by prvst** [comment]
Fragpipe pulls the binary from Github, but recent changes in the website made the download option in the program to fail. There'll probably be a fix for the issue in the next FragPipe release. In the meantime, you can download Philosopher from the repo.
