### ISSUE TITLE
Cannot decode packed binary. strconv.ParseUint: parsing "66601": value out of range

### ISSUE THREAD

**Issue by ArthurViode** [Nesvilab/philosopher#398]
**Describe the bug**

Philosopher is returning the following error : 
Cannot decode packed binary. strconv.ParseUint: parsing "66601": value out of range 

INFO[10:23:57] Executing Filter  v4.4.0                     
INFO[10:23:57] Processing peptide identification files      
INFO[10:23:57] Parsing sample\interact-sample.pep.xml 
ERRO[10:23:57] Cannot decode packed binary. strconv.ParseUint: parsing "66601": value out of range 

**Please complete the following information:**

 - OS: Windows 10
 - Version: Philosopher version: 4.4.0

**Additional context**

I am trying to do a search with a custom fasta file with more than 100 000 entries.
Thanks a lot for your help!

**Comment by prvst** [comment]
Based on what you are describing, it looks like your data is reaching out a limit on a variable. Go is a strongly typed language. Send me your interact files and I can see which one needs change.

**Comment by prvst** [comment]
Please upload [here](https://www.dropbox.com/request/4QSiasPciiRUWwueyoX8)

**Comment by ArthurViode** [comment]
Thanks! I have uploaded one file. Let me know if you want more files.

Best,

Arthur

**Comment by prvst** [comment]
Added to v4.7.0
