### ISSUE TITLE
Philosopher does not allow certain characters in Gene names

### ISSUE THREAD

**Issue by fstein** [Nesvilab/philosopher#407]
Dear Felipe,

With the new philosopher version 4.8.1, I got the following error:

The proteion record [tr|Q1RMN8|Q1RMN8_BOVIN Immunoglobulin light chain, lambda gene cluster OS=Bos taurus GN=IGL@ PE=2 SV=1] contains an unsupported character: @. Please remove it before running philosopher again 
Process 'PhilosopherDbAnnotate' finished, exit code: 2
Process returned non-zero exit code, stopping

This error did not occur with previous versions. And IGL@ is indead the correct gene name (see here: https://www.uniprot.org/uniprotkb/Q1RMN8/entry). 

Thanks for taking care of this.

Best,

Frank

**Comment by prvst** [comment]
Thanks for letting me know that. The reason is because IonQuant can't handle @ in FASTA headers. If there's genes names with @, then IonQuant needs to be fixed. I'll push it forward to FragPipe issue, and I'll plan to revert this in the next release.

**Comment by prvst** [comment]
Removed. Added to v4.9.2
