### ISSUE TITLE
I/L corrected peptides are not present in the reports.

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#409]
There are peptides not in the fasta file. I think this bug is due to the incorrect `I` and `L` switch. 

All files to reproduce the bug can be found from https://www.dropbox.com/sh/k9vct7es422b1lj/AABoN5n9aH4kMbdIqBp-JwOva?dl=0

Following are the example peptides:

CSELWDR
TCELDAR
DAELIAK
LDDILER
ELIASIK

Best,

Fengchao

**Comment by prvst** [comment]
You mean that the peptides from above do not exist in the FASTA file as they are? A quick search shows them mapping to decoy proteins.

**Comment by prvst** [comment]
Similar to #430. Closing to avoid redundancy.
