### ISSUE TITLE
Philosopher 4.8.1: there are decoy proteins in the `protein` column of `psm.tsv`

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#410]
Following is the screenshot of the `psm.tsv`

![image](https://user-images.githubusercontent.com/6926299/215352071-814c8db6-ee93-4edc-af98-47009a352fd6.png)

All files to reproduce the bug can be found from https://www.dropbox.com/sh/nfgv3w2er70snf3/AABjrd_DLmy92nmmVyx6htwNa?dl=0 . Since it is from an unpublished data, the above link is only accessible to Felipe @prvst .

Thanks,

Fengchao

**Comment by prvst** [comment]
Thanks for reporting. Fixed. Added to v4.8.2.
