### ISSUE TITLE
Error: Cannot decode packed binary. strconv.ParseInt: parsing "63781": value out of range 

### ISSUE THREAD

**Issue by ArthurViode** [Nesvilab/philosopher#412]
Hi,
I am having parsing problems see below: 
anic: Cannot decode packed binary. strconv.ParseInt: parsing "63781": value out of range

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xcd8c225140, 0x52}, {0xfe0dd5, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0x115a3e0?, 0xd733d1b680?}, {0xfe0dd5, 0x5})
	/workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/spc.(*ProtXML).Parse(0xc0c29dd910, {0xc0000281e0, 0x45})
	/workspace/philosopher/lib/spc/spc.go:97 +0x210
philosopher/lib/id.(*ProtXML).Read(0xc0c29ddbb8, {0xc0000281e0?, 0x2bd3320?})
	/workspace/philosopher/lib/id/pro.go:116 +0x85
philosopher/lib/fil.ReadProtXMLInput({0xc0000281e0?, 0xd?}, {0xc00001c140, 0x4}, 0x3ff0000000000000)
	/workspace/philosopher/lib/fil/fil.go:504 +0x9f
philosopher/lib/fil.Run({{0xc000020780, 0x24}, {0xc000028730, 0x4e}, {0xc000028780, 0x46}, {0xc0000e02a0, 0x5d}, {0xc0000e0300, 0x54}, ...})
	/workspace/philosopher/lib/fil/fil.go:81 +0x77a
philosopher/cmd.glob..func5(0x2bdd9c0?, {0xfe0615?, 0xa?, 0xa?})
	/workspace/philosopher/cmd/filter.go:43 +0x390
github.com/spf13/cobra.(*Command).execute(0x2bdd9c0, {0xc000276c80, 0xa, 0xa})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2bdc2c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
[log_2023-02-03_14-57-52.txt](https://github.com/Nesvilab/philosopher/files/10582363/log_2023-02-03_14-57-52.txt)

	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
ERRO[14:42:19] Cannot decode packed binary. strconv.ParseInt: parsing "63781": value out of range 
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping

thanks a lot for your help,
Best,
Arthur

**Comment by prvst** [comment]
how big is your database?

**Comment by ArthurViode** [comment]
787476 entries including decoys and contaminants.

**Comment by prvst** [comment]
Can you please share the prot.xml file?

**Comment by ArthurViode** [comment]
The combined.prot.xml is 111 GB what would be the easiest way to share it ? 
thanks

**Comment by prvst** [comment]
any cloud service that you have access is fine to me.

Are you working with a metaproteomics experiment?

**Comment by prvst** [comment]
@ArthurViode I can't open or properly inspect your file, it's just too big (I have a 16 core i7-9800X 4Ghz CPU, and 32 GB RAM machine). The reason for this is that one or more fields from the file have values that are larger than what the program can hold them, and I don't have a way right now to figure it out which variable is overflowing. What I can tell you is that you might need a different approach to your problem. I noticed that some of the protein groups have multiple thousands of alternative proteins (if not more!). Even if the program was able to properly parse your data, you'll end up with a file that cannot be opened by any spreadsheet program, and with peptides or proteins having thousands and thousands of alternative identifications or mappings, meaning that it's virtually impossible to for any algorithm to tell you which protein was detected with confidence.

**Comment by anesvi** [comment]
I agree. Arthur what you are doing is not a common scenario so you should probably contact us directly and explain your project. Then we can see if we can suggest something, like a different strategy,  or implement a fix, if that is feasible (e.g. as a collaboration)
Best
Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArthurViode** [comment]
Hi Felipe and Alexey,
thanks a lot for your help. We will be happy to have a meeting with you, I will send an email around.
Best,
Arthur
