### ISSUE TITLE
cannot serialize data structures

### ISSUE THREAD

**Issue by KunathBJ** [Nesvilab/philosopher#42]
Hello,
I'm using FragPipe with the splicing database option. The splicing works to some extend but soon after I get an error saying that it cannot serialize data structures. 

```
ReportDbAnnotate [Work dir: E:\LAO\D17Test resulst\msfraggersplice]
C:\Software\MSFragger\philosopher_windows_amd64.exe database --annotate E:\LAO\Db_Fra_Clust99_A0_Decoy.fasta --prefix rev_
INFO[10:05:38] Executing Database 20190226                  
INFO[10:05:38] Processing database                          
FATA[10:10:47] cannot serialize data structures: short write 
Process 'ReportDbAnnotate' finished, exit code: 1

Process returned non-zero exit code, stopping
PeptideProphet [Work dir: E:\LAO\D17Test resulst\msfraggersplice]
C:\Software\MSFragger\philosopher_windows_amd64.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database E:\LAO\Db_Fra_Clust99_A0_Decoy.fasta 052313-SludgeD17_25-30.pepXML
~~~~~~~~~~~~~~~~~~~~
Stopping 10/20 processes (10 already finished)
Processing interrupted, stopping PeptideProphet
```
Here are some information on my system
**System info:**
    OS and version: Windows 10 enterprise
    java version "1.8.0_202"
    Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
    Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
**Input data files**
   6 mzML file of 2Gb each. Converted from raw files using msconvert.
**Sequence database**
    Metagenomic database of 2.5Gb size (counting decoy)
The entries in the database look all like this:
 >D01_contig_gene2_1
 >rev_1 (decoy)
I just realized that the decoy software sometimes produce a * at the beginning of the sequence.

Any idea? I've also attached the complete log from FragPipe.
Thanks a lot for your help,

Ben
[log_2019-03-05_12-32-57.txt](https://github.com/Nesvilab/philosopher/files/2933439/log_2019-03-05_12-32-57.txt)

**Comment by prvst** [comment]
@KunathBJ 
Can you send me this database to take a look ?

**Comment by KunathBJ** [comment]
Sure!
I put it in a google drive folder. Where can I send you the link?

**Comment by prvst** [comment]
felipevl@umich.edu

**Comment by KunathBJ** [comment]
Hey Felipe,

Did you have time to have a look at the Db?? You received my email??
Thanks a lot,

Ben

**Comment by prvst** [comment]
@KunathBJ 

I downloaded your database and tried to process it with Philosopher, unfortunately the file is too big, I had to kill the process after reaching almost 60GB of RAM usage. With decoys your database will have almost 27 million entries, I don;t think that MSFragger or any other search tool would perform well with such a search space.

**Comment by prvst** [comment]
I just noticed that you already have decoys, but still, that is a extremely large search space with 13 million entries in your database.

**Comment by KunathBJ** [comment]
Oki. Thanks a lot for trying :)

Ben
