### ISSUE TITLE
contaminant peptide in my result

### ISSUE THREAD

**Issue by qianqli** [Nesvilab/philosopher#425]
**If you have a question, and not a bug**

Please use the Discussions board instead of the Issue tracking system.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qianqli** [comment]
Dear author, I have a problem when I use Frapipe for human phosphoproteomics analysis: in the STY report file, there are peptides from rabbits and there is no feature to filter the peptides in this file. one of the peptide is like this: index: P00883_S36, Gene: ALDOA, protein:sp|P04075|ALDOA_human, Protein_ID: P00883, peptide:GILAADEsTGSIAK, BestbLocalization Probability: 0.97, Sanple Probability: 0.977, Sample Intensity:140611472. Please check the problem here.

**Comment by anesvi** [comment]
Could you please clarify. Is this peptide sequence present in both a human protein and a rabbit protein? If so, why do you want to eliminate it?

**Comment by prvst** [comment]
no response.
