### ISSUE TITLE
Adjust `I` and `L` in the psm.tsv, peptide.tsv, and ion.tsv after razor assignment

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#430]
The razor assignment might make an alternative protein as the razor protein. Since we don't distinguish `I` and `L` in the protein mapping, some peptides might not exist in their razor protein. Need to change some `I` to `L`, or `L` to `I` after razor assignment, so that the peptides in the tsv files are correct.

Best,

Fengchao

**Comment by fcyu** [comment]
@prvst Has this bug been fixed after version 4.8.1? If yes, could you share the fixed version with @hollenstein ?

Thanks,

Fengchao

**Comment by hollenstein** [comment]
Hi, I've tested it with the FP 19.2-RC and philosopher v5.0.0-RC18 and the I / L issue is still present.

Best,
David

**Comment by hollenstein** [comment]
Hi, just wanted to mention that the issue still exists in the current version of FragPipe (Philosopher 5.1.1)

This time we observed a peptide sequence that only exists in a decoy protein.

Best,
David

**Comment by fcyu** [comment]
Fixed in https://github.com/Nesvilab/philosopher/pull/517

Huge thanks to @hollenstein 

Best,

Fengchao
