### ISSUE TITLE
Philosopher - non-zero exit code

### ISSUE THREAD

**Issue by brunoalex7** [Nesvilab/philosopher#433]
Hi. I'm new to Fragpipe, I was actually just testing it for the first time using a couple of samples in closed search.

I got a few warnings such as this one (for protein sequences containing U):

.WARNING: Found the following zero-mass residues in protein entry sp|O62768|TRXR1_BOVIN : U
MNGSKDLPEPYDYDLIIIGGGSGGLAAAKEAAKYDKKVMVLDFVTPTPLGTRWGLGGTCVNVGCIPKKLMHQAALLGQALRDSRNYGWNVEETVKHDWERMTEAVQNHIGSLNWGYRVALREKKVTYENAYGEFVGPHRIKATNNKGKEKIYSAERFLIATGERPRYLGIPGDKEYCISSDDLFSLPYCPGKTLVVGASYVALECAGFLAGIGLDVTVMVRSILLRGFDQDMANKIGEHMQEHGIKFIRQFVPIKVEQIEAGTPGR

I'm not sure whether this relates or not, but in the end I got a non-zero exit code.
You can find the full log attached.

[log_2023-05-03_14-56-23.txt](https://github.com/Nesvilab/philosopher/files/11383234/log_2023-05-03_14-56-23.txt)

Can you help?
Thanks,
Bruno

**Comment by AimeeD90** [comment]
Hi @brunoalex7 ,

Can you share 2023-05-02-decoys-UniMS50_51_Human+Bovine+Vaccinia+Contaminants.fasta.fas with us? It will enable us to debug this error for you.

Thanks,
Yamei

**Comment by fcyu** [comment]
I am closing this issue because there is no response from the user.

**Comment by brunoalex7** [comment]
Hi. I am sorry for the late reply. I am attaching the database.
thank you,
Bruno
