### ISSUE TITLE
Non-English characters in the folder name break ProteinProphet

### ISSUE THREAD

**Issue by hongweizhao1** [Nesvilab/philosopher#434]
- Describe theI have the following problem while running issue or question:

- Upload your log
[log.txt](https://github.com/Nesvilab/FragPipe/files/11521857/log.txt)
 file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by assafkacen** [comment]
read message

**Comment by hongweizhao1** [comment]
sir can you reply  to me in more detail  I have read some but I still have no choice to solve

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/philosopher/issues/435 and https://github.com/Nesvilab/FragPipe/issues/1107

Best,

Fengchao
