### ISSUE TITLE
Non-English characters in the folder name break ProteinProphet

### ISSUE THREAD

**Issue by hongweizhao1** [Nesvilab/philosopher#435]
When I use a DDA file to create a spectral library, Philosopher/cmd. Execute() appears

/workspace/philosopher/cmd/root.go:35 +0x25

main.main()

/workspace/philosopher/main.go:25 +0x90

ERRO[10:01:06] Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files
[log.txt](https://github.com/Nesvilab/philosopher/files/11523592/log.txt)

Process 'ProteinProphet' finished, exit code: 2

Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~

Cancelling 8 remaining tasks

**Comment by fcyu** [comment]
Can you replace the non-English (e.g. "其余软件的汇总") in your folder names and try again?

Best,

Fengchao

**Comment by hongweizhao1** [comment]
Thank you very much. I have already solved the problem that troubles me
