### ISSUE TITLE
Applying evaluation to all search hits in PSM

### ISSUE THREAD

**Issue by FantacticMisterFox** [Nesvilab/philosopher#44]
Thanks for providing with this nice wrapper for the whole Prophetsuite. It is easy to use.
I would like to know if I can use PeptideProphet to evaluate all peptide spectrum matches. Not just only the first/best one. If not I would like to make this as a feature request.

**Comment by anesvi** [comment]
MSFragger can write top N matched to pepXML file
ANDY: what is the option for that?

Unfortunately PeptideProphet (which is what is used in Philosopher) only reads the top match per spectrum

So there is no easy way of adding that option. There is a workaround  - MSFragger can write separate pepXML files (say one for the top peptide, one for second best, etc) and one can then process them independently. But this is far from ideal (from the FDR perspective) and may have to be done by running the tools command line, not via FragPipe (not sure how you are running it)

Best
Alexey

**Comment by FantacticMisterFox** [comment]
Yeah did thought about this, but then the whole information of the top hits would be lost. Which contain the most information.

**Comment by anesvi** [comment]
One day we may replace PeptideProphet… now have to work given what we have.
Can you tell me what you want to achieve? Get some extra IDs from chimeric spectra? I am of the opinion that it is not going to help much, especially in large datasets.
Alexey

**Comment by andytyk** [comment]
The parameters for outputting the top N hits in MSFragger is output_report_topN.  Combining this with the output_report_rankfiles = 1 option will write each search rank hit to a different pepXML file.

**Comment by FantacticMisterFox** [comment]
Currently I am trying to work with 6frame data bases. I see some draw backs from a priori reduced data bases. I would rather deal with more cleaning steps and score assessment. I think if I have a good scoring scheme I can eliminate the error in the last step. And I am more worried of losing information in the early steps.
From your review paper I see that you tend more to towards well build databases. Maybe we can discuss this in an email or different forum further. I think the issue tracker will get messy otherwise.

**Comment by anesvi** [comment]
Yes, this is not for the Philosopher issue tracker site, feel free to contact us directly.
Alexey
