### ISSUE TITLE
Wrong matching of protein_id

### ISSUE THREAD

**Issue by She1111** [Nesvilab/philosopher#440]
Hi,

I used fragpipe for DDA searching and found there is some wrong matching of 'peptide_sequence' and 'protein_id' after I searched in both Uniprot and fasta.fas file.
<img width="934" alt="Capture1" src="https://github.com/Nesvilab/FragPipe/assets/130647208/9f0ffc53-1083-4fde-9d1c-fe649941dace">
<img width="914" alt="Capture" src="https://github.com/Nesvilab/FragPipe/assets/130647208/c63bda76-872a-4899-a427-ebf83d345465">
Is there any strategies to correct them or just by hand?
Thanks in advance!

Best,
Shel

**Comment by anesvi** [comment]
What is wrong actually? This peptide got assigned not to protein 04090 but to P16972 https://www.uniprot.org/uniprotkb/P16972/entry which is FER2

**Comment by She1111** [comment]
> What is wrong actually? This peptide got assigned not to protein 04090 but to P16972 https://www.uniprot.org/uniprotkb/P16972/entry which is FER2

I searched this peptide in fasta.fas file, it also showed this peptide belongs to O04090. But its 'prev_aa' and 'next_aa' are correct. I found there are hundreds of peptides are missed assigned. I also upload my log file.
<img width="697" alt="Capture3" src="https://github.com/Nesvilab/philosopher/assets/130647208/3f08e09c-9410-43f8-b267-96fee5fa33ba">
<img width="914" alt="Capture" src="https://github.com/Nesvilab/philosopher/assets/130647208/3bd4559b-9f86-483f-979c-9bfa70bbad61">
<img width="885" alt="Capture5" src="https://github.com/Nesvilab/philosopher/assets/130647208/f3aed367-e37e-4b92-b6f9-07965210d83d">
<img width="692" alt="Capture4" src="https://github.com/Nesvilab/philosopher/assets/130647208/fd8cebd2-5b81-4d2a-a4fb-b5dc28b0fc11">
[LiP_1min.txt](https://github.com/Nesvilab/philosopher/files/11707446/LiP_1min.txt)

Best,
Shel

**Comment by fcyu** [comment]
You are using older versions of the tools. Could you upgrade FragPipe, MSFragger, IonQuant, and Philosopher to the latest versions and try again?

Thanks,

Fengchao

**Comment by She1111** [comment]
I rerun samples with the latest version of FragPipe and I still got some missed-peptides. 
<img width="792" alt="Capture" src="https://github.com/Nesvilab/philosopher/assets/130647208/4915002f-9a77-4561-b88a-26ec1d4850c4">
Is it may because of the confusion of 'mapped_genes'?

**Comment by fcyu** [comment]
Hi Shel,

I checked your first example, `AAEEAGIDLPYSCR` can be matched to `P16972`. Note, `I` and `L` are indistinguishable.

Best,

Fengchao

**Comment by She1111** [comment]
> Hi Shel,
> 
> I checked your first example, `AAEEAGIDLPYSCR` can be matched to `P16972`. Note, `I` and `L` are indistinguishable.
> 
> Best,
> 
> Fengchao

Thank you Fengchao! Dose it mean that these 'missed-peptides' are not unique one?

Best,
Shel

**Comment by She1111** [comment]
> > Dose it mean that these 'missed-peptides' are not unique one?
> 
> What does "unique one" mean?
> 
> Best,
> 
> Fengchao

Like one peptide can be mapped to two proteins.

Best,

Shel

**Comment by She1111** [comment]
> Correct, but I think it is not related to your original question. The protein ID is not incorrectly matched.
> 
> Best,
> 
> Fengchao

Yes I got it. I would like to discard these un-unique peptides. So I just need to filter out the peptides with values in 'Mapped Genes'?

Best,

Shel

**Comment by fcyu** [comment]
If you want to get a list of unique peptides, yes.

Best,

Fengchao

**Comment by She1111** [comment]
> If you want to get a list of unique peptides, yes.
> 
> Best,
> 
> Fengchao

Thank you very much for your help! That makes sense for me :)! It is good to have this faster searching engine 💯!

Best,
Shel
