### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock! & Process 'PhilosopherFilter' finished, exit code: 2 

### ISSUE THREAD

**Issue by MelissaVorster** [Nesvilab/philosopher#441]
- Describe the issue or question:
Good day, I am running a LFQ workflow using .mzML files and the mouse ref database. I get this error and unfortunately not any of the previous issue's answers seem related. Could you please help?

- Upload your log file
[log_2023-06-09_14-36-20.txt](https://github.com/Nesvilab/FragPipe/files/11720482/log_2023-06-09_14-36-20.txt)

**Comment by guoci** [comment]
@MelissaVorster I have pushed a fix to the code.
For an immediate solution, set the number of threads to ≥ 2.

**Comment by MelissaVorster** [comment]
Hi, thank you very much. When you say "set the number of threads" are you referring to the global settings?

[cid:64d7eaa6-4b78-478a-b117-dba2a4ddef60]

Or where can one find these settings?


Kind Regards/ Vriendelike Groete

Melissa Vorster  |  MSc (Bioinfo and Comp Bio) Candidate
Centre for Bioinformatics and Computational Biology

Faculty of Science | amaMaties.net Council 2023 | Support

e: ***@***.***  |  t: +27 81 253 9730

[cid:c15a7b58-ee8f-4bce-8698-302b4c6bf948]

________________________________

**Comment by guoci** [comment]
Just a reminder, the fix #442 isn't merged yet
