### ISSUE TITLE
ProteinProphet batchconvert not recognized

### ISSUE THREAD

**Issue by BrendonSeale** [Nesvilab/philosopher#444]
- Describe the issue or question:
All of my searches fail at validation when ProteinProphet attempts to run the 'batchconvert' command in the temp directory:

"Calculating sensitivity...and error tables...
'C:\Users\bseale\AppData\Local\Temp\377f778c-16bc-455a-8930-f468ff17b7cc/batchcoverage' is not recognized as an internal or external command,
operable program or batch file."

At first I thought it might have been an issue with the location of the temp directory but I don't see a way to change that.

Any help would be appreciated, seems no searches can work on my (and a colleagues) systems (same error).

- Upload your log file
Done.
[log_2023-06-16_09-01-46.txt](https://github.com/Nesvilab/FragPipe/files/11770552/log_2023-06-16_09-01-46.txt)

**Comment by AimeeD90** [comment]
Hi, 

The executable should be batchcoverage.exe on Windows, not batchcoverage (linux). I am quite confused why you got a wrong one, because it performs normally on my PC. I guess it should be something related to your system. Have you downloaded philosopher from FragPipe once more and still met this error? 

Best,
Yamei

**Comment by BrendonSeale** [comment]
I did start with a fresh install, downloading both automatically through FragPipe and manually. I will try a total reinstall of fragpipe, manually adding philosopher.

**Comment by BrendonSeale** [comment]
Just to update a reinstall and manually adding the tools didn't fix this issue.

**Comment by AimeeD90** [comment]
With TPP and WLS should be fine. And batchcoverage.exe is implicitly called by ProteinProphet, so the command should be 'batchcoverage.exe', not 'philosopher batchcoverage'. 
The error you met looks like philosopher failed to deploy the binary executables into your system. Not sure if batchcoverage.exe has been properly deployed to the Temp folder, or if it has been deployed as a linux version. To fix this error, really need to check if you can find these executables in the Temp folder (should be C:\Users\youraccount\AppData\Local\Temp\foldername). You should find ProteinProphet.exe, batchcoverage.exe under that folder. 
You can simply run ProteinProphet unchecking other steps in FragPipe and locate to Temp folder at the meantime to take a check. To make it work, I suggest to load a large database, so can make the temp folder exist a little bit longer and allow for a thorough check. 

Best,
Yamei

**Comment by BrendonSeale** [comment]
I understand. I have monitored the temp folder as requested.

![image](https://github.com/Nesvilab/philosopher/assets/75998063/916d0101-490d-4620-bf14-d7e909476dd7)

As you can see batchcoverage.exe isn't being deployed there. I am wondering if our IT's chosen security software is messing with something. Thanks for the tip, I can look into this more now.

**Comment by BrendonSeale** [comment]
I can now confirm that our security software was interfering with the deployment of batchcoverage. Are there other executables that are deployed in the same way? Knowing this might help me avoid this issue in the future.

Thank you for your help!

**Comment by AimeeD90** [comment]
Thanks for the update, good to know. 

You can check the philosopher wiki page, it provides a list of tools philosopher can deploy to a user's computer (https://github.com/Nesvilab/philosopher/wiki). One thing to mention that philosopher will only deploy such executables when you run certain commands. In most established FragPipe workflows, ProteinProphet is the only tool that philosopher always uses, while others are seldom used, so fixing the issue with ProteinProphet will make FragPipe work most of the time.
