### ISSUE TITLE
Philsopher filter error: cannot find .meta\pep.bin

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/philosopher#449]
Philosopher filter is not completing because it is not generating the pep.bin files. I think this is because it doesn't recognise the --razorbin tag in the command but I do not know how to remove that tag or why is there.

Log is below.

Running on Windows Server 2012 R2.

[log_2023-07-05_12-06-21.txt](https://github.com/Nesvilab/philosopher/files/11964097/log_2023-07-05_12-06-21.txt)

**Comment by fcyu** [comment]
The latest Philosopher requires the latest FragPipe (version 20).

Best,

Fengchao
