### ISSUE TITLE
Missing Intensity values in msstats.csv TMT channel columns

### ISSUE THREAD

**Issue by Monod79** [Nesvilab/philosopher#450]
- Describe the issue or question:

Title says it all. After running a TMT11-MS3-phospho workflow with Fragpipe v20, channel columns from the msstats.csv file are empty while associated psm.tsv files display full intensity values. 

The channel column headers from psm.tsv files are labeled respectively by sample names from the annotation.txt file, whereas msstats.csv channel headers are labeled by labeling reagents name (126, 127N, etc...). 

This prevents running the latest version of FragPipetoMSstatsPTMFormat from MSstatsPTM, which have been updated with you guys to directly import Fragpipe's output.

Here's a link towards the files. 

https://drive.google.com/drive/folders/12NQfDJmOwHBxDbU67Pk4-asbzW1Jw0gK?usp=sharing

I'm always thankful for your great work. 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by AimeeD90** [comment]
Thanks for providing us with these files, can you also share one mzML file? 

Best,
Yamei

**Comment by Monod79** [comment]
Sure Yamei ! 

I've uploaded one mzML file, which is one fraction out of 9. 

Joe

**Comment by Monod79** [comment]
Hi ! 

Is there any development regarding this issue?

**Comment by AimeeD90** [comment]
Hi,

Apologies for the late reply, with the mzML file you provided, I ran a test with the same workflow TMT10-MS3-phospho using FragPipe V20.0, however I wasn't able to reproduce the error you met. The intensity columns are correctly incorporated in msstats.csv. Attached is the msstats.csv by my analysis. Can you please share the fragpipe.workflow file with us? 

Best,
[msstats.csv](https://github.com/Nesvilab/philosopher/files/12322516/msstats.csv)

Yamei

**Comment by Monod79** [comment]
Hi Yamei,

I've added the fragpipe workflow in the shared folder. 

Thanks again for your help !

**Comment by anesvi** [comment]
We just use default workflows and the only change is needed is to check 'generate Msstat file' box in Validation tab. Did you check that box?

**Comment by Monod79** [comment]
Yes Alexey I've checked the MSStats box.

I must precise that I'm running FragPipe in headless mode, where I must separate the dataset in several folders with the respective channel annotation.

Joe

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anesvi** [comment]
Yes, that's the right way to put mzML files into separate folders and have annotation.txt in each folder. But that is the same really with the GUI version. So I do not think running headless vs GUI would be an issue by itself. We need to take a look with Yamei, hopefully next week, but I personally tested quite a bit before.

**Comment by AimeeD90** [comment]
Hi Joe, 

Thank you for bringing this issue to our attention. Upon debugging, we just noticed a bug in philosopher that was causing this error. I have attached the corrected executable of philosopher, which resolves this problem. Please download it and take another run (can start from ProteinProphet by unchecking MSFragger and validation tools before Protein Inference step). Let us know if you encounter any problems.

[philosopher-linux.zip](https://github.com/Nesvilab/philosopher/files/12330683/philosopher-linux.zip)

**Comment by Monod79** [comment]
Yamei you rock!

I'll be able to test this new version in 2 weeks (vacation), but I'll be glad to let you guys know.

Thanks to everyone involved.

Joe

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Monod79** [comment]
Hi Yamei, 

The philosopher file you sent me doesn't seem to work. I've switched your file with the previous philospher executable. 

Here's the error message I'm having : 

ERROR - Does not appear to be an executable file: "/home/monod79/fragpipe/tools/philosopher_v5.0.0_linux_amd64/philosopher"

**Comment by AimeeD90** [comment]
If running FragPipe in the headless mode, you can provide the path of Philosopher using --config-philosopher, there is no need to rename it. If there was a problem with the executable, here I uploaded both linux and windows versions at https://drive.google.com/drive/folders/18S1XjraHIhV361bua9qfXOPEDmrM12A7?usp=sharing. It worked on my end, please give it another try.

**Comment by Monod79** [comment]
There was an execution permission issue with the file. It was simply solved with chmod u+x philosopher-v5.1.0-RC3

Thanks again Yamei for your kind help !

**Comment by Monod79** [comment]
Hi Yamei, 

I've tested the latest philosopher update and I confirm it's working fine. I'm getting values in the msstats.csv file. 

Many thanks !
