### ISSUE TITLE
Custom fasta database result in Philosopher: panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by yannic-chen** [Nesvilab/philosopher#451]
Dear FragPipe team,

I created a custom fasta database with gene name as header. Due to the nature of the analysis, I have the same gene name for multiple sequences. Therefore I added a number suffix ("_#") after each gene name to make them unique. This is so that when adding decoys using the inbuild function my database does not get trimmed. But I still get the error message:

> java.lang.IllegalStateException: Something happened during database update
> 	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:376)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException: Process returned non zero value
> 	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
> 	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
> 	... 1 more

Next I ran the Nonspecific-HLA workflow (IM-MS timsTOF data), however I get the following error:

> PhilosopherDbAnnotate [Work dir: D:\data\2022-145\FragPipe\20230310_AtoG_only]
> C:\FragPipe_v18.0\fragpipe\tools\philosopher_v4.2.2_windows_amd64\philosopher.exe database --annotate D:\data\2022-145\2023-03-10-decoys-hg19_lenient_extended_AtoG_long_custom.fasta.fas --prefix rev_
> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 1 [running]:
> philosopher/lib/dat.ProcessTair(0xc0004a7be1, 0x11, 0xc0005fef40, 0x32, 0xc000018138, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
> 	/workspace/philosopher/lib/dat/db.go:472 +0x4ba
> philosopher/lib/dat.(*Base).ProcessDB(0xc0001a0000, 0xc0000620c0, 0x53, 0xc000018138, 0x4)
> 	/workspace/philosopher/lib/dat/dat.go:157 +0x465
> philosopher/lib/dat.Run(0xc00001a9f0, 0x24, 0xc00001aa20, 0x2c, 0xc000022460, 0x48, 0xc00001e440, 0x3b, 0xc00001e480, 0x32, ...)
> 	/workspace/philosopher/lib/dat/dat.go:64 +0xb85
> philosopher/cmd.glob..func4(0x1f0b5a0, 0xc000138f00, 0x0, 0x4)
> 	/workspace/philosopher/cmd/database.go:23 +0xc5
> github.com/spf13/cobra.(*Command).execute(0x1f0b5a0, 0xc000138ec0, 0x4, 0x4, 0x1f0b5a0, 0xc000138ec0)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x1f0d7c0, 0x200b60, 0xc00008ff70, 0xc00008ff68)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
> philosopher/cmd.Execute()
> 	/workspace/philosopher/cmd/root.go:35 +0x34
> main.main()
> 	/workspace/philosopher/main.go:25 +0x85
> INFO[12:56:18] Executing Database  v4.2.2                   
> INFO[12:56:18] Annotating the database                      
> Process 'PhilosopherDbAnnotate' finished, exit code: 2
> Process returned non-zero exit code, stopping
> 
> ~~~~~~~~~~~~~~~~~~~~
> Cancelling 4 remaining tasks

My fasta file has the following format:

```
>TSC22D1_1
AAAAAADISARKMAHPAMFPRRGSGGGSASALNAAGTGVGSNATSSEDFPP
>CDK13_2
AAAAAASSSCFSPGPPLEVKRLARGRRRAGGRQKRRRGPRAGQEAEKRRVF
>MAZ_3
AAAAATAVVAPTSTVAVAPVASALERKTKSKGPYICALCAKEFKNGYNLRR
>ARID1B_4
AAAAGAPGSMDPLQNSHEGYPNSQCDHYPGYSRPGAGGGGGGGGGGGGGSG
>ARID1B_5
AAAAGAPGSMDPLQNSHEGYPNSQCSHYPGYSRPGAGGGGGGGGGGGGGSG
>ANKS3_6
AAAAGHEIIVQYFLNHSPSVAQAGVRQLTAISASRVEAILLPQPPE
>ZNF586_7
AAAALRAPAQSSVTFEDVAVNFSLEGWSLLNEAQGCLYHDVMLETLTLISS
>PIPSL_8
AAAASAAEAGIATTGTEDSDDALLKVTISQQEFGHTGLPDLSSMTEEEKIV
>ADNP_9
AAAATGPPPGNTSSTQKWKICTICNGLFPENVYSVHFEKEHKAEKVPAVAN
>ZNF814_10
AAAATLRLSAQESHSVIQTGVQWRDRSSPQPPPTGDILIQGTVTFEDVAVN
>ZNF814_11
AAAATLRLSAQGTVTFEDVAVNFTWGEWNLLSEAQRCLYRDVTLENLALIS
>PPP2R1A_12
AAADGDDSLYPIAVLIDELRNEDVQGRGFTMLARLGRELLTSSDPPASASQ
>CCDC85A_13
AAAESCSPAPAGSSAAPPAPVEDLSEVSDEELLQWSKEELIRSLRRAEAEK
>CCDC85A_14
AAAESCSPAPAGSSAAPPAPVEDLSRVSDEELLQWSKEELIRSLRRAEAEK
>GLT8D1_15
AAAFSEDCDSASTKVVIRGAGNQYNCIGYLDYKKERIRKLSMKASTCSFNP
>ANKS3_16
AAAGHEIIVQYFLNHSPSVAQAGVQRLTAISASRVEAILLPQPPE
```

I use FragPipe v18.0 with Philosopher v4.2.2 on AMD

I also wanted to ask if the header allows transcript ID (instead of gene name) from multiple databases (ucsc, ncbi and ensembl) in a single file.

Many thanks,
Yannic

**Comment by xiaodfeng** [comment]
[uniprot_human_W_Trunk.zip](https://github.com/Nesvilab/philosopher/files/12168727/uniprot_human_W_Trunk.zip)
I've attached the fasta file. Thank you.

**Comment by AimeeD90** [comment]
I checked the fasta file you provided, turns out that there are quite a lot duplicated headers in it, which caused philosopher to fail. Philosopher can't work with duplicated headers, so please encode your headers properly, like by adding suffixes like "_1", "_2" to distinguish them. Philosopher will definitely work after making those changes. 

Attached is the duplicated header table.
[duplicated_header.zip](https://github.com/Nesvilab/philosopher/files/12175878/duplicated_header.zip)

**Comment by xiaodfeng** [comment]
Thank you for checking the fasta file. According to your suggestion, I added suffixes to the header like "_1", "_2" to distinguish them. As shown in the attached fasta file. Thus the headers should be unique now. Apart from the unique headers, I also make sure the AA sequences are unique by using the following python script:
`def count_duplicates(fasta_file):
    sequence_counts = defaultdict(int)
    # Read the FASTA file and count the occurrences of each sequence
    for record in SeqIO.parse(fasta_file, "fasta"):
        sequence = str(record.seq)
        sequence_counts[sequence] += 1
    # Print the counts of duplicates
    for sequence, count in sequence_counts.items():
        if count > 1:
            print(f"Sequence: {sequence}\tCount: {count}")
fasta_file_path = "uniq_gencode_F2All_TTT_TTC.fasta"
count_duplicates(fasta_file_path)`
[uniq_gencode_F2All_TTT_TTC_Test.zip](https://github.com/Nesvilab/philosopher/files/12213339/uniq_gencode_F2All_TTT_TTC_Test.zip)
However, there are still errors reported by philosopher_V5
`philosopher_v5/philosopher database --custom uniq_gencode_F2All_TTT_TTC_Test.fasta
INFO[11:02:29] Executing Database  v5.0.0
WARN[11:02:29] contaminants are not going to be added to database
INFO[11:02:29] Generating the target-decoy database
INFO[11:02:36] Creating file
panic: runtime error: index out of range [2] with length 1
goroutine 191 [running]:
github.com/Nesvilab/philosopher/lib/dat.getProteinName({0xc00022c870?, 0x16?}, 0x80?, 0x0)
        D:/Projects/philosopher/philosopher/lib/dat/db.go:235 +0x334
github.com/Nesvilab/philosopher/lib/dat.ProcessHeader({0xc00022c870, 0x16}, {0xc02c902480, 0x25}, 0x5, {0xb69c88, 0x4}, 0x0?)
        D:/Projects/philosopher/philosopher/lib/dat/db.go:50 +0x1fd
github.com/Nesvilab/philosopher/lib/dat.(*Base).ProcessDBAndSerialize.func2(0x1a)
        D:/Projects/philosopher/philosopher/lib/dat/dat.go:181 +0x60b
created by github.com/Nesvilab/philosopher/lib/dat.(*Base).ProcessDBAndSerialize
        D:/Projects/philosopher/philosopher/lib/dat/dat.go:152 +0x190

`

**Comment by AimeeD90** [comment]
Hi,

Thanks for the update, it's helpful! We noticed a small bug in philosopher when parsing headers starting with ">AT". In the current version, philosopher assumes that if a header starts with ">AT", the sequence follows a specific format like The Arabidopsis Information Resource (TAIR), and it parses the header using the TAIR pattern. However, look like in your database, this is not the case. To avoid this error, I suggest replacing ">AT" with a different prefix, for example, ">custom_AT". I have tested this solution, and it worked. We will fix this error in the next release, but for now, please make these changes on your end.

Thank you for bringing this to our attention.
