### ISSUE TITLE
Remove the warning `Cannot read file. open .meta\meta.bin: The system cannot find the path specified.` in the `workspace --clean` command

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#452]
This warning is printed when running `philosopher workspace --clean` command in a clean directory, which happens most of the time at the beginning of the FragPipe run. It is not necessary and confusion, such as this report https://github.com/Nesvilab/FragPipe/issues/1197. 

Please remove it from the `workspace --clean` command.

Thanks,

Fengchao

**Comment by AimeeD90** [comment]
The warning message is removed as requested.
