### ISSUE TITLE
Error in PhilosopherFilter - exit code: 1

### ISSUE THREAD

**Issue by helloworld1631** [Nesvilab/philosopher#454]
**Describe the bug**
I use the TMT10 workflow with some slight changes in MSfragger setting. When it came to the final stage of validation, "PhilosopherFilter", it reports a new error saying that cannot read/parse the file. But this .pep.xml file does exist in the folder, and I can open it with Notepad.

**Screenshots**
Here is the detailed information of Log: 
PhilosopherFilter [Work dir: C:\Users\zwang3136\Desktop\MSfragger_TPP_Nterm_test\Second_TPP_Nterm_A_Search]
C:\Users\zwang3136\Desktop\FragPipe-jre-20.0\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe filter --sequential --picked --prot 0.01 --tag rev_ --pepxml C:\Users\zwang3136\Desktop\MSfragger_TPP_Nterm_test\Second_TPP_Nterm_A_Search --protxml C:\Users\zwang3136\Desktop\MSfragger_TPP_Nterm_test\Second_TPP_Nterm_A_Search\combined.prot.xml --razor
INFO[03:01:38] Executing Filter  v5.0.0                     
INFO[03:01:38] Processing peptide identification files      
INFO[03:01:38] Parsing C:\Users\zwang3136\Desktop\MSfragger_TPP_Nterm_test\Second_TPP_Nterm_A_Search\interact-E_ZW_TPP_Nterm_A_test.pep.xml 
ERRO[03:01:38] Cannot read file. Error parsing the file     
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

**Please complete the following information:**
 - OS: windows
 - Version: FragPipe v20.0
 
**Thank you!**

**Comment by fcyu** [comment]
Could you upload the whole log file?

Thanks,

Fengchao

**Comment by helloworld1631** [comment]
Sure. Second time I start from Philosopher.
[1log_2023-08-12_17-51-22.txt](https://github.com/Nesvilab/philosopher/files/12328968/1log_2023-08-12_17-51-22.txt)
[2log_2023-08-13_03-01-38.txt](https://github.com/Nesvilab/philosopher/files/12328969/2log_2023-08-13_03-01-38.txt)

**Comment by fcyu** [comment]
Thanks for the log files. Everything looks good until the Philosopher filter command...

@AimeeD90 Could you take a look?

Best,

Fengchao

**Comment by helloworld1631** [comment]
Hi all, 

I made several other tries. I notice when use the proteome fasta file downloaded via FragPipe, everything works well. But when use another fasta, PhilosopherFilter reports error again. Maybe something wrong with my fasta file result in the reading .pep.xml error??

**Comment by helloworld1631** [comment]
Hi Yamei,

Sure. Here are the log file/.fasta file, and a folder containing .pep.xml files used in the PhilosopherFilter step. 

(https://gtvault-my.sharepoint.com/:f:/g/personal/zwang3136_gatech_edu/Epg1L28GrMhMgZ5xi2-8WZUBKFG1qdZuENlzzGZwYqck_Q?e=OFh1Dk)

Thank you!

**Comment by AimeeD90** [comment]
The files worked fine for me. Not sure if the folder name 'Human_Reviewed_cannonical&isoforms' would be causing this error. Can you try renaming the folder without the '&' symbol and rerun ProteinProphet and filtering steps?

**Comment by helloworld1631** [comment]
I see. That is the real reason. After renaming, now it works well.
Thanks again for your kind help!
