### ISSUE TITLE
Cannot read file. open .meta\pep.bin: The system cannot find the file specified. Cannot read file. open .meta\db.bin: The system cannot find the file specified.

### ISSUE THREAD

**Issue by manushiparajuli** [Nesvilab/philosopher#455]
[ERRO[15:06:48]](url) Cannot read file. open .meta\db.bin: The system cannot find the file specified.

philosopher_v5.0.0_windows_amd64>philosopher report
INFO[15:07:32] Executing Report  v5.0.0
INFO[15:07:32] Creating reports
ERRO[15:07:32] Cannot read file. open .meta\pep.bin: The system cannot find the file specified.

Philosopher doesn't print report. philosopher_v5.0.0_windows_amd64

![Screenshot 2023-08-17 092741](https://github.com/Nesvilab/philosopher/assets/55906277/11f12a63-137a-407a-b957-f92cee40df8a)

![Screenshot 2023-08-16 134652](https://github.com/Nesvilab/philosopher/assets/55906277/e9af35e4-5a51-43d5-aca3-9dd35fee1209)

**Comment by manushiparajuli** [comment]
![IMG_6566](https://github.com/Nesvilab/philosopher/assets/55906277/8aa5d6a4-7e33-4611-b473-db6a0eec9be6)

**Comment by AimeeD90** [comment]
Hi, could you please share the log file with us? Thanks.
