### ISSUE TITLE
Annotating the database panic: runtime error: index out of range [2] with length 1

### ISSUE THREAD

**Issue by jayieh** [Nesvilab/philosopher#456]
When running the "database --annotate" step in a FragPipe workflow, I receive the following error:

`INFO[11:18:48] Executing Database  v5.0.0
INFO[11:18:48] Annotating the database
panic: runtime error: index out of range [2] with length 1

goroutine 27 [running]:
github.com/Nesvilab/philosopher/lib/dat.getProteinName({0xc00038a0a0?, 0x10?}, 0xe8?, 0x0)
        D:/Projects/philosopher/philosopher/lib/dat/db.go:235 +0x334
github.com/Nesvilab/philosopher/lib/dat.ProcessHeader({0xc00038a0a0, 0x10}, {0xc0003a41e0, 0xe1}, 0x5, {0xc00009e0d0, 0x4}, 0x0?)
        D:/Projects/philosopher/philosopher/lib/dat/db.go:50 +0x1fd
github.com/Nesvilab/philosopher/lib/dat.(*Base).ProcessDBAndSerialize.func2(0x7)
        D:/Projects/philosopher/philosopher/lib/dat/dat.go:181 +0x60b
created by github.com/Nesvilab/philosopher/lib/dat.(*Base).ProcessDBAndSerialize
        D:/Projects/philosopher/philosopher/lib/dat/dat.go:152 +0x190`

I am using FP 20 on a Win10 64bit system - and therefore philosopher_v5.0.0_windows_amd64.

The search went smooth up to that step. I am using an non-uniprot fasta (from araport) and saw that this might cause issues. Decoys and contaminants were added by FP. Here is an example of a repsective header:

`>AT1G01010.1 | Symbols: NAC001, NTL10, ANAC001 | NAC domain containing protein 1 | chr1:3760-5630 FORWARD LENGTH=429`

Looking fwd to any suggestions.

**Comment by jayieh** [comment]
As the wiki for Philosopher states that the protein description text should not contain any commas or special characters, I now have removed any characters that are not 

`[A-Z]|[a-z]|[0-9]| |=|-|\\.|_|\\|` - however not beeing sure, if that is enough.

Headers now look like

`>AT1G01010.1 | Symbols NAC001 NTL10 ANAC001 | NAC domain containing protein 1 | chr13760-5630 FORWARD LENGTH=429`

with the error persisting. What else could cause the problem?

**Comment by AimeeD90** [comment]
Hi all,

This issue has been mentioned at https://github.com/Nesvilab/philosopher/issues/451, please review the last few comments for more details. To put it simply, by adding a header prefix before 'AT' like 'custm_AT' can address this matter. We will fix it in next release.

Best,
Yamei

**Comment by jayieh** [comment]
Hi, thanks for pointing me to #451. I briefly skimmed it, but missed the most relevant post...

Thanks for the workaround. Looking fwd to the next release :)
