### ISSUE TITLE
when using the iTRAQ8.workflow in FragPipe v20.0, the log shows that the analysis finished successfully, but the output matrix only includes titles without quantification results

### ISSUE THREAD

**Issue by qianliujia** [Nesvilab/philosopher#459]
We revised default iTRAQ4.workflow to analysis iTRAQ8, as follows: 
[iTRAQ8.workflow.txt](https://github.com/Nesvilab/philosopher/files/12521158/iTRAQ8.workflow.txt)

Here is the log file (shows finished): 
[iTRAQ8_20230903.log](https://github.com/Nesvilab/philosopher/files/12521175/iTRAQ8_20230903.log)

Here is the screenshot of output matrix (only tile without any quantification results):
![2d53fd95dc066ffd8043be947bb93ac](https://github.com/Nesvilab/philosopher/assets/107305990/fc99b21d-2735-4ba3-95bd-ace241d33af8)

**Comment by AimeeD90** [comment]
Hi, looks like philosopher failed to calculate the precursor purity score on your data, can you share one mzML with us?
