### ISSUE TITLE
ERRO[15:34:38] Cannot read file. open .meta\db.bin: The system cannot find the file specified.  Process 'PhilosopherFilter' finished, exit code: 1

### ISSUE THREAD

**Issue by RMeelker** [Nesvilab/philosopher#460]
Hi! I am trying to run a 100% FDR search of 4 fractionated samples (11 fractions each) using Fragpipe v20.0 but my search always crashes on the same point, giving the following error:

ERRO[15:34:38] Cannot read file. open .meta\db.bin: The system cannot find the file specified. 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

Here is the log file
[log_2023-09-05_15-34-38.txt](https://github.com/Nesvilab/philosopher/files/12524571/log_2023-09-05_15-34-38.txt)

Is there something wrong with the search parameters? Thank you beforehand!

Best,
Rebecca

**Comment by fcyu** [comment]
It looks like the changes in the latest version broke the `do not use ProteinProphet file` option, please uncheck it.

If you want to use 100% protein-level FDR, you should set `--prot 1`. There is no need to change `--minprob` because it is for the non-razor case, but FragPipe always add `--razor` flag. Here is the filter documentation: https://github.com/Nesvilab/philosopher/wiki/Filter

Best,

Fengchao

**Comment by RMeelker** [comment]
Dear Fengchao and Yamei,

It works now. Thank you!

Best,
Rebecca

**Comment by comtewal** [comment]
Hi,  I am trying to run a Fragger search using the Glyco tab and MS1 quantitation (LFQ)- the search goes thru until it gets to writing the reports in Philosopher and then crashes. The box "Do not use ProteinProphet file is not selected.
I am enclosing the log and parameter files from the search.
Thank you so much for your help,

Susana Comte-Walters
Medical University of SC
Mass Spectrometry Facility
comtewal@musc.edu

[log_2023-09-20_17-00-06.zip](https://github.com/Nesvilab/philosopher/files/12689941/log_2023-09-20_17-00-06.zip)
[fragger_parameters.zip](https://github.com/Nesvilab/philosopher/files/12689942/fragger_parameters.zip)

**Comment by fcyu** [comment]
Hi Susana,

First of all, could you upgrade FragPipe to the latest version (version 20)? 

Second, the current version has issues when the `Do not use ProteinProphet file` is enabled. We will fix it in the next release.

Best,

Fengchao
