### ISSUE TITLE
Error running FAIMS data

### ISSUE THREAD

**Issue by mikmoux** [Nesvilab/philosopher#461]
Hi, 

I was trying to analyse DDA runs with FAIMS and I got this error: 

Process 'PhilosopherFilter' finished, exit code: 0
PhilosopherFilter [Work dir: D:\EV_EMT_project\FragPipe\WT_EV_4]
C:\PhD_programs\FragPipe-jre-19.1\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml D:\EV_EMT_project\FragPipe\WT_EV_4 --protxml D:\EV_EMT_project\FragPipe\combined.prot.xml --razorbin D:\EV_EMT_project\FragPipe\HDF_KO_1\.meta\razor.bin
Error: unknown flag: --razorbin
Usage:
  philosopher filter [flags]

Flags:
      --2d               two-dimensional FDR filtering
      --group            use the group label to filter the data
  -h, --help             help for filter
      --inference        extremely fast and efficient protein inference compatible with 2D and Sequential filters
      --ion float        peptide ion FDR level (default 0.01)
      --mapmods          map modifications
      --models           print model distribution
      --pep float        peptide FDR level (default 0.01)
      --pepProb float    top peptide probability threshold for the FDR filtering (default 0.7)
      --pepxml string    pepXML file or directory containing a set of pepXML files
      --picked           apply the picked FDR algorithm before the protein scoring
      --prot float       protein FDR level (default 0.01)
      --protProb float   protein probability threshold for the FDR filtering (not used with the razor algorithm) (default 0.5)
      --protxml string   protXML file path
      --psm float        psm FDR level (default 0.01)
      --razor            use razor peptides for protein FDR scoring
      --sequential       alternative algorithm that estimates FDR using both filtered PSM and protein lists
      --tag string       decoy tag (default "rev_")
      --weight float     threshold for defining peptide uniqueness (default 1)

Process 'PhilosopherFilter' finished, exit code: 0
PhilosopherReport [Work dir: D:\EV_EMT_project\FragPipe\MCF10A_KO_HDF_3]
C:\PhD_programs\FragPipe-jre-19.1\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe report
INFO[19:39:35] Executing Report  v5.0.0                     
INFO[19:39:35] Creating reports                             
ERRO[19:39:35] Cannot read file. open .meta\pep.bin: The system cannot find the file specified. 
Process 'PhilosopherReport' finished, exit code: 1
Process returned non-zero exit code, stopping

Any ideas on why this is happening or how to fix it? I am new to this software but used the LFQ-MBR workflow.

Thanks!
Michael

**Comment by fcyu** [comment]
Upgrading FragPipe to version 20 will solve this problem.

Best,

Fengchao
