### ISSUE TITLE
an error with Proteinprophet

### ISSUE THREAD

**Issue by xyzcc2007** [Nesvilab/philosopher#465]
ERRO Cannot execute program, there was an error with Proteinprophet, please check your parameters and input files
often happened these days,I have no idea.need help,thanks!
Here is the log and screen image
![14ffbe3fad9f68cc13076c99b06c512](https://github.com/Nesvilab/philosopher/assets/145945874/7cc66487-f20f-4066-a7a0-564139d8e58d)
[log_2023-10-08_17-35-08.txt](https://github.com/Nesvilab/philosopher/files/12840850/log_2023-10-08_17-35-08.txt)

**Comment by anesvi** [comment]
Please upgrade to the latest version of the tools

**Comment by xyzcc2007** [comment]
Fine,Thanks
