### ISSUE TITLE
FragPipe not recognizing Philosopher

### ISSUE THREAD

**Issue by mbimegan** [Nesvilab/philosopher#467]
Hi I'm having issues with FragPipe not recognizing the version of Philosopher - is there anyway I can fix this?

**Comment by fcyu** [comment]
Can you share the screenshot of the config tab in FragPipe?

Thanks,

Fengchao

**Comment by mbimegan** [comment]
Hi Fengchao,

Here is the config page.

Megan

**Comment by fcyu** [comment]
I see nothing;)

![image](https://github.com/Nesvilab/philosopher/assets/6926299/8d893e2c-9fb8-4c21-a0ec-7364aff23513)

**Comment by mbimegan** [comment]
![Capture](https://github.com/Nesvilab/philosopher/assets/148150716/3124dbcf-2e5b-4d40-a1a4-f663654c68b3)

oops sorry I responded by email and didn't realize the attachment wouldn't attach!

**Comment by fcyu** [comment]
Yeah, replying the email often causes issues, which is annoying.

As to the issue, the error message actually has already told you the reason: " there are spaces in the path". Removing them will solve the issue.

Best,

Fengchao

**Comment by mbimegan** [comment]
Hi Fengchao, 

MSFragger and IonQuant gave me the same error message but were able to be recognized - is this just a property of Philosopher?

**Comment by fcyu** [comment]
It seems that there is a bug when checking the MAFragger and IonQuant executable files. They will likely crash after you start the job even FragPipe didn't warn you.

Best,

Fengchao

**Comment by fcyu** [comment]
Actually, there will be a warning window when you specify a MSFragger or IonQuant path with spaces. I guess you ignored it.

![image](https://github.com/Nesvilab/philosopher/assets/6926299/752eb4cd-5219-4ca8-bb1d-fdb00eb1a61a)

Anyway, I have added one more layer of checking and warning to prevent spaces in those tools: https://github.com/Nesvilab/FragPipe/commit/17610c137883360fd7bda3edd45122a0e5de69be

Best,

Fengchao
