### ISSUE TITLE
Error opening a temp file

### ISSUE THREAD

**Issue by Maithy15** [Nesvilab/philosopher#469]
Hi,

I restarted the LFQ Phospho workflow and got a new error now. Below is the error and the full log is attached.

[ERROR:] fin: error opening interact-timsTOF2_4632_9-16-2023_Slot2-29_140923_TIMS02_JoFr_Phospho_DDA_SCC058.pep.xml.tmp.a20960
Process 'PTMProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2023-10-20_09-56-36.txt](https://github.com/Nesvilab/FragPipe/files/13051725/log_2023-10-20_09-56-36.txt)

Thanks
Maithy

**Comment by fcyu** [comment]
There were issues in your drive or file system. Please troubleshoot locally with your IT department.

Best,

Fengchao
