### ISSUE TITLE
Cannot read file/Error parsing the file

### ISSUE THREAD

**Issue by WenSheng-Ye** [Nesvilab/philosopher#472]
Hello, 
         I have run the Validation with filter in "--sequential --prot 0.01 --psm 0.01 --mapmods" mode. But the parsing error has appeared. Did I set some parameter in wrong method?
 
[log_2023-11-19_06-32-45.txt](https://github.com/Nesvilab/philosopher/files/13402808/log_2023-11-19_06-32-45.txt)

Yours Sincerely,
Sheng-Ye

**Comment by fcyu** [comment]
There are temp files (maybe) from the previous job crashing Philosopher. Could you delete `interact.pep.xml.tmp.a35368` and all other files with the pattern `interact.pep.xml.tmp.*`, and try again?

Thanks,

Fengchao

**Comment by WenSheng-Ye** [comment]
I try it later, thx.

Yours Sincerely,
Sheng-Ye

**Comment by WenSheng-Ye** [comment]
Hello,
I have discovered another problem.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseGlycanString(StaticGlycoUtilities.java:528)
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseDefaultGlycan(StaticGlycoUtilities.java:225)
	at edu.umich.andykong.ptmshepherd.glyco.StaticGlycoUtilities.parseGlycanDatabase(StaticGlycoUtilities.java:133)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:708)
Did I make a mistake?

[log_2023-11-20_14-39-44.txt](https://github.com/Nesvilab/philosopher/files/13412312/log_2023-11-20_14-39-44.txt)


Yours Sincerely,
Sheng-Ye

**Comment by fcyu** [comment]
@dpolasky , can you take a look? It seems that the incorrect input crashed PTM-Shepherd.

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi Sheng-Ye,
This error means there was an unsupported glycan in the provided database. We currently support HexNAc, Hex, NeuAc/Gc, Fucose, and phospho/sulfo modifications - anything else (or spelling/formatting errors) will cause this error. In the next version, any monosaccharides/modifications will be supported, but currently it is just the list above. If you remove any other glycans from your database, it should clear the error.

Best,
Dan

**Comment by WenSheng-Ye** [comment]
Thank you very much, these help me a lot. I will set it again.

Yours Sincerely,
Sheng-Ye
