### ISSUE TITLE
peptide prophet xml parsing error

### ISSUE THREAD

**Issue by mremachine1** [Nesvilab/philosopher#475]
- Describe the issue or question:
I received an error in running peptide prophet after msfragger and am unsure why i recieved an xml parsing error on the 74th file especially when all files were generated by one msfragger run for the set.

- Upload your log file
[postdiaumpire_fragpipe_log_manifest_and_workflow.zip](https://github.com/Nesvilab/FragPipe/files/13508173/postdiaumpire_fragpipe_log_manifest_and_workflow.zip)

**Comment by mremachine1** [comment]
hey feng chao, Which other files would help out? I supplied the manifest workflow and run commands

**Comment by fcyu** [comment]
Since the error message is as the following

```shell
/fastscratch/myscratch/smburke/frag_working_dir_slurm/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E47_Q2.mzML(1) : parseOffset() 2: Syntax error parsing XML.
 file 74: /fastscratch/myscratch/smburke/frag_working_dir_slurm/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E47_Q2.pepXML
time="19:39:43" level=error msg="Cannot execute program. there was an error with PeptideProphet, please check your parameters and input files"
```

Could you please share `JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E47_Q2.mzML`, `JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E47_Q2.pepXML`, and `2023-11-25-decoys-reviewed-contam-UP000005640.fas` with us as a start? Here is the link to upload the file https://www.dropbox.com/request/YxldzreT9DWelOnUUlL2

Thanks,

Fengchao

**Comment by mremachine1** [comment]
I've uploaded them to dropbox. we are currently trying to run without them but if we can include them that would be better

**Comment by fcyu** [comment]
Thanks for your file but I have no idea why PeptideProphet crashed with your file. Maybe you can create a ticket to their google group: https://groups.google.com/g/spctools-discuss?pli=1 since they are maintaining PeptideProphet.

Best,

Fengchao

**Comment by anesvi** [comment]
Trying using percolator if it is a closed search or a mass offset search with not too many mass shifts
