### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock! in PhilosopherFilter despite threads=8

### ISSUE THREAD

**Issue by vicpaton** [Nesvilab/philosopher#476]
Hi! I am trying to run fragpipe in headless mode to process around 70 DDA files (converted to mzml by MSConverter). I am trying to get this to run in a slurm-controlled cluster, but I am constantly getting this error: 
`time="10:16:29" level=info msg="Executing Filter  v5.0.0"`
`time="10:16:29" level=info msg="Processing peptide identification files"`
`fatal error: all goroutines are asleep - deadlock!`

I have seen in #441 that a possible fix would be to set workflow.threads>2, but I have set it to 8 and still get the same error. In case this is the same as #463, could you help me identify the file that is corrupted so that I can remove it from the run?
Thank you for your help!

I am attaching the slurm log file, the workflow config file, the database I am using (998 entries, half decoys) and one of the pepXML (i had to add the .txt extension to upload it here).

[2023-11-24-decoys-contam-uniprot_tfs.fasta.fas.txt](https://github.com/Nesvilab/philosopher/files/13598543/2023-11-24-decoys-contam-uniprot_tfs.fasta.fas.txt)
[04159_BA7_P046453_S00_I00_U01_R1_TMT11.pepXML.txt](https://github.com/Nesvilab/philosopher/files/13598527/04159_BA7_P046453_S00_I00_U01_R1_TMT11.pepXML.txt)
[fragpipe.workflow.txt](https://github.com/Nesvilab/philosopher/files/13598492/fragpipe.workflow.txt)
[slurm-3147407.out.txt](https://github.com/Nesvilab/philosopher/files/13598494/slurm-3147407.out.txt)

**Comment by guoci** [comment]
From the log, the `workflow.threads=1` setting triggered a bug that caused the error, same as #441. Can you also show the log when you have `workflow.threads=8`?

**Comment by vicpaton** [comment]
I found out that the slurm controller was overwriting the thread number, I reconfigured it and now I made sure it is using more than two threads. It is running now, the solution from #441 worked, thanks!
