### ISSUE TITLE
PhilosopherAbacus exit code: 1 when using split database

### ISSUE THREAD

**Issue by yannic-chen** [Nesvilab/philosopher#478]
Hello Fragpipe Team,

I am running samples through multiple databases and two of those would need to be split as they would produce more than 2 billion peptides. However, this resulted in the following error:

`C:\Programme\FragPipe_v20.0\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe abacus --razor --reprint --tag rev_ --protein --peptide exp_1 exp_10 exp_11 exp_12 exp_2 exp_3 exp_4 exp_5 exp_6 exp_7 exp_8 exp_9`
`INFO[10:28:48] Executing Abacus v5.0.0`
`INFO[10:28:48] Restoring PSM results`
`INFO[10:28:58] Processing combined file`
`INFO[10:28:58] Parsing combined.pep.xml`
`ERRO[10:28:58] Cannot read file. Error parsing the file`
`Process 'PhilosopherAbacus' finished, exit code: 1`
`Process returned non-zero exit code, stopping`

Fragpipe runs flawlessly with the smaller databases which do not require splitting on these samples.

I have attached the complete log. 
[log_2023-12-13_14-59-19.txt](https://github.com/Nesvilab/FragPipe/files/13661688/log_2023-12-13_14-59-19.txt)

**Comment by hdesai17** [comment]
Hi team

I'm also running into this issue in both FP v20 & v21 --
experiment group searches w/ database splitting results in this exact Abacus error; however,  without database splitting it finishes.
No experiment groups' w/ database splitting also finishes. So errors occur when both are used

Appreciate any help, thank you!!
-Heta

**Comment by fcyu** [comment]
Thanks for reporting the bug. Please find the fixed FragPipe in https://www.dropbox.com/t/z9IDmxRdXYF0zUdO

Best,

Fengchao

**Comment by hdesai17** [comment]
Thanks!
Anyway to get version with JRE?

**Comment by fcyu** [comment]
Sure, here it is https://www.dropbox.com/t/HurKqYXY3sqXbVEl

Best,

Fengchao

**Comment by djnesbitt** [comment]
> Sure, here it is https://www.dropbox.com/t/HurKqYXY3sqXbVEl
> 
> Best,
> 
> Fengchao

I've also been having this issue - would you be able to re-share the DropBox link?

Thanks,
Daniel

**Comment by fcyu** [comment]
@djnesbitt , sure. Here it is https://www.dropbox.com/t/rLtfTwzJeIVXZMzx

Best,

Fengchao

**Comment by djnesbitt** [comment]
> @djnesbitt , sure. Here it is https://www.dropbox.com/t/rLtfTwzJeIVXZMzx
> 
> Best,
> 
> Fengchao

Is this the version with the JRE?

Thanks,
Daniel

**Comment by alessandro-vai** [comment]
Has this problem been resolved in version 5.1.2? I am still experiencing the same behavior that is described here.
