### ISSUE TITLE
Philosopher 5.1.0 filter command crashed: Cannot read file. Error parsing the file 

### ISSUE THREAD

**Issue by WeiqiangChen** [Nesvilab/philosopher#481]
- Describe the issue or question:
I want to search for a project with FragPipe21.1.
It showed the following error. 

`PhilosopherFilter [Work dir: D:\20231221_ID_23258_new\data\processed\A]
D:\software\FragPipe-jre-21.1\fragpipe\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml D:\20231221_ID_23258_new\data\processed\A --protxml D:\20231221_ID_23258_new\data\processed\combined.prot.xml --razor
INFO[08:59:36] Executing Filter  v5.1.0                     
INFO[08:59:36] Processing peptide identification files      
INFO[08:59:36] Parsing D:\20231221_ID_23258_new\data\processed\A\interact-20231215_E1_NEO3_Stelzer_jlphealth_MPLGmbH_Company_MPLID23258_A_7c5p.pep.xml 
ERRO[08:59:40] Cannot read file. Error parsing the file     
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping
Cancelling 11 remaining tasks`

I copied my folder to another computer and did Fragpipe20 search there. It gets another error. 
`Internal state when error was thrown: recordCount=11453, recordData=[tr|A0A8F3I251|A0A8F3I251_9HIV1]
	at com.univocity.parsers.common.AbstractWriter.throwExceptionAndClose(AbstractWriter.java:1046)
	at com.univocity.parsers.common.AbstractWriter.addValue(AbstractWriter.java:1185)
	at Features.percolatorFormatter.editPin(percolatorFormatter.java:480)
	at Features.MainClass.main(MainClass.java:588)
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping
Cancelling 26 remaining tasks`

What should I do to let the search go through? Thanks!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-12-22_08-59-40_FragPipe21.1_error.txt.zip](https://github.com/Nesvilab/FragPipe/files/13749837/log_2023-12-22_08-59-40_FragPipe21.1_error.txt.zip)
[log_2023-12-22_09-08-31_FragPipe20_error.zip](https://github.com/Nesvilab/FragPipe/files/13749838/log_2023-12-22_09-08-31_FragPipe20_error.zip)

**Comment by WeiqiangChen** [comment]
It must be a problem with the following fasta, after I removed it from the combined fasta, it worked. 

[uniprotkb_moloney_murine_leukemia_virus_2023_12_21.zip](https://github.com/Nesvilab/philosopher/files/13753261/uniprotkb_moloney_murine_leukemia_virus_2023_12_21.zip)

**Comment by fcyu** [comment]
Thanks for the update. If you can share your whole result folder and the combined fasta file with us, I can take a look. Here is the link to upload the files https://www.dropbox.com/request/I8fhr998yBbnlU3ZmKl3

Best,

Fengchao

**Comment by WeiqiangChen** [comment]
I have uploaded the whole folder to Dropbox. 

Thanks!

WeiQiang

**Comment by fcyu** [comment]
Hi Weiqiang,

Thank you for the files. I have located and fixed the bug. Could you try the RC version from https://www.dropbox.com/t/ggpGMJSfvaCXRRdB ?

Thanks,

Fengchao

**Comment by WeiqiangChen** [comment]
Thanks FengChao. Now it works. 

Best! 
WeiQiang
