### ISSUE TITLE
FragPipe 19.1 is not compatible with Philosopher 5.1.0

### ISSUE THREAD

**Issue by WenSheng-Ye** [Nesvilab/philosopher#482]
Hi, I have discovered a problem. 

[log_2024-01-17_19-54-31.txt](https://github.com/Nesvilab/philosopher/files/13964129/log_2024-01-17_19-54-31.txt)

PhilosopherReport [Work dir: C:\fetuin0117-4\fetuin0117_1]
C:\FragPipe-jre-19.1\fragpipe\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe report
INFO[19:54:31] Executing Report  v5.1.0                     
INFO[19:54:31] Creating reports                             
ERRO[19:54:31] Cannot read file. open .meta\pep.bin: The system cannot find the file specified. 
Process 'PhilosopherReport' finished, exit code: 1
Process returned non-zero exit code, stopping

Hope can get your help.

Sincerely yours,
Sheng-Ye

**Comment by fcyu** [comment]
FragPipe 19.1 is not compatible with Philosopher 5.1.0. Please upgrade it to version 21.1.

Best,

Fengchao
