### ISSUE TITLE
idconvert erases all files in the working dir if no workspace exists 

### ISSUE THREAD

**Issue by GeorgesBed** [Nesvilab/philosopher#49]

**Comment by GeorgesBed** [comment]
INFO[08:48:56] Current Philosopher build and version         build=201903131612 version=20190313

**Comment by prvst** [comment]
@GeorgesBed 

A similar issue was reported last week for msconvert, I issued an updated to prevent that. Please, try the latest version and report back if you still see this happening.

**Comment by GeorgesBed** [comment]
Ok thank you.

**Comment by GeorgesBed** [comment]
Hello,
I would like to inform you that, even when using the lastest release, idconvert erases everything in the current directory if no workspace exists.

**Comment by prvst** [comment]
@GeorgesBed 

Thanks for reporting, we will disable these tools for now until we figure it out what is the cause of the issue. The next Philosopher version will be able to report mzID files natively.
