### ISSUE TITLE
FragPipe 20.0 is not compatible with Philosopher 5.1.0

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/philosopher#491]
Philosopher is throwing this error on the second sample in the batch. 
ERRO[12:05:05] Cannot read file. open C:\data\Nathan\tiven0234\MSFragger_output\OTA_2\.meta\db.bin: The system cannot find the file specified. 
Log is attached.

 - OS: Windows
 - Versions: MSFragger: 4.0, IonQuant: 1.10.12, Philosopher: 5.1.0
[log_2024-04-29_12-05-05.txt](https://github.com/Nesvilab/philosopher/files/15195039/log_2024-04-29_12-05-05.txt)

**Comment by fcyu** [comment]
FragPipe 20.0 is not compatible with Philosopher 5.1.0. Please upgrade FragPipe, MSFragger, and IonQuant.

Best,

Fengchao

**Comment by ndtivendale** [comment]
Ah. I updated everything else but not FragPipe! I will do that now.
