### ISSUE TITLE
'PhilosopherFilter' finished, exit code: 1

### ISSUE THREAD

**Issue by Patrick-W1345** [Nesvilab/philosopher#492]
Hi all,

I have been using Frapipe for only a little bit now and acknowledge my lack of understanding on these issues so any help would be much appreciated. I have run into issues when trying to run a particular database. All my other databases have run successfully with the same workflow. Previously, fragpipe would crash on the PhilosopherDbAnnotate step, however I reformatted the database in accordance with the wiki and solved that issue.

Now im having a new issue arise with PhilosopherFilter (printout of the error at bottom). I am wondering if this is related to the database format or something else? some other info that may help(?): the database is very large (27million sequences without decoys) and Im using the database split command to split the database 10 times; I have tried completely clearing the working directory in case there were problematic files being carried over between runs and this did not solve the issue. Log file and workflow attached. Pep files are quite large so if these are needed would need to be uploaded in another way. Sorry if this is not all the info that you need - please let me know if I should add anything else and thank you so much for your help!

PhilosopherFilter [Work dir: /home/pwhite/Msfragger_tests/test15_fulldb_0.01FDR/220718_1082_097_01_09]
/home-pool/home/pwhite/MSfragger_tools/philosopher filter --sequential --prot 0.01 --tag rev_ --pepxml /home/pwhite/Msfragger_tests/test15_fulldb_0.01FDR/220718_1082_097_01_09 --protxml /home/pwhite/Msfragger_tests/test15_fulldb_0.01FDR/combined.prot.xml --razor
time="16:10:39" level=info msg="Executing Filter  v5.1.0"
time="16:10:40" level=info msg="Processing peptide identification files"
time="16:10:40" level=info msg="Parsing /home/pwhite/Msfragger_tests/test15_fulldb_0.01FDR/220718_1082_097_01_09/interact-220718_1082_097_01_09.mod.pep.xml"
time="16:24:54" level=error msg="Cannot read file. Error parsing the file "
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

[fragger.params.txt](https://github.com/Nesvilab/philosopher/files/15203427/fragger.params.txt)
[fragpipe copy.workflow.txt](https://github.com/Nesvilab/philosopher/files/15203428/fragpipe.copy.workflow.txt)
[log_2024-05-01_16-04-56.txt](https://github.com/Nesvilab/philosopher/files/15203429/log_2024-05-01_16-04-56.txt)

**Comment by fcyu** [comment]
Thanks for using FragPipe. I believe you uploaded the wrong log file:
```shell
Process 'WorkspaceCleanInit' finished, exit code: 0
MSFragger [Work dir: /path/Msfragger_tests/test15_fulldb_0.01FDR]
/bin/python3.10 /path/MSfragger_tools/fragpipe/tools/msfragger_pep_split.py 4 "java -jar -Dfile.encoding=UTF-8 -Xmx120G" /path/MSfragger_tools/MSFragger-4.0/MSFragger-4.0.jar /path/Msfragger_tests/test15_fulldb_0.01FDR/fragger.params /path2/220718_1082_097_01_09.raw /path2/220718_1082_097_01_11.raw
Processing interrupted, stopping MSFragger

~~~~~~~~~~~~~~~~~~~~
Cancelling 28 remaining tasks
```

Best,

Fengchao

**Comment by Patrick-W1345** [comment]
Hi @fcyu - you are totally right - my apologies. I see I don't have a log file from the actual run with the crash - is this strange? Is there an option I may have selected to not export a log file? I have the filter log where the crash occurred attached here but no long report for the whole run. 

[filter.log](https://github.com/Nesvilab/philosopher/files/15204086/filter.log)

**Comment by fcyu** [comment]
It seems that you ran FragPipe in headless mode? It won't save the log file it FragPipe crashes. You probably need to redirect the output to text file when running it.

Could you also run FragPipe in GUI mode to make sure that all the settings are correct, first?

Thanks,

Fengchao

**Comment by Patrick-W1345** [comment]
Thank you for the insight and help @fcyu - you are correct, I was running it in headless mode - its taken me a little bit to it to run all the way through in the GUI - settings seem correct - here is the updated log file. 
[log_2024-05-05_15-17-32.txt](https://github.com/Nesvilab/philosopher/files/15214107/log_2024-05-05_15-17-32.txt)

**Comment by fcyu** [comment]
Could you remove `.` in the directory name `/path/Msfragger_tests/test15_fulldb_0.01FDR` and try again?

Thanks,

Fengchao

**Comment by Patrick-W1345** [comment]
Ill add here, there seems to be an error when returning to the machine that runs Fragpipe stating it has run out of storage. Is Fragpipe creating large temporary files? Possibly this is related to the size of the dropbox we start with (~30gb)?

**Comment by fcyu** [comment]
> Ok rerun without the period and crashed with same issue
> [log_2024-05-05_18-26-50.txt](https://github.com/Nesvilab/philosopher/files/15219762/log_2024-05-05_18-26-50.txt)

Thanks for the update. Then, I have no idea why Philosopher crashed. 

> Ill add here, there seems to be an error when returning to the machine that runs Fragpipe stating it has run out of storage. Is Fragpipe creating large temporary files? Possibly this is related to the size of the dropbox we start with (~30gb)? Wondering if this potentially provides some insight

FragPipe does not, but I am not sure about Philosopher.

Best,

Fengchao

**Comment by Patrick-W1345** [comment]
If I can add to this to potentially find a solution - I considered it could be a sequence or header name issue as per others have mentioned in other threads. However, I took my database and split it in half and ran both halves separately. Both ran to completion suggesting it is the size of the combined database that is the problem as oppose to a problem of IDs. Every time the combined database is run, I receive an error on my computer before it crashes stating 'this computer has only 0 bytes disk space remaining'. the computer has 2.7Tb of free space so this is perplexing to me. Does anyone have any thoughts on this?

**Comment by Patrick-W1345** [comment]
Last update - It was actually that combined.prot.xml was not being completely written. this is likely the result of temp files being written to a place on the machine that were not the users folder location, and that location did not have much space. The solution was to free up space on where we expected the location the temp files were being written to. So the problem actually occurred at ProteinProphet and was simply inherited by Filter. My best guess is that the computer ran out of space (but not actually as there were other drives empty) which did not crash ProteinProphet but inhibited it from completing the xml file. Happy to share more info if this is a bug you want to add a warning about!

Best,
Patrick
