### ISSUE TITLE
SequenceWindow, Ile over-representation on the n-term side

### ISSUE THREAD

**Issue by pisistrato** [Nesvilab/philosopher#500]
Hi,

I was inspecting the files generated in the tmt-report folder. I noticed a suspicious over-representation of Ile in the SequenceWindow on the n-term side, i.e. before the detected peptide sequence.
Can you comment on how that is `calculated`?
It might be real, but I was expecting a Leu to be over-represented...

**Comment by fcyu** [comment]
Yes, this is a know bug: https://github.com/Nesvilab/philosopher/issues/430

**Comment by fcyu** [comment]
Fixed in https://github.com/Nesvilab/philosopher/pull/517

Huge thanks to @hollenstein 

Best,

Fengchao
