### ISSUE TITLE
Format of custom database

### ISSUE THREAD

**Issue by FantacticMisterFox** [Nesvilab/philosopher#53]
Can you elaborate how a custom database has to be structured to work with philosopher?
Do my headers have to be inline with this format?
https://www.uniprot.org/help/fasta-headers

Thanks

**Comment by prvst** [comment]
Yes, you can use the UniProt, NCBI or ENSEMBL standard formats. If you prefer to keep using sequences from UniProt, you can use Philosopher to fetch a database for you or you can you download one from the website.

**Comment by FantacticMisterFox** [comment]
Okay I wish to use a custom generate database. So I need a simple way to generate the fasta headers. I would be fine to later on use a hash to get back to my original headers.
So I tried to construct the header like so.
```
">sp|$ident|ACN2_ACAGO Acanthoscurrin-2 (Fragment) OS=Acanthoscurria gomesiana OX=115339 GN=acantho2 PE=1 SV=1"
$ident = [O,P,Q][0-9][A-Z,0-9][A-Z,0-9][A-Z,0-9][0-9]
```
But the problems with wrong mapping persist.
Can you elaborate what philosopher needs. Because the example above is in line with the fasta standard with uniprot as far as I can see.

**Comment by prvst** [comment]
You don't actually need all the fields in there, but the more the better. The program uses the information from the header to fill the reports with information about your sequences.`>sp|$ident|` should also work.
If your construct is not working, then there still something not matching to the format. If ou send me your new file I can take a look.

**Comment by FantacticMisterFox** [comment]
http://www.bioinf.uni-leipzig.de/~john/uniprot_header_ecoli.tar.gz
http://www.bioinf.uni-leipzig.de/~john/results_tsv.tar.gz
thanks

**Comment by prvst** [comment]
Did you noticed that your file is called `uniprot_proteom_ecoli.fasta` but you have inside _Acanthoscurria_ sequences ?

**Comment by FantacticMisterFox** [comment]
no I was not aware. should not be the case can you tell me the header? I use the official ncbi annotation to get the proteins.

**Comment by FantacticMisterFox** [comment]
oh wait no I just used the Acanthoscurria header to have something. to make the header in line with the uniprot standard. I hope that philosopher is not checking the species.
I just used the example from the this link:
https://www.uniprot.org/help/fasta-headers

**Comment by prvst** [comment]
Just make sure first that you used the same database for the search and for the post processing. I ddi a quick search on your db file using these IDs P00761, Q86YZ3 and they don't exist. These two are in your result table but not in your database file.

**Comment by FantacticMisterFox** [comment]
ah yes I added a crap database before processing it with philosopher database. 
`cat uniprot_proteom_ecoli.fasta crap.fasta > current_db.fasta`
and with this the resulting database is not inline with the db uniprot standard. forgot about this line. I will run philosopher again, this time changing all the headers. hope this solves it.
my mistake.

**Comment by anesvi** [comment]
You can use --contam tag in database command to add contaminants that way

**Comment by prvst** [comment]
Yes, as Alexey mentioned above, you can use Philosopher to generate your databases, the command also adds contaminants, you can find examples in the [ Database Wiki section](https://github.com/Nesvilab/philosopher/wiki/Database).

**Comment by FantacticMisterFox** [comment]
yes but unfortunately I implemented in my scripts a contamination protein list i got from the lab. and some of the scripts downstream depend on the headers. i just discovered late the option from philospher. hence i was not eager changing it if not necessary.
also this was not the main problem. i still want to use different databases.

**Comment by anesvi** [comment]
Thanks for using the tools and helping us to sort things out!

**Comment by FantacticMisterFox** [comment]
Thank you providing it this way and not just in the tpp. And also the quick service.
With the headers changed like so, the analysis seems to work with out problems:
```
>sp|O00A00|
>sp|O00A01|
...
```

I did hope that this will also solve the problem with memory allocation problem. but it does not. More in the other thread.
Oh and I would suggest to add the feature of adding custom databases with header structure different to uniprot. Using own tailored DBs is something that some people would like to do, not just me.

**Comment by FantacticMisterFox** [comment]
Thank you providing it this way and not just in the tpp. And also the quick service.
With the headers changed like so, the analysis seems to work with out problems:

```
>sp|O00A00|
>sp|O00A01|
...
```
I did hope that this will also solve the problem with memory allocation problem. but it does not. More in the other thread.
Oh and I would suggest to add the feature of adding custom databases with header structure different to uniprot. Using own tailored DBs is something that some people would like to do, not just me.
