### ISSUE TITLE
cannot open file: there was an error trying to create the decoy database

### ISSUE THREAD

**Issue by tobiasko** [Nesvilab/philosopher#55]
Hi there,

I am trying to setup a target+decoy DB incl. contaminants using philosopher, but there is always an error:

```
PS D:\Software\MSFragger-20190222> .\philosopher_windows_amd64.exe database --id UP000005640 --contam
INFO[14:16:56] Executing Database 20190418
INFO[14:16:56] Fetching database
INFO[14:16:56] Processing decoys
INFO[14:16:56] Creating file
FATA[14:16:56] cannot open file: there was an error trying to create the decoy database
PS D:\Software\MSFragger-20190222>
```
Why is this failing?

**Comment by prvst** [comment]
did you ran the `workspace` command first ?

**Comment by tobiasko** [comment]
No. I just run the command shown in the FragPipe9., Sequence DB tab. I meanwhile figured out that an active workspace is needed. I would suggest to def. a more instructive error message. Something like: "No workspace found." Instead of "can not open file ...".
