### ISSUE TITLE
unknown command idconvert 

### ISSUE THREAD

**Issue by tobiasko** [Nesvilab/philosopher#56]
Hi there,

has the command idconvert been removed from philosopher?

```
PS D:\projects\p2501\Workunit_183339\MSFragger_output\closed_search\male> D:\Software\MSFragger-20190222\philosopher_win
dows_amd64.exe idconvert
Error: unknown command "idconvert" for "philosopher"
Run 'philosopher --help' for usage.
FATA[15:57:26] unknown command "idconvert" for "philosopher"
```
I am running
INFO[16:01:12] Current Philosopher build and version         build=201904182204 version=20190418

**Comment by prvst** [comment]
Yes. The idconvert command was crashing and deleting files from the computer. For now we decided to remove the command while we investigate what could be the cause of the problem.
