### ISSUE TITLE
PTMprophet with msfragger

### ISSUE THREAD

**Issue by GeorgesBed** [Nesvilab/philosopher#57]
Hello dev team,
I would like to report that when trying to run ptmprophet on msfragger output i encounter the error bellow:

philosopher ptmprophet --massdiffmode interact.pep.xml

INFO[17:39:44] Executing PTMProphet 20190418                
No index list offset found. File will not be read.
ERROR: cannot read scan in data file file1.mzML exiting ...
INFO[17:39:46] Done

I am using MSFragger-20190222 and philosopher v1.0.1

Thank you.

**Comment by prvst** [comment]
Can you share your interact.pep.xml ?

**Comment by prvst** [comment]
Also, make sure that your mzml file is in the same folder as the pep.xml file

**Comment by GeorgesBed** [comment]
Hello, 
indeed the mzML was in the same folder but it was looking for the mzXML instead.
I managed to make it work by changing the all the (raw_data=".mzXML") to (raw_data=".mzML") in the pepXML. In addition, I had to add an indexList element to the mzML file (since MSconvert doesn't support this feature based on what i've read online).

Thank you.

**Comment by JohnSuberu** [comment]
Hello,

Not sure if my problem is related to the above or not except it concerns PTMprophet.  My TMTPhospho run in FrapPipe v23 keeps exiting before completion with a warning "couldn't read scan 1940 from file..." PTMProphet exit code -1073741819

![Image](https://github.com/user-attachments/assets/80ebcdf4-766c-4643-9a0f-e010ddc04b5f)

**Comment by fcyu** [comment]
@JohnSuberu Please share the whole log file.

Thanks,

Fengchao

**Comment by JohnSuberu** [comment]
Here is the log file also 

[log_2025-05-15_16-12-32.txt](https://github.com/user-attachments/files/20230906/log_2025-05-15_16-12-32.txt)

**Comment by fcyu** [comment]
Thanks for the log file. Could you share `SB_JB_TMT18plex_phos_1.mzML` and `2025-05-12-decoys-reviewed-contam-UP000000589.fas` with us?

Thanks,

Fengchao

**Comment by JohnSuberu** [comment]
Thanks

**Comment by fcyu** [comment]
Hi @JohnSuberu ,

Thank you again for sharing the files. It is a known and fixed bug after we releases version 4.2. If you want to try the pre-released version, please send an email to `yufeATumich.edu` (replace `AT` with `@`).

Thanks,

Fengchao
