### ISSUE TITLE
philosopher filter error on pep.xml without any hits

### ISSUE THREAD

**Issue by GeorgesBed** [Nesvilab/philosopher#59]
Hello dev team,
I would like to report that when using 'philosopher filter' on a pep.xml without any psm inside (no identifications after the search) the error below is being raised:

philosopher_v101 filter --sequential --razor --mapmods --tag rev_ --pep 0.01 --prot 0.01 --models --pepxml iproph.pep.xml

INFO[14:57:39] Executing Filter v1.0.1                      
WARN[14:57:39] Razor option will be disabled because there is no protein inference data 
INFO[14:57:39] Processing peptide identification files      
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ef9e9]

goroutine 1 [running]:
github.com/prvst/philosopher/lib/err.(*Error).Error(0x0, 0x24, 0xc00002c300)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/err/err.go:134 +0x29
github.com/prvst/philosopher/cmd.glob..func5(0x84f91a0, 0xc000108300, 0x0, 0xc)
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/filter.go:53 +0xbca
github.com/spf13/cobra.(*Command).execute(0x84f91a0, 0xc000108240, 0xc, 0xc, 0x84f91a0, 0xc000108240)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x84fabc0, 0x4059ef, 0xc000030358, 0x0)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:800
github.com/prvst/philosopher/cmd.Execute()
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x2e
main.main()
	/home/pr

Thank you

**Comment by prvst** [comment]
Thanks for reporting, I'll include a error treatment for cases like that.

**Comment by prvst** [comment]
fix added to [1.1.2](https://github.com/Nesvilab/philosopher/releases/tag/v1.1.2)
Thanks
