### ISSUE TITLE
tsv reports: inconsistent 'Mapped Proteins' formatting

### ISSUE THREAD

**Issue by hayse1** [Nesvilab/philosopher#60]
In the peptide.tsv reports, Mapped Protein entries are not separated by a space (e.g. "sp|A6NHT5|HMX3_HUMAN,sp|P15502|ELN_HUMAN,sp|P50458|LHX2_HUMAN"), but are space-delimited in the psm.tsv reports (e.g. "sp|P10412|H14_HUMAN, sp|P16402|H13_HUMAN, sp|P16403|H12_HUMAN").

**Comment by prvst** [comment]
fix added to [1.1.2](https://github.com/Nesvilab/philosopher/releases/tag/v1.1.2)
Thanks
