### ISSUE TITLE
Parallel peptide prophet

### ISSUE THREAD

**Issue by andrewjmc** [Nesvilab/philosopher#61]
Thanks for a really useful tool.

I have 53 mzXML files which have been searched against a >10Gb metaproteomic database using MSFragger (database splitting; parallelised on HPC by extracting commands from the msfragger_pep_split.py script).

The peptide prophet part is slow though, taking at least an hour per file. I'd like to parallelise across multiple machines. I tried it (all accessing the same directory) but many of the processes terminated early (no specific error given through PBS system).

I presume that because philosopher is tracking workflows in the .meta directory, it is unsafe to run commands in parallel.

If this is the case, how do I safely parallelise (ideally without having to run separate database annotation commands)? Can I copy the .pepXML file to a new folder, initialise a workspace and copy the db.bin file into the .meta directory?

Thanks for your help,

Andrew

**Comment by andrewjmc** [comment]
Just to add, I experimented on my own machine and realised the database annotation is only necessary for at the filtering step, so peptide and protein prophets will run without.

I still have two difficulties:
1. Running multiple peptide prophet processes in parallel on the same folder failed, and so did copying each file pep.xml file to a new peptide prophet workspace. I will do some further experimentation
2. Even if this succeeds, for this >20Gb database the annotate command for this fails on an HPC with 200Gb RAM and 12 cores. Unfortunately, since I ran it through screen, the scrollback wasn't long enough to see what the original error was. Is there a theoretical limit to the size of database that can be used with philosopher?

Thanks again for your advice,

Andrew

**Comment by prvst** [comment]
Your assumption is correct. Because of the data management centralization, its impossible to distribute jobs like the way you described in your first message. Maybe in a near future we can distribute philosopher with a client/server architecture.

Does your nodes have access to the same storage area ? if so, what you can do is to have philosopher installed locally in each node, and automate the processing in each node using something like [gearman](http://gearman.org/)

**Comment by andrewjmc** [comment]
Thanks. Yes, they do have access to the same storage area. But do parallel
processes clash due to accessing a single .meta directory? I tried it once
and all but two of the processes failed. Perhaps it was for a different
reason but I assumed it was access related.

Best wishes,

Andrew

**Comment by prvst** [comment]
You will need to run philosopher locally on the nodes, including the workspace command. have the nodes run PeptideProphet and then you can pull back to your server the resulting interact.pep.xml.
