### ISSUE TITLE
IDconvert - output formats it can handle

### ISSUE THREAD

**Issue by MarcIsak** [Nesvilab/philosopher#62]
Hi, I just wonder what output formats/database search engine results  that your IDconvert function can handle? It would be nice to be able to convert an array of output formats to pepXML so that they can go into peptideProphet and iProphet.

**Comment by prvst** [comment]
The IDconvert function was temporarily disabled due to unwanted file deletions. The program behind this command was the same idconvert provided by proteowizard.
