### ISSUE TITLE
Label free quant question

### ISSUE THREAD

**Issue by 2kleio** [Nesvilab/philosopher#68]
Hi there,
Thanks again for a very useful tool.
Is it possible to add to the intensity-based label-free quantification the option to include also peaks identified following matching between different samples within the same experiment (like match-between runs in MaxQuant for example)?
Best regards,
O

**Comment by anesvi** [comment]
We have been discussing this for a while. It is extra work to add alignment between runs, and if we do it should probably be a separate tool (not in philosopher).
That way we can also support reading raw files (which MSFragger can now process).
If there is a strong demand for such a feature from the users, we will see how to best add that.

Best
Alexey

**Comment by 2kleio** [comment]
Thank you very much for your reply.
It might worth looking on MoFF as a potential tool for that (https://github.com/compomics/moFF). Personally I would love to have such feature in MSFragger. 
Best regards,
O

**Comment by prvst** [comment]
@2kleio 
The label-free quantification implemented in Philosopher was based on the moFF program, so both should give you the same results (or at least extremely similar results). As Alexey mentioned above, we decided to not add match between runs for the moment.
