### ISSUE TITLE
MSFrager could support continuous search？

### ISSUE THREAD

**Issue by Golden-proteogenomics** [Nesvilab/philosopher#74]
Hello,
     If the MSFrager could support continuous search for the same work,it will be great convenient for user save time. Even if there are some files in the search process, every time you start, you have to start from scratch. So it is really a waste of time. Searching engine such as MaxQuant, Proteome Discoverer and pFind all could continue task when there are some files in the search process. Could t MSFrager do like those softwares? I believe that would be more convenient to use.

**Comment by fcyu** [comment]
MSFragger can start from the middle if there are fraggertemp files in the folder.

Best,

Fengchao

**Comment by prvst** [comment]
@Golden-proteogenomics Please, next time refer to the MSFragger repository if you have questions about MSFragger.
