### ISSUE TITLE
'Observed Modifications' mapping to unimod

### ISSUE THREAD

**Issue by hayse1** [Nesvilab/philosopher#76]
In psm.tsv reports, the mass reported in the 'Observed Modifications' column does not always correspond to Unimod (e.g. Carbofuran in the example below is 58.0293 in Unimod).

(MSFragger 2.1, Philosopher 1.5.2)

![image](https://user-images.githubusercontent.com/16582242/66960585-beb7d980-f03a-11e9-9e04-5c2735212662.png)

**Comment by prvst** [comment]
added to source v1.5.2
