### ISSUE TITLE
"Observed modifications" don't match "Original/Adjusted Delta Mass"

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#79]
Hi Felipe,

I think this issue is different from [https://github.com/Nesvilab/philosopher/issues/76](https://github.com/Nesvilab/philosopher/issues/76), so I open a new one.

As what we talked before, the "Observed Modifications" don't match the delta mass. For example:
![image](https://user-images.githubusercontent.com/6926299/67045554-85e03900-f0fc-11e9-897d-10a9e836ac3f.png)

Attached please find the zipped fragger.params. I used a human SwissProt database downloaded by Philosopher. I didn't use Crystal-C. PeptideProphet, ProteinProphet, and the filter command were run with the default open search settings from FragPipe.

Could you please take a look when you have time?

[fragger.params.zip](https://github.com/Nesvilab/philosopher/files/3741230/fragger.params.zip)

Thanks,

Fengchao

**Comment by prvst** [comment]
fixed and added to source v1.5.2
