### ISSUE TITLE
change temporary directory for database command

### ISSUE THREAD

**Issue by rababerladuseladim** [Nesvilab/philosopher#83]
Hi,
generating a database with decoys and contaminants using the command `philosopher database --custom myfasta.fasta --contam` fails with the following error message:
`FATA[13:13:08] Cannot write file. write /tmp/a3eee851-380a-4005-b665-39079bc81745/myfasta.fasta: no space left on device`
On our machines, the system tmp dir (as set in the `TMPDIR` environment variable) is lying on another drive. 
Would it be possible to have philosopher respect that environment variable? Or is there a way to specify a temporary directory?
As a workaround, I replaced the temporary directory created by philosopher with a softlink.

**Comment by prvst** [comment]
@rababerladuseladim 
It might be possible but I would need some time to plan this change, the definition of the system paths plays an important role in the program and affects almost everything.

**Comment by prvst** [comment]
Added to source v4.0.0
