### ISSUE TITLE
Error with spectraST library searches during filter

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/philosopher#87]
Dear Felipe,

using the philosopher 1.5.1 the following error code occurs when I try to filter SpectraST search results:

Cannot decode packed binary. strconv.ParseFloat: parsing "Normal": invalid syntax

The error seems to be caused by some string encoded values in the pep.xml, i.e. the fields "lib_remark" and "lib_status" contain strings instead of numbers. I was able to circumvent the error by changing the values for these two fields to numerical values manually in the interact.pep.xml file, but perhaps you could modify philosopher to ignore these fields?

Best,
Juergen

**Comment by prvst** [comment]
Can you paste the error log in here? It would be useful if you could share your pep.xml as well.

**Comment by JB91451** [comment]
Dear Felipe, I just send you an email with the download link.

Also find the error log here:

C:\TPP\data\JB\PhilosopherError>B:/Software/Philosopher/philosopher_151/philosopher filter --pep 0.001 --pepxml merge_cid_data_splib_interact.pep.xml --picked --prot 0.001 --protxml Merge_CID_data_SpLib_interact.prot.xml --psm 0.001 --tag DECOY_ 
[36mINFO[0m[16:55:26] Executing Filter  v1.5.1                     
[36mINFO[0m[16:55:26] Processing peptide identification files      
[31mFATA[0m[16:55:27] Cannot decode packed binary. strconv.ParseFloat: parsing "Normal": invalid syntax

**Comment by prvst** [comment]
thanks

**Comment by prvst** [comment]
fixed. Added to source v2.0.0

@JB91451 
We are about to release a new version, if not today, then tomorrow. If you want to get notified, scroll to the top of this page and click on the first button on the upper right corner, change from Unwatch to Releases only.
