### ISSUE TITLE
level=fatal msg="Cannot write file. open .meta/meta.bin: no such file or directory"

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/philosopher#88]
What could be causing this error when one one runs philosopher pipeline?

**Comment by javanOkendo** [comment]
036. 170909_CH_C1_T077_FT.mzML 2.4 s [progress: 43193/43193 (100.00%) - 25377.79 spectra/s] - completed 1.7 s
        037. 170909_CH_C1_T007_FT_R2.mzML 2.4 s [progress: 43702/43702 (100.00%) - 31417.69 spectra/s] - completed 1.4 s
        038. 170909_CH_C1_T009_FT.mzML 2.6 s [progress: 48693/48693 (100.00%) - 32418.77 spectra/s] - completed 1.5 s
        039. 170909_CH_C1_T010_FT_R2.mzML 2.5 s [progress: 46882/46882 (100.00%) - 36035.36 spectra/s] - completed 1.3 s
        040. 170909_CH_C1_T011_FT_R2.mzML 2.3 s [progress: 40130/40130 (100.00%) - 36415.61 spectra/s] - completed 1.1 s
        041. 170909_CH_C1_T013_FT.mzML 2.6 s [progress: 47352/47352 (100.00%) - 28252.98 spectra/s] - completed 1.7 s
        042. 170909_CH_C1_T014_FT_R2.mzML 2.4 s [progress: 41553/41553 (100.00%) - 28816.23 spectra/s] - completed 1.5 s
        043. 170909_CH_C1_T015_FT.mzML 2.5 s [progress: 47681/47681 (100.00%) - 25003.15 spectra/s] - completed 1.9 s
        044. 170909_CH_C1_T025_FT.mzML 2.5 s [progress: 45028/45028 (100.00%) - 26440.40 spectra/s] - completed 1.7 s
        045. 170909_CH_C1_T026_FT.mzML 2.5 s [progress: 45669/45669 (100.00%) - 30385.23 spectra/s] - completed 1.5 s
        046. 170909_CH_C1_T007_FT_R2.mzML 2.6 s [progress: 43702/43702 (100.00%) - 36388.01 spectra/s] - completed 1.2 s
        047. 170909_CH_C1_T009_FT.mzML 2.7 s [progress: 48693/48693 (100.00%) - 30975.19 spectra/s] - completed 1.6 s
        048. 170909_CH_C1_T010_FT_R2.mzML 2.5 s [progress: 46882/46882 (100.00%) - 36007.68 spectra/s] - completed 1.3 s
        049. 170909_CH_C1_T011_FT_R2.mzML 2.4 s [progress: 40130/40130 (100.00%) - 36415.61 spectra/s] - completed 1.1 s
        050. 170909_CH_C1_T013_FT.mzML 2.5 s [progress: 47352/47352 (100.00%) - 29558.05 spectra/s] - completed 1.6 s
        051. 170909_CH_C1_T014_FT_R2.mzML 2.3 s [progress: 41553/41553 (100.00%) - 29638.37 spectra/s] - completed 1.4 s
        052. 170909_CH_C1_T015_FT.mzML 2.8 s [progress: 47681/47681 (100.00%) - 26445.37 spectra/s] - completed 1.8 s
        053. 170909_CH_C1_T025_FT.mzML 2.6 s [progress: 45028/45028 (100.00%) - 26455.93 spectra/s] - completed 1.7 s
        054. 170909_CH_C1_T026_FT.mzML 2.6 s [progress: 45669/45669 (100.00%) - 30405.46 spectra/s] - completed 1.5 s
***************************MAIN SEARCH DONE IN 12.239 MIN***************************

*******************************TOTAL TIME 12.246 MIN********************************
time="20:54:22" level=fatal msg="Cannot write file. open .meta/meta.bin: no such file or directory"

**Comment by prvst** [comment]
@javanOkendo 
Can you clean all workspaces and try again with the latest version?

**Comment by javanOkendo** [comment]
@prvst I did that and I have another question.
The csv file from the msstat in the philosopher pipeline does not have the right columns. can you fix that?

**Comment by prvst** [comment]
You need to be more specific than that, which columns are not right? I can run all steps from MSstats using Philosopher's msstats output.

**Comment by javanOkendo** [comment]
[msstat.zip](https://github.com/Nesvilab/philosopher/files/3869879/msstat.zip)

See the attached file @prvst
