### ISSUE TITLE
Fetch and combine multiple FASTA databases

### ISSUE THREAD

**Issue by kevinkovalchik** [Nesvilab/philosopher#91]
Hello,

Is there a way to use `philosopher database` to fetch multiple FASTA databases from uniprot and concatenate them in a single step? (e.g. a host and an infectious agent) I believe I can do this manually by downloading one first and then using `-add` when I fetch another, but the pipeline I'm setting up is automated for a lot of different samples so this would get a little more complicated than I would like. Can it be done with a single command?

Thanks!
Kevin

**Comment by prvst** [comment]
The current version can't do something like that but I'll add your request to our backlog and include this as an option for the next release.

**Comment by kevinkovalchik** [comment]
Okay, thanks.

**Comment by prvst** [comment]
Added to V4.0.0
