### ISSUE TITLE
Data base not available error!

### ISSUE THREAD

**Issue by aliyurtsevenn** [Nesvilab/philosopher#95]
Hello, I go through the steps one by one in the website for TMT analysis : https://github.com/Nesvilab/philosopher/wiki/TMT-analysis

At the step of filtering I have got an error:

WARN[15:08:07] Cannot marshal file. open .meta/db.bin: no such file or directory 
WARN[15:08:07] Cannot serialize file. EOF                   
FATA[15:08:07] Database data not available, interrupting processing

I looked at my .meta file and saw that there is indeed no db.bin file created. Because of that I also had a trouble in quantification step. After creating annotation.txt file, I have typed: 
>philosopher labelquant --plex 10 --dir . I got this error: 

Cannot read file:open .meta/ev.param.bin: no such file or directory 

It would be great if you help me about this? Thank you in advance. 

Best Regards.

**Comment by aliyurtsevenn** [comment]
Apparently, I have created meta data before in the home directory. I have just copied  both db.bin file and meta.bin file into the meta data in workspace directory and the problem solved.

**Comment by prvst** [comment]
I'm glad you found out the issue. Next time you should run the [database](https://github.com/Nesvilab/philosopher/wiki/Database) command right after initiating the workspace.
