### ISSUE TITLE
TMT -labeling quantification

### ISSUE THREAD

**Issue by spoudel77** [Nesvilab/philosopher#99]
Hi, 

I have interact.pep.xml and interact.prot.xml and when I wanted to perform label quantification, it gives me an error. 
INFO[09:13:07] Executing Isobaric-label quantification  v2.1.1
FATA[09:13:07] Cannot read file:open .meta/ev.param.bin: no such file or directory

Has anyone seen this before?

I have annotation.txt file 
sig126 S1
sig127N S2
sig127C S3
sig128N S4
sig128C S5
sig129N S6
sig129C S7
sig130N S8
sig130C S9
sig131N S10
sig131C S11

The code used is 
#!/bin/bash
set -xe

dataDirPath="/research/projects/penggrp/psychENCODE/penggrp/software_dev/PTM_study/ThermoRawFile_Test_NeuronData/TestSet"

annotFile="/research/projects/penggrp/psychENCODE/penggrp/software_dev/PTM_study/annotation.txt"

$philosopherPath workspace --clean
$philosopherPath workspace --init
$philosopherPath labelquant --annot $annotFile --plex 11 --dir $dataDirPath

$philosopherPath report
$philosopherPath workspace --clean

Thank you for the help.

Sincerely,
Suresh

**Comment by prvst** [comment]
@spoudel77 

I see two different issues here, 1) there are some steps missing from your script and 2) your annotation file is not using the standard Thermo label names. I advise you to carefully read our [documentation](https://github.com/Nesvilab/philosopher/wiki), specially the [TMT analysis](https://github.com/Nesvilab/philosopher/wiki/TMT-Analysis) tutorial.

**Comment by spoudel77** [comment]
Thank you. I didn't keep rest of the script. I just kept the script that had problem. I will check the annotation file, only thing the document says tell Philosopher what sample is in each TMT channel. I will try with real sample name.

**Comment by spoudel77** [comment]
Thanks Felipe for the suggestion. I had only one error.
sig126 S1
sig127N S2
sig127C S3
sig128N S4
sig128C S5
sig129N S6
sig129C S7
sig130N S8
sig130C S9
sig131N S10
sig131C S11

should be 


126 S1
127N S2
127C S3
128N S4
128C S5
129N S6
129C S7
130N S8
130C S9
131N S10
131C S11

I got my output files
